### PR TITLE
New detector plugin: MediaPipe

### PR DESCRIPTION
**Pull request by skrashevich**
This pull request adds a new MediaPipe detector plugin, enhancing its object detection capabilities. The plugin utilizes the MediaPipe library, which has been added to the requirements-wheels.txt file. Additionally, the Dockerfile and necessary files have been updated to support the new detector.

example configuration:

```
mediapipe:
  type: mediapipe
model:
  path: /efficientdet_lite2_fp32.tflite
  width: 448
  height: 448
```

### CODE REVIEW

**Comment by NickM-27** [comment]
What hardware does this run on? What inference times are you seeing?

**Comment by skrashevich** [comment]
11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
image

**Comment by NickM-27** [comment]
Interesting, what advantage does it provide over openvino?

**Comment by skrashevich** [comment]
Right now mediapipe python bindings allows use "out of the box" only the CPU inference. But in the near future, developers promise to update the build scripts to change this. (now to use GPU or TPU inference, you need to do an non-trivial and magic-like manual building procedure)

**Comment by skrashevich** [comment]
> Interesting, what advantage does it provide over openvino?

It will work at the same speed even on your kettle :)

**Comment by blakeblackshear** [comment]
From what I can tell, this seems like it's just an wrapper around tensorflow lite. What am I missing?

**Comment by skrashevich** [comment]
> From what I can tell, this seems like it's just an wrapper around tensorflow lite. What am I missing?

Actually, nothing much. It's essentially a "wrapper" around other libraries, enabling the use of the same code for various different models and equipment; as well as allowing for inference to be run on low-power hardware such as the RPI3/4.

**Comment by blakeblackshear** [comment]
Does the existing CPU detector not work? It just uses the Tensorflow Lite APIs with CPU detection directly.

**Pull request closed without merging**
