### PR TITLE
docker: Enable IPv6 support in nginx

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by scho0ck** [comment]
I believe if this gets merged IPv4 support will be disabled the line should read the following instead:

llisten [::]:5000 ipv6only=off;

same for rtmp

**Review by scho0ck — CHANGES_REQUESTED** [review]
testes change to the following to allow v4 and v6

llisten [::]:5000 ipv6only=off;

llisten [::]:1935 ipv6only=off;

**Comment by stgraber** [comment]
Ah, I must have tested with an older nginx that would just respect the OS default of binding IPv4 when binding an IPv6 wildcard address.

**Review by scho0ck — APPROVED** [review]
Tested and confirmed working

**Comment by saltyautomation** [comment]
Any chance we can get this merged? 
Thanks!

**Pull request closed without merging**
