### PR TITLE
Update cameras.md

### PR DESCRIPTION
**Pull request by ProbablyAnAsdf**
Updated information for Amcrest ASH21 camera. ONVIF works when using port 80 in Frigate.

### CODE REVIEW

**Review by hawkeye217 — DISMISSED** [review]

**Comment by NickM-27** [comment]
I've seen some posts saying it doesn't work. Can you confirm what ptz actions are possible?

**Comment by ProbablyAnAsdf** [comment]
> I've seen some posts saying it doesn't work. Can you confirm what ptz actions are possible?

I'm able to rotate the camera, haven't tested functionality much beyond due to being busy.
Screenshot 2024-08-01 152524

**Review by NickM-27 — APPROVED** [review]

**Comment by hawkeye217** [comment]
> > I've seen some posts saying it doesn't work. Can you confirm what ptz actions are possible?
> 
> I'm able to rotate the camera, haven't tested functionality much beyond due to being busy. 

Great. This was likely fixed with the onvif changes in 0.14.

**Comment by hawkeye217** [comment]
To be more consistent, we can probably remove the specific mention of the ASH21 from the docs altogether. It was only there to indicate that ONVIF was not functional in contrast to the line above it that says that Amcrests are functional.

**Comment by NickM-27** [comment]
we should probably target dev instead of master

**Comment by gabigoo** [comment]
Hi I was trying this out unfortunately I can't get PTZ to work
This is my config:
cameras:
  livingroom:
    enabled: true
    onvif:
      host: 192.168.2.196
      port: 80
      user: admin
      password: XXXXX 

I get this error:
Unable to get Onvif capabilities for camera: livingroom: Unknown error: Device doesn`t support service: ptz

I am using the latest ash21 firmware and the stable docker image from Frigate. It works on Blue Iris

**Comment by gabigoo** [comment]
I did a little bit of digging.
PTZ works for the ash21-v3 with this firmware V2.800.00AC004.0 but it doesn't work for ash21-v2 with this firmware V2.680.00AC008.0. Both of those are the latest available for that specific release and they both work on Blue Iris.
https://amcrest.com/firmware/

**Comment by hawkeye217** [comment]
Perhaps Blue Iris is using the proprietary Amcrest API to control the v2 model? It may be helpful to specify in the Frigate docs that the v3 is the only one that works with onvif.

**Pull request closed without merging**
