### PR TITLE
Build CI images in parallel

### PR DESCRIPTION
**Pull request by madsciencetist**
With the Jetson images added to the CI job, it now takes so long that it times out. This PR refactors the CI workflow to build the images in four independent jobs, which each run simultaneously on their own runner:

1. `frigate-amd64` and `frigate-tensorrt`
2. `frigate-standard-arm64` and `frigate-rpi`
3. `frigate-tensorrt-jp4`
4. `frigate-tensorrt-jp5`

It also enables caching for the jetpack builds, which take 2.5 hours without it.

Review by commit.

WIP because the required cache currently exceeds the 10GB gha limit. I'm trying to understand how multi-image multi-platform builds are cached, whether caching intermediate layers is important, what makes sense for gha `scope`, whether we should cache to a `registry` instead of `gha`, how the docker cache mount interacts with the gha cache, and if there are simple ways to make the cached images smaller. That'll take a while though, so we will should merge the uncontroversial parts of this PR before getting it all perfect.

### CODE REVIEW

**Comment by NickM-27** [comment]
A few things here:
- I believe that we do not want final images to be cached, same reason why tensorrt and now rpi are not cached. 
- We still want the standard arm64 build to be done, seems that was not included
- Also wondering if it makes sense for the jetson images to `need` one of the standard builds so it can use the cache

**Comment by madsciencetist** [comment]
Why not cache final non-standard images? Don't we basically want to cache every single layer, so that they are not rebuilt if they don't need to be? Not caching rpi seems fine because it's just one quick layer, but for jetson, the `trt-wheels`, `trt-model-wheels` and `jetson-ffmpeg` intermediate images are all quite slow to build. We need to ensure that these don't have to be rebuild each time (though I'm not confident I'm doing so correctly).

The standard arm64 image is built in the second job. Job `rpi_build` consists of steps `Build and push arm64 standard build` and `Build and push RPi build`.

The jetson builds each use a custom base image, which invalidates every layer. The only thing that could be shared between a jetson image and standard build, given the current dockerfiles, is `ov-converter`, which isn't a big bottleneck. Moreover, I believe that a cache can't be shared between layers anyway. Docs state:
> As a general rule, each cache writes to some location. No location can be written to twice, without overwriting the previously cached data. If you want to maintain multiple scoped caches (for example, a cache per Git branch), then ensure that you use different locations for exported cache.

So I think we'll need to set `scope=<image>` for each of them. Testing that now.

**Comment by NickM-27** [comment]
> Why not cache final non-standard images

I think @blakeblackshear would be best to answer that 

> The standard arm64 image is built in the second job. Job rpi_build consists of steps Build and push arm64 standard build and Build and push RPi build.

Right, probably want to call that step `arm64_build` then

**Comment by blakeblackshear** [comment]
We are already at the 10gb limit for cache in github actions. If we start pushing out the layers for the standard images, then we get no benefit from caching.

**Comment by NateMeyer** [comment]
Looks like the largest time sink is building ffmpeg in the jetson images.  Is that something that can be built outside of frigate and pulled in instead?

**Comment by blakeblackshear** [comment]
@NickM-27 I think this looks fine. If you agree, feel free to approve and merge.

I do think we should look for opportunities to reduce the size of the cached layers. We will benefit from smaller layer sizes regardless of the cache type.

**Comment by NickM-27** [comment]
Merging this for now so builds can be working again, @madsciencetist if you have subsequent improvements feel free to create another PR

**Review by NickM-27 — APPROVED** [review]

**Pull request merged**
