### PR TITLE
Recordings overhaul and db performance improvements

### PR DESCRIPTION
**Pull request by blakeblackshear**
- Adds indexes to improve performance of db queries
- Fixes a bug with logic to check if plus is active
- Recordings updates
  - Substantial reduction in response time for recordings api call
  - Url is now linkable and can navigate to any arbitrary time
  - Day detail is lazy loaded to only fetch event data when requested
  - Thumbnails lazy load to reduce bandwidth use

### CODE REVIEW

**Comment by NickM-27** [comment]
Seeing this issue when opening the recordings screen for a camera:

Screen Shot 2022-05-11 at 7 17 29 AM

will do some more digging if I can get more helpful logs

**Comment by herostrat** [comment]
Unbelievable, Blake sorry for the bug in the plus logic -.-
That shouldn't have happened.

**Comment by blakeblackshear** [comment]
@NickM-27 I think this could happen if you have events in the database with `has_clip` true, but the recordings for that hour are missing. Does that sound plausible?

**Comment by NickM-27** [comment]
The latest commit fixed it, works well now 👌

**Pull request merged**
