### PR TITLE
Adjust camera motion threshold and contour area with mqtt

### PR DESCRIPTION
**Pull request by hawkeye217**
I've been able to get much better detection performance on my cameras at night by setting up Home Assistant automations to dynamically adjust ``improve_contrast`` as well as motion ``threshold`` and ``contour_area``. This effectively allows me to have a "day" and a "night" profile for my cameras that has worked flawlessly for me over the past couple of weeks.

This PR builds upon https://github.com/blakeblackshear/frigate/pull/3011 and follows the same conventions we worked through there. The only main difference is a try/except block for ensuring the mqtt payload is an integer.

On a related note, I am not sure it would be worthwhile to add these controls to the HA integration as it may make it more complex and possibly problematic for new users of HA and Frigate. Power users can easily add it to HA with an mqtt entity as I did.

### CODE REVIEW

**Review by NickM-27 — APPROVED** [review]

**Comment by NickM-27** [comment]
ping

**Comment by hawkeye217** [comment]
> ping

Thanks!

I think the failing test from the end of April had something to do with frontend issues at the time. It wasn't code that I modified. I bet it would pass now if rerun.

**Comment by NickM-27** [comment]
I don't have the powers to rerun

That being said we're seeing a different check fail now so might as well wait anyway

**Comment by NickM-27** [comment]
@hawkeye217 Okay if you sync with `release-0.11.0` this should start passing

**Comment by Anc0dia** [comment]
I tried to get this to work but no luck.  Is there something that needs to be done to force the changes to be read into Frigate?

If I publish a new value using MQTT to 

frigate/../motion_threshold/state
frigate/../motion_contour_area/state 

I can verify the new value in MQTT using MQTT explorer however if I look at the config using Frigate web ui debug I see the start-up values, not the new published values.  It also seems that changing the values has no effect on the image processing - is there a way to verify the changes are being applied?

**Comment by NickM-27** [comment]
> I tried to get this to work but no luck.  Is there something that needs to be done to force the changes to be read into Frigate?
> 
> If I publish a new value using MQTT to 
> 
> frigate/../motion_threshold/state
> frigate/../motion_contour_area/state 
> 
> I can verify the new value in MQTT using MQTT explorer however if I look at the config using Frigate web ui debug I see the start-up values, not the new published values.  It also seems that changing the values has no effect on the image processing - is there a way to verify the changes are being applied?
> 

Please read the docs. The `/state` topic is read only, you need to publish to `/set`

**Pull request merged**
