### PR TITLE
Upgrade go2rtc from 1.0.0 to 1.0.1

### PR DESCRIPTION
**Pull request by felipecrs**
https://github.com/AlexxIT/go2rtc/releases/tag/v1.0.1

### CODE REVIEW

**Comment by NickM-27** [comment]
There's going to need to be changes to the reolink and restream docs along with this as reolink http streams don't need ffmpeg (except for opus audio) same as rtsp now

**Comment by felipecrs** [comment]
Interesting. Would you like me to do it? Otherwise, I think you have permission to push changes to this branch, or even a separate PR.

**Comment by NickM-27** [comment]
> Interesting. Would you like me to do it? Otherwise, I think you have permission to push changes to this branch, or even a separate PR.

I'm good either way, if you want to go for it otherwise I can in a few hours

**Comment by felipecrs** [comment]
I'd prefer you do it then, in your own time. :)

**Review by blakeblackshear — APPROVED** [review]

**Pull request merged**
