### PR TITLE
Update rknn detector to toolkit version v1.6.0

### PR DESCRIPTION
**Pull request by MarcA711**
Changes:
- update rknn-toolkit2-lite

### CODE REVIEW

**Comment by MarcA711** [comment]
This PR introduces a breaking change:
The number of npu cores is now controlled by the option `num_cores` instead of `core_mask`. If you want to use two cores of your multicore NPU you now pass `num_cores: 2` instead of `num_cores: 0b11` or `num_cores: 3` instead of `num_cores: 0b111` for 3 cores.

**Comment by NickM-27** [comment]
I think that is a good change, seems reasonable to me and I'd not expect many users set this field

**Review by NickM-27 — APPROVED** [review]

**Comment by MarcA711** [comment]
Rockchip just released a new really big upgrade of it's Toolkit (from v1.6.0 to a new v2.0). This makes this PR kind of deprecated. I don't know how fast I am to integrate the new toolkit though. Are any releases frigate planned in the next couple of weeks?

**Comment by NickM-27** [comment]
There will not be a release from `dev` for multiple months. There is a small chance that one would come from master, but I don't believe this would be a good fit to put into master as a . release

**Comment by MarcA711** [comment]
Alright, then I will continue my work with the new toolkit.

**Pull request closed without merging**
