### PR TITLE
Standalone install script (without Docker)

### PR DESCRIPTION
**Pull request by remz1337**
I wrote a script that installs Frigate on Debian 11 without the need for Docker. I have tested this in a unpriviledged LXC (Proxmox 7.4) with Nvidia GPU passthrough for ffmpeg hardware acceleration and a Reolink camera. Everything is working :)

I've been working on this for a few days, going through the Dockerfile and various build scripts. Hopefully others can benefit from this too.

Keep up the good work! thanks

### CODE REVIEW

**Comment by NickM-27** [comment]
This has been discussed before, see https://github.com/blakeblackshear/frigate/issues/3565#issuecomment-1200405222

You could potentially share this in a discussion but anyone running this way would be doing so with an unofficially supported setup.

**Comment by remz1337** [comment]
I get it, though it wouldn't hurt to ref my script (with the disclaimer that's not the officially supported setup) somewhere in your docs, for anyone else like me that prefer not running an additional layer of abstraction in my hypervisor.

But you do you,

cheers

**Comment by blakeblackshear** [comment]
Please feel free to publish this script in your own github repo so you can maintain it. We are happy to make a reference to it in the documentation, but aren't interested in maintaining a parallel install path ourselves.

**Comment by remz1337** [comment]
Sounds good. There you go:
https://github.com/remz1337/frigate-standalone

**Pull request closed without merging**
