### PR TITLE
docs: add contributing docs

### PR DESCRIPTION
**Pull request by paularmstrong**
Hoping to get more people involved, I wanted to make sure it was written out how to get things running. I intentionally left the *Core* section blank, as I'm not familiar with the recommended way to go about it. I have some roundabout steps that I take, but maybe there are easier bits.

localhost_3000_frigate_contributing

### CODE REVIEW

**Comment by mitchross** [comment]
I followed these instructions and got it working locally... How can I debug the React JS code from vs code? Having issues there.

**Comment by paularmstrong** [comment]
@mitchross What do you mean by "debug"? What issues are you having?

Also, note: it's Preact, not React, though they are nearly identical in end results.

**Comment by mitchross** [comment]
Just trying to set break points in jsx files in VS code.  Would be helpful to set breakpoints in the raw .jsx files to debug vs chrome. Perhaps not possible, but curious if you know how to do such....

**Comment by paularmstrong** [comment]
You can use `debugger;` statements to set break points and open up your developer tools in Chrome/Firefox/Safari.

**Comment by mitchross** [comment]
> You can use `debugger;` statements to set break points and open up your developer tools in Chrome/Firefox/Safari.

Yea can do this in chrome no issue. However the code is "snowpacked" ( for lack of better terms). Trying to debug from the code I see in VScode as the code is not "snowpacked". Once you start setting break points in chrome, the source files are slightly differnt than the raw jsx. Makes it a little more confusing to debug.

**Comment by paularmstrong** [comment]
I am not totally fluent in snowpack configs. I have sourcemaps enabled, which _should_ make the debugger show the original code. It doesn't seem to totally be the case though. Would love if someone could find a way to make them better.

**Comment by mitchross** [comment]
> I am not totally fluent in snowpack configs. I have sourcemaps enabled, which _should_ make the debugger show the original code. It doesn't seem to totally be the case though. Would love if someone could find a way to make them better.

Yea lets hypothetically say I had break points here -> 
image

If I run debug here -> 
image

I successfully start up a debug session -> 
image


However, I get the unbound breakpoint error in vs code -> 
image

**Comment by paularmstrong** [comment]
This is getting really off-topic. I don't use VSCode, so I don't know how to help you with that. Maybe start a discussion or open a PR for changes that will fix what you want?

**Comment by mitchross** [comment]
> This is getting really off-topic. I don't use VSCode, so I don't know how to help you with that. Maybe start a discussion or open a PR for changes that will fix what you want?

Oh wow! Did not know there was a discussion feature now in Github. Thanks!

**Pull request merged**
