### PR TITLE
Frontend Revamp

### PR DESCRIPTION
**Pull request by blakeblackshear**
Decided to refresh the entire frontend workflow.

- Switch to vite
- Implement SWR for data fetching
- Complete rewrite of the events view
- Revamp devcontainer

TODO:
- [x] Fix datepicker calendar
- [x] Fix build for new paths
- [x] Update to Node 16
- [x] Fix light/dark mode
- [x] Update frontend developer docs

### CODE REVIEW

**Comment by blakeblackshear** [comment]
image

**Comment by NickM-27** [comment]
I really like that favorite icon (and the design in general!), I tried to do that in the old front end but being a bit of a react noob I couldn't figure it out. Really excited to check this out😃

**Comment by blakeblackshear** [comment]
Yea. All that is changing. The build is probably broken.

**Comment by blakeblackshear** [comment]
@NickM-27 fixed up the build process. You can build locally with just `make` now.

**Comment by NickM-27** [comment]
@blakeblackshear Thank you! It worked great and it is nice how simple the file is now.

**Comment by NickM-27** [comment]
Thing are looking really good! You may already know about this, but figured I would mention it just in case. In the debug screen I now see a camera for `detection_fps`

Screen Shot 2022-03-11 at 6 29 58 AM

**Pull request merged**
