### PR TITLE
Add docker healthcheck

### PR DESCRIPTION
**Pull request by felipecrs**
This is inspired by addon-vscode, which implemented this not so long ago (https://github.com/hassio-addons/addon-vscode/blob/8149899349d5d5f0f9095b4fb47950d5ad58541e/vscode/Dockerfile#L133).

This will make the container be shown as `starting`, `healthy`, or `unhealthy` in `docker ps`. Example:

```console
❯ docker ps
CONTAINER ID   IMAGE                                                          COMMAND                  CREATED              STATUS                        PORTS                                                                                                                                                                     NAMES
e8ce50efee46   ghcr.io/hassio-addons/vscode/amd64:5.11.0                      "/init"                  About a minute ago   Up About a minute (healthy)                                                                                                                                                                             addon_a0d7b954_vscode
d665a841a9bf   local/amd64-addon-netdata:1.42.4-2                             "/run.sh"                2 days ago           Up 2 days (healthy)                                                                                                                                                                                     addon_local_netdata
```

This will also present a more helpful page from the hassio panel:

chrome_SdoD1XbY2i

And finally, this will allow people using docker compose to automatically restart Frigate when unhealthy using [autoheal](https://github.com/willfarrell/docker-autoheal):

```diff
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/your/config.yml:/config/config.yml
      - /path/to/your/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
+   labels:
+     autoheal: "true"
+ autoheal:
+   restart: unless-stopped
+   depends_on:
+     frigate:
+       condition: service_healthy
+   image: willfarrell/autoheal
+   volumes:
+     - /var/run/docker.sock:/var/run/docker.sock
```

### CODE REVIEW

**Comment by NickM-27** [comment]
Thanks for the explanation on the benefits, otherwise I would lost on why this would be needed by default. 

The main thing I am concerned about is when does this healthcheck start. There is a decent chance that some users running the TensorRT images may have longer than 90 seconds to startup frigate service while the model is being generated

**Comment by felipecrs** [comment]
The official documentation around `HEALTHCHECK` is very helpful: https://docs.docker.com/engine/reference/builder/#healthcheck

> The main thing I am concerned about is when does this healthcheck start.

The healthcheck starts as soon as the container is started. However, during `start-period` all failures are ignored. As soon as the check passes during `start-period` however, the container status will be changed from `starting` to `healthy`.

If `start-period` is over, and the check is still failing, I believe it would take 45 seconds for the Frigate container to be flagged as unhealthy (because there is a retries of 3 and an interval of 15 seconds between each check).

That said:

1. The tensorrt has its own dockerfile, right? We can bump the `start-period` in there only.
2. We can relatively safely also bump the `start-period` for the default image, because as I mentioned, as soon as the check passes the container will be switched to `healthy`.

WDYT?

**Comment by NickM-27** [comment]
The default behavior will keep the container running just marking it as unhealthy correct?

I think setting a longer healthcheck in the tensorrt containers would be fine, maybe like 10 minutes or something

**Comment by felipecrs** [comment]
> The default behavior will keep the container running just marking it as unhealthy correct?

That's correct. However, when running as add-on, this may cause Supervisor to restart the add-on in case watchdog is enabled. But honestly I never tried to exercise that. I'm not sure if it actually happens.

> I think setting a longer healthcheck in the tensorrt containers would be fine, maybe like 10 minutes or something

Oh wow. I had no clue it could take that long. Ok, I'll push some changes.

**Comment by NickM-27** [comment]
> That's correct. However, when running as add-on, this may cause Supervisor to restart the add-on in case watchdog is enabled. But honestly I never tried to exercise that. I'm not sure if it actually happens.

tensorrt isn't supported in the addon anyway, so not concerned about that

**Comment by felipecrs** [comment]
Ok. I will do some tests with Supervisor now. I want to confirm how does it work.

**Comment by felipecrs** [comment]
Ok, confirmed here that when _Watchdog_ is enabled, Supervisor restarts the add-on when it becomes unhealthy:

image

https://github.com/blakeblackshear/frigate/assets/29582865/602c15e7-f647-425c-ae7f-5f97e4b39ad4

**Review by NickM-27 — APPROVED** [review]

**Comment by felipecrs** [comment]
@NickM-27, just some other things before merging:

1. Do you think it's worth to document usage of `autoheal` in the `docker-compose.yaml`? I always run Frigate as an add-on, so I have no personal opinion on this.
2. I am trying to understand whether I need to add the `HEALTHCHECK` to the rpi dockerfile as well. `HEALTHCHECK` is automatically inherited from base images BTW.

**Comment by NickM-27** [comment]
> Do you think it's worth to document usage of autoheal in the docker-compose.yaml? I always run Frigate as an add-on, so I have no personal opinion on this.

I definitely wouldn't in the main install docs because I feel like that is something that might cause confusion / complexity given different versions of docker compose and stuff. Might be worth holding off for now and adding a doc later if there are questions about it

> I am trying to understand whether I need to add the HEALTHCHECK to the rpi dockerfile as well. HEALTHCHECK is automatically inherited from base images BTW.

The inheritance is my understanding as well, in which case the main definition should suffice

**Comment by felipecrs** [comment]
> The inheritance is my understanding as well, in which case the main definition should suffice

Hm... I will have to push a new commit. RPI inherits from the `deps` target of the main dockerfile, but I only add HEALTHCHECK to the final target, not deps.

**Comment by felipecrs** [comment]
Done. It should be all good now. :)

**Comment by vajonam** [comment]
This is nice, I am using autoheal in the tensorrt to help address an bug with nvidia cgroups that causes the GPU to become unavailable. 

#7915

https://github.com/blakeblackshear/frigate/discussions/7915#discussioncomment-7104151

I understand this pertains to the addon inside HA, but can we consider something for tensorrt around the nvidia stack as well? perhaps a healthcheck that includes curl and call to nvidia-smi to make sure it can see the GPUs?

**Comment by felipecrs** [comment]
That's very doable. We can make the `HEALTHCHECK CMD` for tensorrt variant different than the one from the main image.

But I would prefer someone else does that after my PR, as I don't have an environment to test.

**Comment by NickM-27** [comment]
@felipecrs Looks like the jetson images are failing for some reason. I set the docker file version to 1.6 on the trt container that had the `HEALTHCHECK` but it still seems to fail. Do the other trt docker files need to be 1.6 as well?

On the other hand, can say that unraid also supports the container health which is pretty cool
Screen Shot 2023-10-08 at 13 25 28 PM

**Comment by felipecrs** [comment]
Oh yeah, it is required there too. I'm sorry I didn't test the trt variant.

Do you fix or should I?

**Comment by NickM-27** [comment]
Feel free to put up a fix otherwise I can later

**Comment by felipecrs** [comment]
Sure, will do.

**Comment by felipecrs** [comment]
> @felipecrs Looks like the jetson images are failing for some reason. I set the docker file version to 1.6 on the trt container that had the `HEALTHCHECK` but it still seems to fail. Do the other trt docker files need to be 1.6 as well?
> 
> On the other hand, can say that unraid also supports the container health which is pretty cool Screen Shot 2023-10-08 at 13 25 28 PM

Actually, I overlooked your comment. I am not sure why it's failing, but I will try to reproduce and check.

**Comment by felipecrs** [comment]
@NickM-27 what is happening, exactly? The container never leaves "starting" state? But is Frigate API working?

I tried reproducing here, but I am not sure what exactly I'm after.

**Comment by NickM-27** [comment]
No, the issue I'm referring to is that the Jetson builds are failing 

The screenshot was just that it is working well and pretty cool to see in unraid.

**Comment by felipecrs** [comment]
I think I got it now. I wasn't able to reproduce the issue with `make local-trt`, but `make local-trt-jp4` is indeed failing. I'm taking a look.

**Comment by felipecrs** [comment]
Ok, if you are talking about this issue:

https://github.com/blakeblackshear/frigate/actions/runs/6449643953/job/17508184542#step:4:3284

I believe it's just an intermittency with the Debian keyserver.

**Comment by NickM-27** [comment]
The build has continuously failed since this (and other) PRs were merged. Could be a coincidence but seems related. I'm not sure what it would be though.

**Comment by felipecrs** [comment]
Here is my theory:

1. dockerfile had no other changes recently, thus cache was still valid and this problem wasn't raising
1. debian servers are now using new keys to sign code
1. the base image for trt-j4 is too old (one year old), and it does not yet have the new keys
1. I changed the dockerfile, this caused cache to be invalidated and the problem to be uncovered

Solutions:

1. add the newly needed keys:

```
46.20 deb http://deb.debian.org/debian bullseye main contrib non-free
63.33 W: GPG error: http://deb.debian.org/debian bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY 605C66F00D6C9793
63.33 E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
------
Dockerfile:119
```

similar to: https://github.com/blakeblackshear/frigate/blob/0dfa2b9a1be7bbebd580f28739b1505f74659fd3/docker/main/Dockerfile#L124

2. run `apt-get update && apt-get upgrade -y` before anything else

However 1 is not required for the main image, only for the base image used in jp4 and 5.

I will craft a solution which I think is the best.

**Comment by NickM-27** [comment]
ah I see, yeah that makes sense that it was masked by the cache

**Comment by felipecrs** [comment]
- FYI: https://github.com/moby/buildkit/issues/4355

**Pull request merged**
