### PR TITLE
Add check for valid label index for object detection (#7149)

### PR DESCRIPTION
**Pull request by NateMeyer**
Issue #7149 appears to be getting invalid label indexes from the TensorRT object detection. Add a bounds check on the raw detections before indexing the label list and log a warning if an invalid index is found.

### CODE REVIEW

**Review by NickM-27 — APPROVED** [review]
Approving, looks like we have a npm dependency failing to be pulled though which is weird

**Comment by NateMeyer** [comment]
Might be a linter error?

**Comment by NickM-27** [comment]
No because even the web tests are failing `npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vitest/coverage-v8/-/coverage-v8-0.32.2.tgz - Not found`

**Comment by NickM-27** [comment]
Okay I tried another dep and it is also failing so looks like npm may be down

**Review by blakeblackshear — APPROVED** [review]

**Pull request merged**
