### PR TITLE
Always show recording link even if recordings are currently disabled

### PR DESCRIPTION
**Pull request by NickM-27**
Fix for #2610 

I keep recordings on for both of my cameras, but I have one that I only record when my dog is left at home. It is helpful to always be able to view those recordings even if they are currently disabled. I'm thinking perhaps it may be possible to check if that camera currently has any recording clips but that might also be an expensive call.

### CODE REVIEW

**Comment by blakeblackshear** [comment]
Can you test this in the event that the user never enabled record there are no recordings? Historically that caused the recordings page to go into a crazy crash loop.

**Comment by NickM-27** [comment]
> Can you test this in the event that the user never enabled record there are no recordings? Historically that caused the recordings page to go into a crazy crash loop.

Sure I'll test that! I did test with events but no recording and it worked, just so you know.

**Comment by blakeblackshear** [comment]
Events are just another way to save recordings. I'm talking about situations where there are no recordings at all for a camera.

**Comment by NickM-27** [comment]
@blakeblackshear Right, makes sense, my bad.

I tested this situation by doing a clean run with an IP camera that has recordings disabled and opening the recordings link. This is what it showed: 

Screen Shot 2022-02-11 at 3 39 46 PM

**Comment by blakeblackshear** [comment]
Looks like you broke a unit test. This is such a small change, I will include it in 0.10.0.

**Comment by NickM-27** [comment]
@blakeblackshear Thanks! Test should be passing now

**Pull request merged**
