### PR TITLE
WebUI: Show label & sub labels values next to the score

### PR DESCRIPTION
**Pull request by skrashevich**
frigate-labels-switch

### CODE REVIEW

**Comment by blakeblackshear** [comment]
I don't see a reason for this.

**Comment by skrashevich** [comment]
If sub-label exists, string "Label: 95%, SubLabel: 99%" is really non-intuitive: needs to remember, what is a label and what is sub-label...

**Comment by blakeblackshear** [comment]
Users already need to know what a sublabel is to use the dropdown filters above.

If we think it would be more intuitive to show the label and sublabel values instead, then let's just do that. There is no reason to have it be switchable.

**Comment by skrashevich** [comment]
> If we think it would be more intuitive to show the label and sublabel values instead, then let's just do that. There is no reason to have it be switchable.

done :)

**Review by blakeblackshear — APPROVED** [review]

**Pull request merged**
