### PR TITLE
Update NVIDIA section

### LINKED ISSUE #4819: [HW Accel Support]: Request to provide complete and precise documentation on how to make nVidia hwaccel work start to finish
### Describe the problem you are having

The documentation expects prior knowledge of making nVidia acceleration work in the container. But even as I am able to run `nvidia-smi` in the container (after installing `nvidia-smi` package), the ffmpeg process fails, complaining about missing `libnvcuvid.so.1`

### Version

0.11.1-2eada21

### Frigate config file

```yaml
...
ffmpeg:
  global_args: -hide_banner -loglevel info
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD129 -hwaccel_output_format yuv420p # works fine
  hwaccel_args: -c:v h264_cuvid # doesn't work
...
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  mosquitto:
    ...

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    depends_on:
      - mosquitto
    shm_size: "1024mb"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config.yml:/config/config.yml:ro
      - ./frigate/storage:/media/frigate
      - clips:/media/frigate/clips
      - recordings:/media/frigate/recordings
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1073741824
    networks:
      *REDACTED*

networks:
      *REDACTED*

volumes:
      *REDACTED*
```

### Relevant log output

```shell
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-12-30 13:11:29] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate  | Starting migrations
frigate  | [2022-12-30 13:11:29] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-12-30 13:11:29] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-12-30 13:11:30] detector.coral                 INFO    : Starting detection process: 215
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Output process started: 217
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Camera processor started for *Camera2*: 221
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Camera processor started for *Camera3*: 223
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Camera processor started for *Camera4*: 224
frigate  | [2022-12-30 13:11:30] ws4py                          INFO    : Using epoll
frigate  | [2022-12-30 13:11:30] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Camera processor started for *Camera5*: 226
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Camera processor started for *Camera6*: 230
frigate  | [2022-12-30 13:11:31] frigate.video                  ERROR   : *Camera1*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:31] frigate.video                  ERROR   : *Camera4*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:31] frigate.video                  ERROR   : *Camera5*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:31] frigate.video                  ERROR   : *Camera5*: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-30 13:11:31] frigate.video                  ERROR   : *Camera4*: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-30 13:11:32] frigate.video                  ERROR   : *Camera2*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:32] frigate.video                  ERROR   : *Camera2*: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-30 13:11:32] frigate.video                  ERROR   : *Camera7*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:32] frigate.video                  ERROR   : *Camera7*: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-30 13:11:31] frigate.video                  ERROR   : *Camera1*: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-30 13:11:31] frigate.video                  ERROR   : *Camera6*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:31] frigate.video                  ERROR   : *Camera3*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Camera processor started for *Camera7*: 231
frigate  | [2022-12-30 13:11:30] frigate.output                 WARNING : Unable to read frigate logo
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Camera processor started for *Camera1*: 233
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Capture process started for *Camera2*: 234
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Capture process started for *Camera3*: 235
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Capture process started for *Camera4*: 239
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Capture process started for *Camera5*: 242
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Capture process started for *Camera6*: 247
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Capture process started for *Camera7*: 257
frigate  | [2022-12-30 13:11:30] frigate.app                    INFO    : Capture process started for *Camera1*: 262
frigate  | [2022-12-30 13:11:30] ws4py                          INFO    : Using epoll
frigate  | [2022-12-30 13:11:31] frigate.video                  ERROR   : *Camera6*: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-30 13:11:31] frigate.video                  ERROR   : *Camera3*: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-30 13:11:33] frigate.edgetpu                INFO    : TPU found
frigate  | [2022-12-30 13:11:50] watchdog.*Camera4*                ERROR   : Ffmpeg process crashed unexpectedly for *Camera4*.
frigate  | [2022-12-30 13:11:50] watchdog.*Camera4*                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   : Input #0, rtsp, from '*RTSP*':
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   :   Metadata:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   :     title           : IP Camera Video
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   :     comment         : videoMain
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   :   Duration: N/A, start: 0.000000, bitrate: N/A
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   :   Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 1920x1080, 30 fps, 30 tbr, 90k tbn
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   :   Stream #0:1: Data: none
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   : [h264_cuvid @ 0x5580c15aff80] Cannot load libnvcuvid.so.1
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   : [h264_cuvid @ 0x5580c15aff80] Failed loading nvcuvid.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   : Stream mapping:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   :   Stream #0:0 -> #0:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   :   Stream #0:0 -> #1:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   :   Stream #0:0 -> #2:0 (h264 (h264_cuvid) -> rawvideo (native))
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera4*.detect           ERROR   : Error while opening decoder for input stream #0:0 : Operation not permitted
frigate  | [2022-12-30 13:11:50] watchdog.*Camera2*            ERROR   : Ffmpeg process crashed unexpectedly for *Camera2*.
frigate  | [2022-12-30 13:11:50] watchdog.*Camera2*            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   : Input #0, rtsp, from '*RTSP*':
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   :   Metadata:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   :     title           : IP Camera Video
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   :     comment         : videoMain
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   :   Duration: N/A, start: 0.000000, bitrate: N/A
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   :   Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 3840x2160, 15 fps, 15 tbr, 90k tbn
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   :   Stream #0:1: Data: none
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   : [h264_cuvid @ 0x56497d11ba00] Cannot load libnvcuvid.so.1
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   : [h264_cuvid @ 0x56497d11ba00] Failed loading nvcuvid.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   : Stream mapping:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   :   Stream #0:0 -> #0:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   :   Stream #0:0 -> #1:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   :   Stream #0:0 -> #2:0 (h264 (h264_cuvid) -> rawvideo (native))
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera2*.detect       ERROR   : Error while opening decoder for input stream #0:0 : Operation not permitted
frigate  | [2022-12-30 13:11:50] watchdog.*Camera3*            ERROR   : Ffmpeg process crashed unexpectedly for *Camera3*.
frigate  | [2022-12-30 13:11:50] watchdog.*Camera3*            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   : Input #0, rtsp, from '*RTSP*':
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   :   Metadata:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   :     title           : IP Camera Video
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   :     comment         : videoMain
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   :   Duration: N/A, start: 0.000000, bitrate: N/A
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   :   Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 1920x1080, 24 fps, 24 tbr, 90k tbn
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   :   Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   : [h264_cuvid @ 0x55a1334415c0] Cannot load libnvcuvid.so.1
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   : [h264_cuvid @ 0x55a1334415c0] Failed loading nvcuvid.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   : Stream mapping:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   :   Stream #0:0 -> #0:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   :   Stream #0:1 -> #0:1 (pcm_mulaw (native) -> aac (native))
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   :   Stream #0:0 -> #1:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   :   Stream #0:1 -> #1:1 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   :   Stream #0:0 -> #2:0 (h264 (h264_cuvid) -> rawvideo (native))
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera3*.detect       ERROR   : Error while opening decoder for input stream #0:0 : Operation not permitted
frigate  | [2022-12-30 13:11:50] watchdog.*Camera6*              ERROR   : Ffmpeg process crashed unexpectedly for *Camera6*.
frigate  | [2022-12-30 13:11:50] watchdog.*Camera6*              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   : Input #0, rtsp, from '*RTSP*':
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   :   Metadata:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   :     title           : IP Camera Video
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   :     comment         : videoMain
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   :   Duration: N/A, start: 0.000000, bitrate: N/A
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   :   Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   :   Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   : [h264_cuvid @ 0x55768edba5c0] Cannot load libnvcuvid.so.1
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   : [h264_cuvid @ 0x55768edba5c0] Failed loading nvcuvid.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   : Stream mapping:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   :   Stream #0:0 -> #0:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   :   Stream #0:0 -> #1:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   :   Stream #0:1 -> #1:1 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   :   Stream #0:0 -> #2:0 (h264 (h264_cuvid) -> rawvideo (native))
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera6*.detect         ERROR   : Error while opening decoder for input stream #0:0 : Operation not permitted
frigate  | [2022-12-30 13:11:50] watchdog.*Camera5*              ERROR   : Ffmpeg process crashed unexpectedly for *Camera5*.
frigate  | [2022-12-30 13:11:50] watchdog.*Camera5*              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   : Input #0, rtsp, from '*RTSP*':
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   :   Metadata:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   :     title           : IP Camera Video
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   :     comment         : videoMain
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   :   Duration: N/A, start: 0.000000, bitrate: N/A
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   :   Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   :   Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   : [h264_cuvid @ 0x5607157af5c0] Cannot load libnvcuvid.so.1
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   : [h264_cuvid @ 0x5607157af5c0] Failed loading nvcuvid.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   : Stream mapping:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   :   Stream #0:0 -> #0:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   :   Stream #0:0 -> #1:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   :   Stream #0:1 -> #1:1 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   :   Stream #0:0 -> #2:0 (h264 (h264_cuvid) -> rawvideo (native))
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera5*.detect         ERROR   : Error while opening decoder for input stream #0:0 : Operation not permitted
frigate  | [2022-12-30 13:11:50] watchdog.*Camera7*         ERROR   : Ffmpeg process crashed unexpectedly for *Camera7*.
frigate  | [2022-12-30 13:11:50] watchdog.*Camera7*         ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   : Input #0, rtsp, from '*RTSP*':
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   :   Metadata:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   :     title           : IP Camera Video
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   :     comment         : videoMain
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   :   Duration: N/A, start: 0.000000, bitrate: N/A
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   :   Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 25 fps, 25 tbr, 90k tbn
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   :   Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   : [h264_cuvid @ 0x55e8e2a46c80] Cannot load libnvcuvid.so.1
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   : [h264_cuvid @ 0x55e8e2a46c80] Failed loading nvcuvid.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   : Stream mapping:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   :   Stream #0:0 -> #0:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   :   Stream #0:1 -> #0:1 (pcm_mulaw (native) -> aac (native))
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   :   Stream #0:0 -> #1:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   :   Stream #0:1 -> #1:1 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   :   Stream #0:0 -> #2:0 (h264 (h264_cuvid) -> rawvideo (native))
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera7*.detect    ERROR   : Error while opening decoder for input stream #0:0 : Operation not permitted
frigate  | [2022-12-30 13:11:50] watchdog.*Camera1*         ERROR   : Ffmpeg process crashed unexpectedly for *Camera1*.
frigate  | [2022-12-30 13:11:50] watchdog.*Camera1*         ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   : Input #0, rtsp, from '*RTSP*':
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   :   Metadata:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   :     title           : IP Camera Video
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   :     comment         : videoMain
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   :   Duration: N/A, start: 0.000000, bitrate: N/A
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   :   Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 25 fps, 25 tbr, 90k tbn
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   :   Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   : [h264_cuvid @ 0x55c95f255300] Cannot load libnvcuvid.so.1
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   : [h264_cuvid @ 0x55c95f255300] Failed loading nvcuvid.
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   : Stream mapping:
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   :   Stream #0:0 -> #0:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   :   Stream #0:1 -> #0:1 (pcm_mulaw (native) -> aac (native))
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   :   Stream #0:0 -> #1:0 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   :   Stream #0:1 -> #1:1 (copy)
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   :   Stream #0:0 -> #2:0 (h264 (h264_cuvid) -> rawvideo (native))
frigate  | [2022-12-30 13:11:50] ffmpeg.*Camera1*.detect    ERROR   : Error while opening decoder for input stream #0:0 : Operation not permitted
frigate  | [2022-12-30 13:11:51] frigate.video                  ERROR   : *Camera1*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:51] frigate.video                  ERROR   : *Camera1*: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-30 13:11:51] frigate.video                  ERROR   : *Camera7*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:51] frigate.video                  ERROR   : *Camera7*: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-30 13:11:51] frigate.video                  ERROR   : *Camera4*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:51] frigate.video                  ERROR   : *Camera4*: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-30 13:11:51] frigate.video                  ERROR   : *Camera5*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:51] frigate.video                  ERROR   : *Camera5*: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-30 13:11:51] frigate.video                  ERROR   : *Camera6*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:51] frigate.video                  ERROR   : *Camera6*: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-30 13:11:51] frigate.video                  ERROR   : *Camera3*: Unable to read frames from ffmpeg process.
frigate  | [2022-12-30 13:11:51] frigate.video                  ERROR   : *Camera3*: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
*IRRELEVANT*
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

*IRRELEVANT*

### Any other information that may be helpful

I believe the documentation is either outdated, or the ffmpeg support is broken. Either way, it is not clear how to make nVidia hw accel work.

### PR DESCRIPTION
**Pull request by LukasMojzis**
Fix NVIDIA section so it works in the current build of Frigate
Fixes #4819

### CODE REVIEW

**Comment by NickM-27** [comment]
These docs w the just updated for 0.11 and they work for frigate 0.11. The necessary compose structures is very dependent on the host system, especially for users with multiple nvidia GPUs but also in all cases. 

I don't think removing the deploy part is a solution, we used to have less docs on this and for many users the deploy part was required and so it was added for 0.11. There will likely need to be more verbiage around different compose structures and which ones are required in which situations.

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate/pull/3233 is an example of this which links multiple issues where the current docs structure was required

**Comment by lmojzis** [comment]
Deletion reverted. For me the deploy section passes through the libraries which do not get passed through without it. I agree that removing deploy section is not necessarily needed, but I insist the environment variables are added. There's not much damage and all the difference it can make for many people.

> There will likely need to be more verbiage around different compose structures and which ones are required in which situations.

That would be welcome. Especially assuming many people would install clean distro and would need more info as to which packages are needed for which distros.

**Comment by blakeblackshear** [comment]
The environment variables are now set in the dockerfile directly, so they won't need to be set in the compose file: https://github.com/blakeblackshear/frigate/blob/dev/Dockerfile#L210-L212

If you want to update this PR with other variations of compose files, you can. Otherwise, we should close this.

**Pull request closed without merging**
