### PR TITLE
AMD GPU support with the rocm detector and YOLOv8 pretrained model download and support for edgetpu and openvino detectors

### PR DESCRIPTION
**Pull request by harakas**
Main changes/improvements:
- new rocm (AMD GPUs) and onnx detector plugins
  - onnx is more of a development thing, openvino runs same/better in general for same inputs
  - currently only yolov8 models supported
  - in theory can process any "normal" onnx files, just needs proper pre and post-processing
  - does not use quantized models so runs full f32
- yolov8 support for edgetpu detector (derived from @lkaino frigate branch)
- better yolov8 support in openvino detector
  - latest quantized yolov8 export from ultralytics wants an f32 input image
  - openvino can now also take generic yolov8 onnx files as input and run them in full f32 mode
- yolov8 pre- and postprocessing utility functions
- yolov8 model automatic download using DOWNLOAD_YOLOV8 environment variable

Possible problems: I updated openvino version to newer generic as it's needed to run the yolov8 models due to version compatibility

### CODE REVIEW

**Comment by NickM-27** [comment]
I think we need to break this up, there are a lot of changes in here that would need to be discussed separately. For example, the latest openvino version does not support the ncs2. We have not given users any notice that it will be unsupported in the next frigate version so I don't think this is the right time for that.

I would suggest 3 separate PRs where things can be discussed:
- RocM
- edgetpu
- openvino

**Comment by harakas** [comment]
So I should delete close this PR and create a new one with limited changes for rocm only?

**Comment by NickM-27** [comment]
That's what I would suggest, will make it easier to get merged while we consider the ramifications of some of the other changes

**Comment by harakas** [comment]
Closed as suggested

**Comment by harakas** [comment]
ROCm specific PR here: https://github.com/blakeblackshear/frigate/pull/9762

**Pull request closed without merging**
