### PR TITLE
Adds support for YOLO-NAS in OpenVino

### PR DESCRIPTION
**Pull request by blakeblackshear**

### CODE REVIEW

**Comment by MarcA711** [comment]
I tried to implement a structure to use the same post-processing for all detectors in this PR https://github.com/blakeblackshear/frigate/pull/11408. Yolo-nas support is already added. It would make sense if openvino uses this method to post-process yolo-nas.
rknn already implements it. All you have to do is calling the init of the base class:
https://github.com/blakeblackshear/frigate/blob/8c325801efba40c3a8f0f6deb28093942e7b20ba/frigate/detectors/plugins/rknn.py#L33
and calling the inherited function `self.post_process(output)` on your inference output:
https://github.com/blakeblackshear/frigate/blob/8c325801efba40c3a8f0f6deb28093942e7b20ba/frigate/detectors/plugins/rknn.py#L157

Also, the dimensions of `output` need to fit:
https://github.com/blakeblackshear/frigate/blob/8c325801efba40c3a8f0f6deb28093942e7b20ba/frigate/detectors/detection_api.py#L25-L29

**Comment by blakeblackshear** [comment]
@MarcA711 I think if you can export the models upstream of rknn conversion using the notebook I added here, then we can consolidate this and simplify the postprocess at the same time. Yolo-nas already supports flat format, minimum thresholds, and limiting the total detections in the output.

**Comment by remon-nashid** [comment]
Just curious, will this be able to work on AMD GPUs?

**Comment by joakim5937x** [comment]
Tried out this patch and followed the new documentation got error bellow. Sorry for being a little too eagar to get yolo-nas working!  

```
frigate  | 2024-06-01 18:27:25.708815050  Traceback (most recent call last):
frigate  | 2024-06-01 18:27:25.708826895    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2024-06-01 18:27:25.708828043      self.run()
frigate  | 2024-06-01 18:27:25.709017479    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2024-06-01 18:27:25.709019357      self._target(*self._args, **self._kwargs)
frigate  | 2024-06-01 18:27:25.709020677    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
frigate  | 2024-06-01 18:27:25.709022126      detections = object_detector.detect_raw(input_frame)
frigate  | 2024-06-01 18:27:25.709023467    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
frigate  | 2024-06-01 18:27:25.709024909      return self.detect_api.detect_raw(tensor_input=tensor_input)
frigate  | 2024-06-01 18:27:25.709026330    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 149, in detect_raw
frigate  | 2024-06-01 18:27:25.709027487      infer_request.infer(input_tensor)
frigate  | 2024-06-01 18:27:25.709029147    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 132, in infer
frigate  | 2024-06-01 18:27:25.709030621      return OVDict(super().infer(_data_dispatch(
frigate  | 2024-06-01 18:27:25.709032147  RuntimeError: Exception from src/inference/src/cpp/infer_request.cpp:223:
frigate  | 2024-06-01 18:27:25.709033591  Exception from src/plugins/intel_cpu/src/infer_request.cpp:423:
frigate  | 2024-06-01 18:27:25.709035146  Can't set the output tensor with index: 0, because the model output tensor (shape=[..20,7]) and the current tensor (shape=(0)) are incompatible
```

**Comment by blakeblackshear** [comment]
@joakim5937x Did you use the Colab Jupyter notebook included in this PR to export a compatible model?

**Comment by joakim5937x** [comment]
@blakeblackshear yep. Used code found in tour notebook herr https://github.com/blakeblackshear/frigate/blob/ov_yolonas/notebooks/YOLO_NAS_Pretrained_Export.ipynb. Tested both with colab and on local machine. Same error tho.

**Comment by Cheerpipe** [comment]
> @blakeblackshear yep. Used code found in your notebook here https://github.com/blakeblackshear/frigate/blob/ov_yolonas/notebooks/YOLO_NAS_Pretrained_Export.ipynb. Tested to export the model with colab and on local machine. Same error both times tho.

Hi.

Try setting device manually to GPU:

`device: GPU`

It worked this way for me

**Comment by joakim5937x** [comment]
> > @blakeblackshear yep. Used code found in your notebook here https://github.com/blakeblackshear/frigate/blob/ov_yolonas/notebooks/YOLO_NAS_Pretrained_Export.ipynb. Tested to export the model with colab and on local machine. Same error both times tho.
> 
> Hi.
> 
> Try setting device manually to GPU:
> 
> `device: GPU`
> 
> It worked for me this way.
> 
> By the way, any changes of get yolo-nas with tensorrt?

This solved my problem. Thanks! :)

**Comment by blakeblackshear** [comment]
Does it work if you use `device: CPU`?

**Comment by joakim5937x** [comment]
> Does it work if you use `device: CPU`?

Yes, both `GPU` and `CPU` work but as soon as i put `AUTO` I get the error again.

**Comment by blakeblackshear** [comment]
This happens with the default mobilenet model too, so its unrelated to the changes in this PR.

**Comment by MarcA711** [comment]
Hey @blakeblackshear,

I would like to write a script that converts the YOLOV-NAS model from your notebook (or any other onnx model) into rknn format, so the user doesn't have to do it himself. This would be especially useful for frigate+ users.

1. Should I include this script in the frigate repo or rather host a repo for this script myself?
2. Does this script have to be a Jupyter notebook? I personally prefer docker for this since it doesn't install any dependencies on the host. Maybe I could provide a Notebook, a normal python script (for headless systems) and a dockerfile?

**Comment by blakeblackshear** [comment]
If the dependencies for rknn conversion are already included in the Frigate container, I would just include it in this image. You could even do the conversion on startup similar to the way tensorrt models are compiled.

**Comment by MarcA711** [comment]
No, these dependencies are not included and it is even more complicated: for some reason you can do the conversion only on x86 systems. This means that one can't do the conversion on the rockchip board.

**Comment by blakeblackshear** [comment]
It's fine to put it in this repo, but it might be better in it's own so it can have its own release cycle. If it ends up working well, I will probably just do the rknn conversion for Frigate+ models at compile time just like tflite.

**Review by NickM-27 — APPROVED** [review]

**Comment by tf7846** [comment]
is there a guide to get the yolo-nas model working with frigate as homeassistant addon ? it would be better to include models with the releases for dummies like me ;-)

**Comment by NickM-27** [comment]
> it would be better to include models with the releases for dummies like me ;-)

Models can't be included due to licensing reasons

**Pull request merged**
