### PR TITLE
Add rockchip support

### PR DESCRIPTION
**Pull request by bdherouville**
Use : ffmpeg  -hwaccel drm -hwaccel_device /dev/dri/renderD128 -c:v h264_rkmpp

docker run -v /dev/dri/renderD128:/dev/dri/renderD128 ffmpeg \
  -hwaccel drm -hwaccel_device /dev/dri/renderD128 -c:v h264_rkmpp \
  -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 \
  -i rtsp://server:80/Streaming/Channels/101  -c:v copy -c:a aac -f null -

### CODE REVIEW

**Comment by blakeblackshear** [comment]
This can be added in 0.9.0, but I need people to test since I don't have a rkmpp board to test with. Anyone willing to test this with 0.9.0?

**Comment by bdherouville** [comment]
> This can be added in 0.9.0, but I need people to test since I don't have a rkmpp board to test with. Anyone willing to test this with 0.9.0?

Is it available in the beta branche ? Or is there any doc to build and use a personal docker registry ?

**Comment by blakeblackshear** [comment]
I am going to add these changes into a separate branch

**Comment by blakeblackshear** [comment]
@bdherouville can you give this image a try? `blakeblackshear/frigate:0.9.0-0f5dfea-aarch64`

Make sure you read the [release notes](https://github.com/blakeblackshear/frigate/releases/tag/v0.9.0-rc4) for 0.9.0.

**Comment by bdherouville** [comment]
> @bdherouville can you give this image a try? `blakeblackshear/frigate:0.9.0-0f5dfea-aarch64`
> 
> Make sure you read the [release notes](https://github.com/blakeblackshear/frigate/releases/tag/v0.9.0-rc4) for 0.9.0.

Perfect. I am completely reinstalling my system from scratch. So for the moment I don't have any compatibility concerns.

Thank you !

**Comment by blakeblackshear** [comment]
Just be aware there are some significant updates in the configuration.

**Comment by bdherouville** [comment]
OK, I read the release notes. I am ready. Thanks for the advice.

**Comment by bdherouville** [comment]
For the moment I have an error :

frigate    | [2021-09-27 16:47:25] watchdog.front              ERROR   : FFMPEG process crashed unexpectedly for front.
frigate    | [2021-09-27 16:47:25] watchdog.front              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate    | [2021-09-27 16:47:25] watchdog.front              ERROR   : You may have invalid args defined for this camera.
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_info: mpp version: 6cc2ef5f author: Herman Chen   2021-09-17 [mpp_list]: Add list_mode and list_move_tail
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_rt: NOT found ion allocator
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_rt: found drm allocator
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: vcodec_service: open vcodec_service (null) failed
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: hal_h264d_api: mpp_dev_init failed ret: -1
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_hal: mpp_hal_init hal h264d_rkdec init failed ret -1
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_hal: mpp_hal_init could not found coding type 7
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_dec: mpp_dec_init could not init hal
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_time: mpp_clock_put invalid clock (nil)
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_time: mpp_clock_put invalid clock (nil)
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_time: mpp_clock_put invalid clock (nil)
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_time: mpp_clock_put invalid clock (nil)
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_time: mpp_clock_put invalid clock (nil)
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_time: mpp_clock_put invalid clock (nil)
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_time: mpp_clock_put invalid clock (nil)
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_time: mpp_clock_put invalid clock (nil)
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_time: mpp_clock_put invalid clock (nil)
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_time: mpp_clock_put invalid clock (nil)
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp_time: mpp_clock_put invalid clock (nil)
frigate    | [2021-09-27 16:47:25] ffmpeg.front.detect         ERROR   : mpp[246]: mpp: error found on mpp initialization

ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args:
    - -hwaccel
    - drm
    - -hwaccel_device
    - /dev/dri/renderD128
  # Optional: global input args (default: shown below)
  input_args: -c:v h264_rkmpp -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv

**Comment by bdherouville** [comment]
I tested  again with my container


docker run -v /dev/dri/renderD128:/dev/dri/renderD128 bdherouville:frigate -hwaccel drm -hwaccel_device /dev/dri/renderD128 -c:v h264_rkmpp -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:pass@nvr/Streaming/Channels/101 -c:v copy -c:a aac  -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an test.mp4

It works flawlessly

  Metadata:
    title           : HIK Media Server V3.0.21
    comment         : HIK Media Server Session Description : standard
  Duration: N/A, start: 1632766916.049400, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 1920x1080, 7.50 fps, 7.50 tbr, 90k tbn, 15 tbc
Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 0, only the last option '-c copy' will be used.
Output #0, segment, to 'test.mp4':
  Metadata:
    title           : HIK Media Server V3.0.21
    comment         : HIK Media Server Session Description : standard
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264, yuv420p(progressive), 1920x1080, q=2-31, 7.50 fps, 7.50 tbr, 15360 tbn, 7.50 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
^Cframe=  257 fps=8.0 q=-1.0 Lsize=N/A time=00:00:35.00 bitrate=N/A speed=1.09x
video:5174kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

**Comment by spattinson** [comment]
h264_rkmpp codec in ffmpeg is for legacy kernel on rockchip rk3399 and possibly other rockchip devices, with kernel drivers and userland libraries written by rockchip. It only works with the old legacy 4.* bsp linux kernel. When I tested this previously it crashed a lot,  and eventually would not restart properly until reboot. The errors in this [reply above](https://github.com/blakeblackshear/frigate/pull/1814#issuecomment-928066251) are what you see if drivers and libraries are missing, or has failed. I strongly suggest testing this actually in frigate using real cameras with motion and recognition. The command above is only doing a copy not decoding from what I can see? I did not have much success with rkmpp. mainline kernel is where up to date development is being done and I have had success with mainline kernel 5.14.5 and this fork of ffmpeg https://github.com/jernejsk/FFmpeg/tree/v4l2-request-hwaccel-4.3.2

**Comment by bdherouville** [comment]
> h264_rkmpp codec in ffmpeg is for legacy kernel on rockchip rk3399 and possibly other rockchip devices, with kernel drivers and userland libraries written by rockchip. It only works with the old legacy 4.* bsp linux kernel. When I tested this previously it crashed a lot, and eventually would not restart properly until reboot. The errors in this [reply above](https://github.com/blakeblackshear/frigate/pull/1814#issuecomment-928066251) are what you see if drivers and libraries are missing, or has failed. I strongly suggest testing this actually in frigate using real cameras with motion and recognition. The command above is only doing a copy not decoding from what I can see? I did not have much success with rkmpp. mainline kernel is where up to date development is being done and I have had success with mainline kernel 5.14.5 and this fork of ffmpeg https://github.com/jernejsk/FFmpeg/tree/v4l2-request-hwaccel-4.3.2

Hi !

Do you mean that for a rockchip device we would have a specific ffmpeg container ?
I will work on build such container and I will test.

I did not understood your remark about using real camera stream as I did that test and it failed ( https://github.com/blakeblackshear/frigate/pull/1814#issuecomment-928066251 ) 

Cheers,

**Comment by baldisos** [comment]
Just for Information, with 0.9.0 Beta i'm down to about 12% CPU usage coming from about 40%. And also about 200MB less RAM usage. Seems like this works!

**Comment by bdherouville** [comment]
> Just for Information, with 0.9.0 Beta i'm down to about 12% CPU usage coming from about 40%. And also about 200MB less RAM usage. Seems like this works!

Looks good ! Can you share your HW / Frigate options ?

Regards,

**Comment by baldisos** [comment]
> 
> 
> > Just for Information, with 0.9.0 Beta i'm down to about 12% CPU usage coming from about 40%. And also about 200MB less RAM usage. Seems like this works!
> 
> Looks good ! Can you share your HW / Frigate options ?
> 
> Regards,

the input_args used:

```
        - -avoid_negative_ts
        - make_zero  
        - -fflags  
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
```

**Comment by bdherouville** [comment]
> > > Just for Information, with 0.9.0 Beta i'm down to about 12% CPU usage coming from about 40%. And also about 200MB less RAM usage. Seems like this works!
> > 
> > 
> > Looks good ! Can you share your HW / Frigate options ?
> > Regards,
> 
> the input_args used:
> 
> ```
>         - -avoid_negative_ts
>         - make_zero  
>         - -fflags  
>         - nobuffer
>         - -flags
>         - low_delay
>         - -strict
>         - experimental
>         - -fflags
>         - +genpts+discardcorrupt
>         - -rw_timeout
>         - "5000000"
>         - -use_wallclock_as_timestamps
>         - "1"
> ```

Thanks, and what is your hardware ?

**Comment by baldisos** [comment]
> 
> 
> > > > Just for Information, with 0.9.0 Beta i'm down to about 12% CPU usage coming from about 40%. And also about 200MB less RAM usage. Seems like this works!
> > > 
> > > 
> > > Looks good ! Can you share your HW / Frigate options ?
> > > Regards,
> > 
> > 
> > the input_args used:
> > ```
> >         - -avoid_negative_ts
> >         - make_zero  
> >         - -fflags  
> >         - nobuffer
> >         - -flags
> >         - low_delay
> >         - -strict
> >         - experimental
> >         - -fflags
> >         - +genpts+discardcorrupt
> >         - -rw_timeout
> >         - "5000000"
> >         - -use_wallclock_as_timestamps
> >         - "1"
> > ```
> 
> Thanks, and what is your hardware ?

I'm using HassOS on an ODROID-N2+ which uses the RK3399(?) platform i think.

**Comment by spattinson** [comment]
> > h264_rkmpp codec in ffmpeg is for legacy kernel on rockchip rk3399 and possibly other rockchip devices, with kernel drivers and userland libraries written by rockchip. It only works with the old legacy 4.* bsp linux kernel. When I tested this previously it crashed a lot, and eventually would not restart properly until reboot. The errors in this [reply above](https://github.com/blakeblackshear/frigate/pull/1814#issuecomment-928066251) are what you see if drivers and libraries are missing, or has failed. I strongly suggest testing this actually in frigate using real cameras with motion and recognition. The command above is only doing a copy not decoding from what I can see? I did not have much success with rkmpp. mainline kernel is where up to date development is being done and I have had success with mainline kernel 5.14.5 and this fork of ffmpeg https://github.com/jernejsk/FFmpeg/tree/v4l2-request-hwaccel-4.3.2
> 
> Hi !
> 
> Do you mean that for a rockchip device we would have a specific ffmpeg container ? I will work on build such container and I will test.
> 
> I did not understood your remark about using real camera stream as I did that test and it failed ( [#1814 (comment)](https://github.com/blakeblackshear/frigate/pull/1814#issuecomment-928066251) )
> 
> Cheers,

There are already hardware specific ffmpeg containers in amd64nividia for cuda decoding on nvidia gpu, aarch64 has raspberry pi hardware acceleration, its a separate part of config so easy enough to build a different one need to install the rockchip libraries in the container. Also may need a /dev/<device> for it. What kernel version are you running?

**Comment by bdherouville** [comment]
> > > h264_rkmpp codec in ffmpeg is for legacy kernel on rockchip rk3399 and possibly other rockchip devices, with kernel drivers and userland libraries written by rockchip. It only works with the old legacy 4.* bsp linux kernel. When I tested this previously it crashed a lot, and eventually would not restart properly until reboot. The errors in this [reply above](https://github.com/blakeblackshear/frigate/pull/1814#issuecomment-928066251) are what you see if drivers and libraries are missing, or has failed. I strongly suggest testing this actually in frigate using real cameras with motion and recognition. The command above is only doing a copy not decoding from what I can see? I did not have much success with rkmpp. mainline kernel is where up to date development is being done and I have had success with mainline kernel 5.14.5 and this fork of ffmpeg https://github.com/jernejsk/FFmpeg/tree/v4l2-request-hwaccel-4.3.2
> > 
> > 
> > Hi !
> > Do you mean that for a rockchip device we would have a specific ffmpeg container ? I will work on build such container and I will test.
> > I did not understood your remark about using real camera stream as I did that test and it failed ( [#1814 (comment)](https://github.com/blakeblackshear/frigate/pull/1814#issuecomment-928066251) )
> > Cheers,
> 
> There are already hardware specific ffmpeg containers in amd64nividia for cuda decoding on nvidia gpu, aarch64 has raspberry pi hardware acceleration, its a separate part of config so easy enough to build a different one need to install the rockchip libraries in the container. Also may need a /dev/ for it. What kernel version are you running?

Linux rockpro64 5.10.63-rockchip64 #21.08.2 

I am running armbian

**Comment by bdherouville** [comment]
> > > > > Just for Information, with 0.9.0 Beta i'm down to about 12% CPU usage coming from about 40%. And also about 200MB less RAM usage. Seems like this works!
> > > > 
> > > > 
> > > > Looks good ! Can you share your HW / Frigate options ?
> > > > Regards,
> > > 
> > > 
> > > the input_args used:
> > > ```
> > >         - -avoid_negative_ts
> > >         - make_zero  
> > >         - -fflags  
> > >         - nobuffer
> > >         - -flags
> > >         - low_delay
> > >         - -strict
> > >         - experimental
> > >         - -fflags
> > >         - +genpts+discardcorrupt
> > >         - -rw_timeout
> > >         - "5000000"
> > >         - -use_wallclock_as_timestamps
> > >         - "1"
> > > ```
> > 
> > 
> > Thanks, and what is your hardware ?
> 
> I'm using HassOS on an ODROID-N2+ which uses the RK3399(?) platform i think.

I just tested the 0.9.0 release with the same parameters. With 5 streams of 1920x1080 and one 1920x720 on a RockPro64 I end with a load of 11 wich I guess is a bit too high.

I don't know if we can monitor the vpu load on that board.

**Comment by spattinson** [comment]
I didn't think rkmpp worked on 5.x kernels? do you have /dev/rkmpp device file ?

**Comment by bdherouville** [comment]
> I didn't think rkmpp worked on 5.x kernels? do you have /dev/rkmpp device file ?

No, I don't have this device.

This document is very interesting, expecially the end.

https://www.linkedin.com/pulse/stream-cheaprk3399-ffmpeg-part-i-bruno-verachten/

**Comment by spattinson** [comment]
> > > > > Just for Information, with 0.9.0 Beta i'm down to about 12% CPU usage coming from about 40%. And also about 200MB less RAM usage. Seems like this works!
> > > > 
> > > > 
> > > > Looks good ! Can you share your HW / Frigate options ?
> > > > Regards,
> > > 
> > > 
> > > the input_args used:
> > > ```
> > >         - -avoid_negative_ts
> > >         - make_zero  
> > >         - -fflags  
> > >         - nobuffer
> > >         - -flags
> > >         - low_delay
> > >         - -strict
> > >         - experimental
> > >         - -fflags
> > >         - +genpts+discardcorrupt
> > >         - -rw_timeout
> > >         - "5000000"
> > >         - -use_wallclock_as_timestamps
> > >         - "1"
> > > ```
> > 
> > 
> > Thanks, and what is your hardware ?
> 
> I'm using HassOS on an ODROID-N2+ which uses the RK3399(?) platform i think.

Odroid N2+ uses  Amlogic S922X Processor NOT RK3399

**Comment by bdherouville** [comment]
@blakeblackshear I would like to test frigate with the specific ffmpeg https://github.com/jernejsk/FFmpeg/tree/v4l2-request-hwaccel-4.3.2

Is it possible to create a branch where I will be able to push updates as I would like to test starting Frigate and how it interract with the ffmpeg ?

Regards,

**Comment by blakeblackshear** [comment]
You don't need to test how frigate works with ffmpeg. You should fork the repo and make changes to [this Dockerfile](https://github.com/blakeblackshear/frigate/blob/release-0.9.0/docker/Dockerfile.ffmpeg.aarch64). You can test your changes by running ffmpeg directly in that container after running `make aarch64_ffmpeg`.

**Comment by blakeblackshear** [comment]
I am going to reopen this. I reverted the previous attempt to incorporate the changes into the next release because it was breaking RPi4 support.

**Comment by blakeblackshear** [comment]
@bdherouville note that the following command you posted does not actually use the hwaccel support you added because its just copying the stream directly to the mp4.

Your command:
```shell
docker run -v /dev/dri/renderD128:/dev/dri/renderD128 bdherouville:frigate -hwaccel drm -hwaccel_device /dev/dri/renderD128 -c:v h264_rkmpp -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:pass@nvr/Streaming/Channels/101 -c:v copy -c:a aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an test.mp4
```

Try this instead:
```shell
docker run -v /dev/dri/renderD128:/dev/dri/renderD128 bdherouville:frigate -hwaccel drm -hwaccel_device /dev/dri/renderD128 -c:v h264_rkmpp -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:pass@nvr/Streaming/Channels/101 -f rawvideo -pix_fmt yuv420p pipe: > /dev/null
```

**Comment by spattinson** [comment]
The aarch64 ffmpeg frigate dockerfile installs raspberry pi userspace kernel headers, these wont work for compiling hardware acceleration for other aarch64 platforms which will probably need the correct kernel headers. So another arch would be needed for frigate, like how amd64nvidia is handled today. For my install I just expose the system /usr/include inside the container for the build as armbian doesn't maintain apt packages for those on kernel 5.13.*

**Comment by sakalauskas** [comment]
This change does indeed break Jetson Nano as well as @spattinson explained.
```
 ERROR   : You may have invalid args defined for this camera.
 ERROR   : ffmpeg: error while loading shared libraries: libnvll.so: cannot open shared object file: No such file or directory
```

@spattinson do you use docker-compose? What's the best way to expose /usr/include?

**Comment by spattinson** [comment]
> This change does indeed break Jetson Nano as well as @spattinson explained.
> 
> ```
>  ERROR   : You may have invalid args defined for this camera.
>  ERROR   : ffmpeg: error while loading shared libraries: libnvll.so: cannot open shared object file: No such file or directory
> ```
> 
> @spattinson do you use docker-compose? What's the best way to expose /usr/include?

I am getting kernel source and installing from that, this needs additional packages xz-utils and rsync added to the apt-get install at the top. For Rockchip the VPU acceleration drivers are still in staging in the kernel and are being actively worked on. One of the kodi libreelec devs is maintaining fork of FFmpeg that has private headers that must be in sync with kernel. For Jetson Nano which probably has stable interfaces with GPU there may be a package you can install name linux-headers-<version> that you can simply install in a way similar to how raspberry pi headers are installed but you may need to add the apt source for that. The method I use may not work for jetson, not sure if nvidia cuda installs headers that are required by ffmpeg or not.

```
## linux headers
RUN  \
        DIR=/tmp/linux && mkdir -p ${DIR} && cd ${DIR} && \ 
        curl -sLO  https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.14.9.tar.xz && \ 
        tar -x --strip-components=1 -f linux-5.14.9.tar.xz && \ 
        make -j6 headers_install INSTALL_HDR_PATH=/usr && \ 
        rm -rf ${DIR}
```

**Comment by spattinson** [comment]
failed to find a suitable hardware decoder and did software decode instead.  If there any options you can change on your camera? I am confused by the "required mem2mem" error.  v4l2m2m is the stateful decoding used on raspberry pi etc, and if you used the same ffmpeg configure options I posted ffmpeg should not support m2m? See the same section of the debug output in my reply has no mention of "missing require mem2mem"
```
[h264 @ 0xaaab157f9f50] v4l2_request_probe_media_device: avctx=0xaaab157f9f50 ctx=0xffff88070f50 path=/dev/media0 driver=hantro-vpu
[h264 @ 0xaaab157f9f50] v4l2_request_probe_video_device: avctx=0xaaab157f9f50 ctx=0xffff88070f50 path=/dev/video0 capabilities=69222400
[h264 @ 0xaaab157f9f50] v4l2_request_try_format: pixelformat 875967059 not supported for type 10
[h264 @ 0xaaab157f9f50] v4l2_request_probe_video_device: try output format failed
[h264 @ 0xaaab157f9f50] v4l2_request_probe_media_device: avctx=0xaaab157f9f50 ctx=0xffff88070f50 path=/dev/media1 driver=uvcvideo
[h264 @ 0xaaab157f9f50] v4l2_request_probe_video_device: avctx=0xaaab157f9f50 ctx=0xffff88070f50 path=/dev/video1 capabilities=69206017
[h264 @ 0xaaab157f9f50] v4l2_request_probe_video_device: missing required mem2mem capability
[h264 @ 0xaaab157f9f50] v4l2_request_probe_video_device: avctx=0xaaab157f9f50 ctx=0xffff88070f50 path=/dev/video2 capabilities=77594624
[h264 @ 0xaaab157f9f50] v4l2_request_probe_video_device: missing required mem2mem capability
```
You can try leaving out the "-pix_fmt yuv420p" seems you camera produces yuvj420p, just let it output same pixel format as the input?

**Comment by gusarg81** [comment]
My camera have two input methods (https://www.arducam.com/product/b0205-arducam-1080p-day-night-vision-usb-camera-module-for-computer-2mp-automatic-ir-cut-switching-all-day-image-usb2-0-webcam-board-with-ir-leds/):

- YUYV
- MJPEG

My intention if to use the second, since the first only provides 5FPS (at 1920x1080) and the second 30FPS (at 1920x1080). Is why I use -input_format mjpeg -pixel_format mjpeg with this camera module:

> v4l2-ctl --device /dev/video1 --list-formats
> ioctl: VIDIOC_ENUM_FMT
>         Type: Video Capture
> 
>         [0]: 'MJPG' (Motion-JPEG, compressed)
>         [1]: 'YUYV' (YUYV 4:2:2)

About FFmpeg: used the options you told me, gave me the error I posted before (I will try again right now). I used the common configure options that use the FFmpeg from Ubuntu, added plus the ones you posted.

**Comment by gusarg81** [comment]
Compiled again FFmpeg with the configure options you gave me and the result is the same (also removed -pix_fmt yuv420p):

> [h264 @ 0xaaaac9b9b8c0] nal_unit_type: 7(SPS), nal_ref_idc: 3
> [h264 @ 0xaaaac9b9b8c0] nal_unit_type: 8(PPS), nal_ref_idc: 3
> [h264 @ 0xaaaac9b9b8c0] nal_unit_type: 5(IDR), nal_ref_idc: 3
> [h264 @ 0xaaaac9b9b8c0] Format drm_prime chosen by get_format().
> [h264 @ 0xaaaac9b9b8c0] Format drm_prime requires hwaccel initialisation.
> [h264 @ 0xaaaac9b9b8c0] ff_v4l2_request_init: avctx=0xaaaac9b9b8c0 hw_device_ctx=0xaaaac9b579d0 hw_frames_ctx=(nil)
> [h264 @ 0xaaaac9b9b8c0] v4l2_request_probe_media_device: avctx=0xaaaac9b9b8c0 ctx=0xffff840ac930 path=/dev/media0 driver=hantro-vpu
> [h264 @ 0xaaaac9b9b8c0] v4l2_request_probe_video_device: avctx=0xaaaac9b9b8c0 ctx=0xffff840ac930 path=/dev/video0 capabilities=69222400
> [h264 @ 0xaaaac9b9b8c0] v4l2_request_try_format: pixelformat 875967059 not supported for type 10
> [h264 @ 0xaaaac9b9b8c0] v4l2_request_probe_video_device: try output format failed
> [h264 @ 0xaaaac9b9b8c0] v4l2_request_probe_media_device: avctx=0xaaaac9b9b8c0 ctx=0xffff840ac930 path=/dev/media1 driver=uvcvideo
> [h264 @ 0xaaaac9b9b8c0] v4l2_request_probe_video_device: avctx=0xaaaac9b9b8c0 ctx=0xffff840ac930 path=/dev/video1 capabilities=69206017
> [h264 @ 0xaaaac9b9b8c0] v4l2_request_probe_video_device: missing required mem2mem capability
> [h264 @ 0xaaaac9b9b8c0] v4l2_request_probe_video_device: avctx=0xaaaac9b9b8c0 ctx=0xffff840ac930 path=/dev/video2 capabilities=77594624
> [h264 @ 0xaaaac9b9b8c0] v4l2_request_probe_video_device: missing required mem2mem capability
> [h264 @ 0xaaaac9b9b8c0] Failed setup for format drm_prime: hwaccel initialisation returned error.
> [h264 @ 0xaaaac9b9b8c0] Format drm_prime not usable, retrying get_format() without it.
> [h264 @ 0xaaaac9b9b8c0] Format yuv420p chosen by get_format().
> [h264 @ 0xaaaac9b9b8c0] Reinit context to 2560x1440, pix_fmt: yuv420p
> cur_dts is invalid st:0 (0) [init:0 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
> [h264 @ 0xaaaac9b94980] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
> cur_dts is invalid st:0 (0) [init:0 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
> [h264 @ 0xaaaac9db5b90] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
> cur_dts is invalid st:0 (0) [init:0 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
> [h264 @ 0xaaaac9c8f9a0] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
> [h264 @ 0xaaaac9cab460] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3

**Comment by cstrat** [comment]
Found my way to this closed pull request looking for a way to enabled hardware acc on my rock5b for ffmpeg...
Has anyone got an answer for this?

**Pull request closed without merging**
