### PR TITLE
Added more unit tests for the review controller

### PR DESCRIPTION
**Pull request by iursevla**
## Proposed change

Add more unit tests for the review controller endpoints

* /review/summary
* /reviews/viewed
* /reviews/delete

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code
- [ ] Documentation Update

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Ruff (`ruff format frigate`)

### CODE REVIEW

**Comment by NickM-27** [comment]
Can you sync with latest

**Comment by iursevla** [comment]
https://github.com/blakeblackshear/frigate/pull/15162#issuecomment-2507781818

@NickM-27 Done

The missing endpoints for the review controller will come shortly afterward 🙏

**Comment by iursevla** [comment]
@NickM-27 is there something missing? 

> Merging is blocked
> This branch must not contain merge commits.

Is there something I need to do, or is everything okay?

I did merge upstream/dev into my branch

**Review by NickM-27 — APPROVED** [review]

**Comment by NickM-27** [comment]
I thought we already merged this

**Review by hawkeye217 — APPROVED** [review]

**Pull request merged**
