### PR TITLE
0.13.0 Release

### PR DESCRIPTION
**Pull request by blakeblackshear**
Docs: https://deploy-preview-6262--frigate-docs.netlify.app/

- [x] Export recordings to export directory next to (or in) recordings folder via API and WebUI
- [x] Prevent recordings from being turned on if disabled in config
- [x] Plus integration 
  - [x] False positive submissions
  - [x] Custom model downloads
- [x] Community supported boards framework
- [x] Timeline data
  - [x] Events framework revamp
  - [x] Generic events model
  - [x] Add custom event support
- [x] Add audio event support
- [x] Move recordings management to separate process
- [ ] False positive reduction
  - [ ] Tracking improvements 
    - [x] Implement a smarter algorithm
    - [ ] Occlusion handling
  - [x] Smarter region sizes based on historical detections
  - [x] Better handling of objects moving into motion masked areas
  - [ ] Better handling of labels that are frequently confused (cat/dog)
  - [ ] Use historical object sizes to determine if an object is too large/small to be a true positive
  - [x] Minimum number of frames for zone presence
- [ ] Improve motion detection
  - [ ] Make dynamic to handle night mode automatically
  - [x] Automatically handle lightning
  - [ ] Detect and handle rain
  - [x] PTZ moves
- [x] Object attributes (face on person, license plate on car, for example)
- [x] remove old legacy recordings cleanup method 

Cleanup:
- [x] Make attribute scores visible
- [x] Retain video when there is detected audio
- [x] Remove proper case in UI for hover text

Bugs:
- [x] Save button not working in mask editor
- [x] Fix "Unable to create jpg because frame 1688851244.054868 is not in the cache" errors
- [x] Recordings management still dropping segments for some users. Unsure why.

Nice to haves:
- [x] View exports in UI

### CODE REVIEW

**Review by kdill00 — COMMENTED** [review]
This seems to be a significant improvement on retaining lock on objects when they are close together and also looks to have the added side affect of decreasing my detector fps usage due to not having to relook for the target as often with large crowds of people. Will be seeing how it does with massive crowds tomorrow.  Looks markedly better though. Thanks for all your hard work

**Comment by Melkor82** [comment]
Is there a way to differentiate between tags or create custom ones? I have 4 cats (each one of a different color) I would like to have them recognized differently.

**Comment by NickM-27** [comment]
> Is there a way to differentiate between tags or create custom ones? I have 4 cats (each one of a different color) I would like to have them recognized differently. 

That would be an external feature, something like doubletake or birdcage

**Comment by bagobones** [comment]
I wonder if rain / snow / small bug swarms are all essentially the same problem at least in IR mode where they all look like bright shiny streaks instead of solid moving masses.

**Comment by DrSpaldo** [comment]
I am not sure if I have missed a setting in updating to 7c629c1, however, I don't appear to be getting stationary objects for cars anymore. I keep getting the same car being detected in the same spot over & over. The event lasts about 25 seconds

**Comment by NickM-27** [comment]
> I am not sure if I have missed a setting in updating to 7c629c1, however, I don't appear to be getting stationary objects for cars anymore. I keep getting the same car being detected in the same spot over & over. The event lasts about 25 seconds

The only thing that changed is that stationary objects are now verified by default every 10 seconds and there is no way to disable that (though the value is still configurable)

**Comment by NickM-27** [comment]
nothing would have changed with that, and it's working as expected for me

**Comment by DrSpaldo** [comment]
Are the audio events supposed to come up in Home Assistant as an event / sensor?

**Comment by NickM-27** [comment]
> Are the audio events supposed to come up in Home Assistant as an event / sensor? 

Yes, but you need the updated integration which isn't available in HACS yet

**Comment by DrSpaldo** [comment]
> > Are the audio events supposed to come up in Home Assistant as an event / sensor?
> 
> Yes, but you need the updated integration which isn't available in HACS yet

You're going to make me work for it!  Alright.,... 

I am guessing this is the PR for this issue in the integration; https://github.com/blakeblackshear/frigate-hass-integration/pull/516 

With 8f26352 being the build? https://github.com/blakeblackshear/frigate-hass-integration/commit/8f26352e76f173db288b745ad746452bbe583cc4

So, how do I make HA load that build instead?

**Comment by DrSpaldo** [comment]
> With 8f26352 being the build? [blakeblackshear/frigate-hass-integration@8f26352](https://github.com/blakeblackshear/frigate-hass-integration/commit/8f26352e76f173db288b745ad746452bbe583cc4)
> 
> So, how do I make HA load that build instead?

I downloaded the 8f26352 build and copied across the integration files into my folder and it is working now

**Comment by DrSpaldo** [comment]
Can any consideration be given to being able to configure the audio sensitivity based on the time? Ie. I want it less sensitive to speech during the day when people are around, but more sensitive at nighttime when criminals may be speaking with each other quiet and speech is not expected

**Comment by NickM-27** [comment]
> Can any consideration be given to being able to configure the audio sensitivity based on the time? Ie. I want it less sensitive to speech during the day when people are around, but more sensitive at nighttime when criminals may be speaking with each other more quietly and speech is not expected at that time..

what do you mean by audio sensitivity?

**Comment by NickM-27** [comment]
> I guess the min volume setting and the thread hold setting?

I am trying to think through this based on my usage of this over the last month.

I don't think changing the threshold makes sense, the score of "speech" for example doesn't change whether the speech is happening at day or night, and regardless you'll just be opening up to more false positives by lowering the threshold at night.

min volume is similar, in my experience with some tuning I've been able to get my config where it really only creates an event for speech that happens on our property, unless someone is yelling on the sidewalk which is something you'd want to record / detect anyway. A person speaking the same volume will be "louder" to the camera the closer that person is to the camera. 

It very well might make sense in the future, but I think for the initial implementation of this feature it makes sense to hold off until we can make sure that the audio features without this variability is working as expected for more users.

**Comment by DrSpaldo** [comment]
> > I guess the min volume setting and the thread hold setting?
> 
> I am trying to think through this based on my usage of this over the last month.
> 
> I don't think changing the threshold makes sense, the score of "speech" for example doesn't change whether the speech is happening at day or night, and regardless you'll just be opening up to more false positives by lowering the threshold at night.
> 
> min volume is similar, in my experience with some tuning I've been able to get my config where it really only creates an event for speech that happens on our property, unless someone is yelling on the sidewalk which is something you'd want to record / detect anyway. A person speaking the same volume will be "louder" to the camera the closer that person is to the camera.
> 
> It very well might make sense in the future, but I think for the initial implementation of this feature it makes sense to hold off until we can make sure that the audio features without this variability is working as expected for more users.

Alright, just a thought… what did you end up using for your settings?

**Comment by NickM-27** [comment]
For my camera on the front I ended up with min_volume of 750, obviously it is going to depend on the camera. Also most high quality cameras include options in the camera settings for mic volume which would naturally affect that setting as well

**Comment by towerhand** [comment]
Great work. I have been running it for a couple of weeks, and it has been solid. From the new features, I really like the option to create and export custom events and time-lapses from the UI. Way to go!!!

**Comment by ljmerza** [comment]
> 5658e5a

which docker container are you running? last time i tried this i had too amny issues and had to go back

**Comment by towerhand** [comment]
I'm currently running 3c25c57.

**Comment by NickM-27** [comment]
> just tried the latest and all my previous events broke

you should make an issue then, there are no known issues with previous events

**Comment by niemyjski** [comment]
Is there any projected date for this release?

**Review by NickM-27 — APPROVED** [review]

**Pull request merged**
