### PR TITLE
Convert config to Pydantic

### PR DESCRIPTION
**Pull request by hunterjm**
This converts the config to use [Pydantic](https://pydantic-docs.helpmanual.io/). The benefit here is validation inside the same models you use for configuration. I have also removed all side effects from the configuration settings. Calling `config.dict(exclude_unset=True)` will return the configuration dictionary exactly as it was parsed. This will enable editing from the frontend in the future.

All side-effects have thus been moved to `config.runtime_config` which returns a new config object that is used by the application runtime.

### CODE REVIEW

**Comment by hunterjm** [comment]
This PR should also supersede #854. Pydantic has built in support for exporting models as JSON Schema, and I have added a new endpoint to retrieve the schema at `/api/config/schema`.

**Comment by ElMoribond** [comment]
If i have this
```
ffmpeg:
  global_args: -hide_banner -loglevel info
```

I get this error
```
Error parsing config: 1 validation error for CameraConfig
ffmpeg -> global_args
  value is not a valid list (type=type_error.list)
```

Everything is ok with
```
ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - info
```

**Comment by hunterjm** [comment]
> @hunterjm
> If i have this
> 
> ```
> ffmpeg:
>   global_args: -hide_banner -loglevel info
> ```
> 
> I get this error
> 
> ```
> Error parsing config: 1 validation error for CameraConfig
> ffmpeg -> global_args
>   value is not a valid list (type=type_error.list)
> ```
> 
> Everything is ok with
> 
> ```
> ffmpeg:
>   global_args:
>     - -hide_banner
>     - -loglevel
>     - info
> ```

Hey, thanks! I can open a new PR to fix this, but would you open this as an issue so it's easier to track?

**Comment by herostrat** [comment]
Awesome, thanks for this

On first glance it seems that some validations/enums were not converted. Was this on purpose or is it ok if I send in fixes?

**Comment by hunterjm** [comment]
> Awesome, thanks for this
> 
> On first glance it seems that some validations/enums were not converted. Was this on purpose or is it ok if I send in fixes?

By all means please do. I should have opened this as a Draft PR initially. I've only done very light testing on it, and wanted to write more tests for the config for scenarios I saw were not covered by existing tests.

I won't be able to touch this until ~10 hours from now, so if you can get fixes in before that we can make sure we don't duplicate efforts.

**Pull request merged**
