### PR TITLE
Return sub_labels in event summary information

### LINKED ISSUE #5639: Should `sub_labels` be included in `api/events/summary` ?
I'm trying to implement `sub_label` support in the card (https://github.com/dermotduffy/frigate-hass-card/issues/900). To do this, I need to fetch the available sub_labels. 

I had assumed they would show up in the event summary information, but they don't. So there are two paths:

* Add `sub_labels` to `api/events/summary` information (this has the advantage that the integration media browser could do drilldowns by sub_label).

* Proxy the `api/sub_labels` call from card -> integration -> Frigate.

Personally, I think the first option is the better one, but there may be a good reason why it's not included in the event summary info?

### PR DESCRIPTION
**Pull request by dermotduffy**
* Closes #5639 

(Well that was easy)

### CODE REVIEW

**Comment by NickM-27** [comment]
Just want to make sure you're aware, there are cases where a sub_label can be a comma separated list of multiple names (for example if two people walk up to the camera at the same time). So the card may want to split that list up depending on how the search is being done.

**Review by NickM-27 — APPROVED** [review]

**Comment by dermotduffy** [comment]
> Just want to make sure you're aware, there are cases where a sub_label can be a comma separated list of multiple names (for example if two people walk up to the camera at the same time). So the card may want to split that list up depending on how the search is being done.

Did not know that -- thanks, will split on the card.

**Comment by dermotduffy** [comment]
Actually -- that's kind of a problem. If the sub label is `foo,bar`, and the card wants to search for `bar`, there's not a great way to do that except separately getting the list of all sub_labels and reverse matching the "unsplit" labels.

Is there a reason sub_label isn't just a list, like zones?

**Comment by NickM-27** [comment]
> Actually -- that's kind of a problem. If the sub label is `foo,bar`, and the card wants to search for `bar`, there's not a great way to do that except separately getting the list of all sub_labels and reverse matching the "unsplit" labels.

You can see how I handled this here: https://github.com/blakeblackshear/frigate/pull/5602

Ended up not being too bad

> Is there a reason sub_label isn't just a list, like zones?

It was just a string, wasn't until other projects started adding support for the feature directly (like doubletake) that it would be a concern. 

Anyway, let me know if a solution like my PR isn't possible.

**Pull request merged**
