### PR TITLE
Add other known birdseye aspect ratios

### LINKED ISSUE #8317: [Support]: Birdseye canvas does not support 2:1 aspect ratio
### Describe the problem you are having

image

Self explanatory... I understand the black space where the red X is drawn, but the huge black space enclosed within the yellow rectangle is just dumb. I use wall mounted tablets around the house to display the birdseye view as a "screensaver" that goes away when I touch the tablet screen, so that I can have a quick glance at my home's perimeter when I'm not using the tablet.

And that empty space means I get smaller camera views because most of the space is wasted with the black empty space.

### Version

0.13.0-9A4F970

### Frigate config file

```yaml
birdseye:
  enabled: true
  restream: true
  width: 2592
  height: 1944
    # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  mode: continuous
```
```


### Relevant log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Frigate stats

_No response_

### Operating system

Debian

### Install method

Docker CLI

### Coral version

Other

### Network connection

Wired

### Camera make and model

Not relevant but resolution is 2592x1944

### Any other information that may be helpful

_No response_

### PR DESCRIPTION
**Pull request by NickM-27**
Closes https://github.com/blakeblackshear/frigate/issues/8317

### CODE REVIEW

**Review by blakeblackshear — APPROVED** [review]

**Comment by Majestic7979** [comment]
https://github.com/blakeblackshear/frigate/assets/128995501/9790408f-ddd5-48f0-97ad-d7e58d6c1b33

LOL?!?!?!? 2:1 Resolution of 2000x1000 and also 2048x1024... Looks like Frigate ingested some LSD!!!!!!!

**Comment by NickM-27** [comment]
I don't think this has anything to do with my change, it is working as expected. Sometimes reading the pipe gets out of sync so the color data is incorrect. Stopping the stream and waiting 30 seconds for it to reset the pipe should fix it

**Comment by Majestic7979** [comment]
Never happened before... not to say I'm here fighting about it. When you say stop the stream, do you mean reboot the cameras? Or restart the Frigate container?

**Comment by NickM-27** [comment]
> When you say stop the stream, do you mean reboot the cameras? Or restart the Frigate container?

just stop watching the stream everywhere so go2rtc stops reading from the pipe, or restarting frigate is fine if that is easier

**Comment by Majestic7979** [comment]
I power cycled all of my cameras. I first restarted the Frigate container. Then I rebooted my server. Same thing, still doing it.

**Comment by Majestic7979** [comment]
I don't know if this helps you in any way but this is a list of standard aspect rations (and resolutions): https://www.hernansantander.com/blog-1/2017/8/17/resolution-aspect-ratio-cheat-sheet

**Comment by NickM-27** [comment]
I've identified an issue with 4:3 cameras and how the layout is scaled after it is calculated, not sure that it would be affecting this pixelation issue as I've not been able to reproduce it, but perhaps it will help

**Comment by Majestic7979** [comment]
Like the cereal tiger (or is it a cheetah? a panther?): Grrrrrrreat. When you submit the PR can you please tell me, so I can download and test. Thanks.

**Comment by NickM-27** [comment]
the PR is https://github.com/blakeblackshear/frigate/pull/8343

**Comment by Majestic7979** [comment]
I know how to enter the container environment and use bash. Any way I can test this by manually modifying a file in the container before it's merged?

**Comment by NickM-27** [comment]
no, you would need to build the container yourself or wait for it to be merged and use the auto build

**Comment by Majestic7979** [comment]
I'll wait. I tried to edit the output.py in the container and I'm getting this when I restart the container:

```
2023-10-26 22:00:48.627783870  Traceback (most recent call last):
2023-10-26 22:00:48.627790942    File "/opt/frigate/frigate/output.py", line 621, in update
2023-10-26 22:00:48.627793989      updated_frame = self.update_frame()
2023-10-26 22:00:48.627796901    File "/opt/frigate/frigate/output.py", line 436, in update_frame
2023-10-26 22:00:48.627799838      layout_candidate = self.calculate_layout(
2023-10-26 22:00:48.627802952    File "/opt/frigate/frigate/output.py", line 566, in calculate_layout
2023-10-26 22:00:48.627806064      total_width, total_height, standard_candidate_layout = map_layout(row_height)
2023-10-26 22:00:48.627808969    File "/opt/frigate/frigate/output.py", line 475, in map_layout
2023-10-26 22:00:48.627811669      max_width = max(max_width, x)
2023-10-26 22:00:48.627814696  UnboundLocalError: local variable 'max' referenced before assignment
```

**Comment by Majestic7979** [comment]
I wish I understood programming but I have some learning difficulties that makes it really challenging to study anything with calculations. Sometimes I can figure it out but it's not easy. Thanks for always helping.

**Comment by Majestic7979** [comment]
Thank you, the PR has fixed the issue and it now fills the whole tablet's screen, it's awesome! You are a great guy!!

**Comment by NickM-27** [comment]
Glad to hear it, thanks for confirming

**Pull request merged**
