### PR TITLE
Update of the home assistant integration example

### PR DESCRIPTION
**Pull request by tubalainen**
sensor to binary_sensor
device_class type "moving" does not exist, update to "motion"

### CODE REVIEW

**Comment by jon102034050** [comment]
https://www.home-assistant.io/components/binary_sensor/

this shows that `moving` does exist:
`moving: On means moving, Off means not moving (stopped)`

**Comment by tubalainen** [comment]
> https://www.home-assistant.io/components/binary_sensor/
> 
> this shows that `moving` does exist:
> `moving: On means moving, Off means not moving (stopped)`

Mr Jon,

That is correct, as a `binary_sensor` the `moving` device_class exists but it does not as a `sensor` device_class. So if using the example code it will still fails. An update of the example would be recommended. Lets see what way our dear maintainer would like to go. I personally like the "running man" better.

**Comment by jon102034050** [comment]
Sorry, I was just pulling the documentation based off of your PR, which stated that you wanted to switch the example to a binary sensor and was simply stating a fact that the class does exist under this. Doesn't really matter to me I guess :)

**Comment by blakeblackshear** [comment]
Thanks

**Pull request merged**
