### PR TITLE
refactor(web): Adhere to Material Design guidelines

### LINKED ISSUE #646: web: allow dark mode via user preference
Would like to make dark mode both auto-chosen via the media query AND by user preference. Will require a backing store with IndexedDB if manually set.

### LINKED ISSUE #651: ☂️ web: style guide and more reusable components
Current UI is arbitrary and basic just pulled from a couple things that tailwindcss offers quickly. A more coherent style and reusable components would help bring everything together better.

If anyone wants to play with the branch, it's available at https://github.com/paularmstrong/frigate/tree/styleguide

## TODO:

- [x] AppBar
- [x] NavigationBar
- [x] TextField
- [x] Select
- [x] Switch
- [x] Logo
- [x] Card
- [x] Button
- [x] Menu
- [x] Dialog
- [x] Camera view

### PR DESCRIPTION
**Pull request by paularmstrong**
Standardized UI and following materialdesign.io will help with future enhancements, like config editing, etc. 

* Dark mode and live view settings are saved in local storage (indexeddb)
* Fully responsive UI

https://user-images.githubusercontent.com/33297/106974722-0b309800-670a-11eb-91ff-e12d1aa9358e.mp4

Screen Shot 2021-02-04 at 4 59 24 PM
Screen Shot 2021-02-04 at 4 59 21 PM
Screen Shot 2021-02-04 at 4 59 08 PM
Screen Shot 2021-02-04 at 4 59 05 PM

Fixes blakeblackshear/frigate#651, blakeblackshear/frigate#646

### CODE REVIEW

**Comment by drinfernoo** [comment]
Just out of curiosity, how tough would it be to allow for CSS styling here? It would be pretty slick to match the Frigate UI to your Lovelace UI, for example 😁

**Comment by paularmstrong** [comment]
> Just out of curiosity, how tough would it be to allow for CSS styling here? It would be pretty slick to match the Frigate UI to your Lovelace UI, for example 😁

It would not be worth the effort

**Comment by drinfernoo** [comment]
No worries, just a curiosity. I really do love MD 😅

**Comment by paularmstrong** [comment]
@blakeblackshear this is a big one, but I've been testing it for a number of days and it's feeling really polished. I can squash the commits if you prefer as well.

**Comment by blakeblackshear** [comment]
Not sure what is causing this, but the menu for switching themes is not showing up on Chrome.
image


Cleared cache, and I don't see anything in the console or network tab.

**Comment by paularmstrong** [comment]
That's odd. What version are you running? You also shouldn't have a horizontal scrollbar showing at the bottom.

I'm on `Version 88.0.4324.150 (Official Build) (x86_64)`

**Comment by paularmstrong** [comment]
I just rebuilt the 0.8.2 branch and looks good on my end.

Screen Shot 2021-02-07 at 1 49 12 PM

**Comment by blakeblackshear** [comment]
Im on linux, so I don't get the pretty scroll bars. My Chrome version is `Version 87.0.4280.88 (Official Build) (64-bit)`, but i doubt that's the issue. I test by running `make amd64_frigate` and running the container. I never build the frontend any other way.

**Comment by paularmstrong** [comment]
Ah looks like a weird Chromium/Linux-specific thing. I can repro on my Chromebook. Will get a fix soon.

**Comment by KillahB33** [comment]
Any updates on this? Would love to have that dark mode enabled.

**Pull request merged**
