### PR TITLE
FEAT: Notifications In Frigate Frontend

### PR DESCRIPTION
**Pull request by NickM-27**
## Idea

Per https://github.com/blakeblackshear/frigate/issues/3185#issuecomment-1133664403 
It is a good idea for frigate to be able to post certain notifications. 

## Supported Notification Types (curently)

- recording storage < 10%
- Frigate update is available (current stats and latest GitHub release version comparison)
- camera_fps of cameras and if it is 0.0 assumes there is an ffmpeg error. (This may not be good logic, not 100% sure.)

If anyone has any ideas or thoughts please let me know 👍

### CODE REVIEW

**Comment by NickM-27** [comment]
Here are some screenshots showing the current UI:

Screen Shot 2022-05-22 at 10 19 31 AM

Screen Shot 2022-05-22 at 10 19 38 AM

Note that the icon will only show when there ARE notifications returned by the API, otherwise it will not show at all. The yellow color is intended to convey that there are warnings but if this isn't a good choice then happy to change this.

**Comment by Raphael909** [comment]
This is fantastic! Wondering if such information can be sent over via MQTT. HASS can listen to this and send a apple or android notification!. Thoughts?

**Comment by NickM-27** [comment]
This is what the UI looks like after latest changes:

Screen Shot 2022-05-23 at 8 18 44 AM

**Comment by coldkevin** [comment]
Considering I just filled up a disk where my recordings live on my server and basically crashed it for a few hours.... id love notifications via the gui! I rarely check in on my server ( sigh.... ) but I check frigate daily for new events.

**Comment by DrSpaldo** [comment]
Good idea :)

**Comment by NickM-27** [comment]
Here's a screenshot example for frigate update

Screen Shot 2022-05-31 at 16 02 47 PM

Currently it doesn't support clicking / url. I think the Frigate update could point to the releases page, but not sure where the other ones would link to so maybe better to leave that out for now?

**Comment by NickM-27** [comment]
I think this is ready for initial review / comments
Also to be clear, I have no preference on if it goes into `0.11` or stays until `0.12` 👍

**Comment by DrSpaldo** [comment]
> 

Having the update check / info is great. The link could probably be somewhat dynamic; either go to the releases page or wherever depending on what level of release you are at or stage of development Frigate is at

**Comment by NickM-27** [comment]
Right, that one is easy, but the dead camera, low storage, etc. notifications have no link that would work for all install types

**Comment by NickM-27** [comment]
Went ahead and added some tests for the notifications endpoint to make sure the values are what they should be. Could be expanded in another PR to test more endpoints.

**Comment by NickM-27** [comment]
Going to go ahead and close this, I think there will be a much better way to do this after the recent changes coming in 0.12

**Comment by NickM-27** [comment]
> > Going to go ahead and close this, I think there will be a much better way to do this after the recent changes coming in 0.12
> 
> Any hints on the coming changes?

No need for hints you can read about it here https://github.com/blakeblackshear/frigate/pull/4055

**Pull request closed without merging**
