### PR TITLE
FEAT: Filter Multi Select

### LINKED ISSUE #1941: Event filter drop-down select multiple
### Discussed in https://github.com/blakeblackshear/frigate/discussions/1930

<div type='discussions-op-text'>

<sup>Originally posted by **redbeardmcg** October  6, 2021</sup>
It would be handy to have the ability to select multiple items in the filter inputs for events. I have a camera that generates pretty constant events, so when I visit events it is pages of "bird bird bird bird" as my wife likes to see what her chickens were up to during the day. All other categories are interesting to me, but it's pages of scrolling to get to it unless I select a different label, but then I have to look at labels one at a time. 

The ability to select all and then deselect one or more labels -- or simply select multiple labels individually -- would be a nice to have!</div>

### LINKED ISSUE #2608: Feature Request - Filter Out Particular Cams in Events View
**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to filter out just one camera in event view.  I have a handful of cameras, and one gets a lot more noise (that I want to keep) but would like to be able to look at all "person" events that happened for my other 7 cameras while leaving 1 out of the filter.

**Describe the solution you'd like**
Be able to filter one camera out of the events list instead of only be able to filter to one camera at a time.

**Describe alternatives you've considered**
Just using it the way it is today...

**Additional context**
Nope.  Love the project.  It's amazing!

### PR DESCRIPTION
**Pull request by NickM-27**
Implementation of https://github.com/blakeblackshear/frigate/issues/1941 & https://github.com/blakeblackshear/frigate/issues/2608

WIP ToDo:

- [x] Update internal buttons to use `labels` instead of `label`
- [x] Use cameras, sub_labels, zones correctly
- [x] General Clean up
- [x] Fix sizing of dropdown
- [x] Format items to remove `_`
- [x] Update HTTP docs
- [x] Set min width on filter headers for better mobile view
- [x] Handle `,` in filter names (like sub labels with multiple people)

### Demo

https://user-images.githubusercontent.com/14866235/175099824-ab423bb9-131c-46be-a2a8-df8a03720971.mov

### CODE REVIEW

**Comment by johnmarksilly** [comment]
Looks nice 🗡️

**Review by blakeblackshear — APPROVED** [review]

**Comment by DrSpaldo** [comment]
I’m not sure if this is the related PR for what I’m suggesting, I hope it is.. would be be possible for the select all button to also have the opposite effect when everything is selected? And de select all. It is tedious when I have 10 cameras to only select one as you have to go and individually select the other 9. Would be better to deselect all, then just select 1. Hopefully that makes sense

**Comment by NickM-27** [comment]
> I’m not sure if this is the related PR for what I’m suggesting, I hope it is.. would be be possible for the select all button to also have the opposite effect when everything is selected? And de select all. It is tedious when I have 10 cameras to only select one as you have to go and individually select the other 9. Would be better to deselect all, then just select 1. Hopefully that makes sense

the camera button to the right of the name is there to select that single one only

**Comment by DrSpaldo** [comment]
>  
> the camera button to the right of the name is there to select that single one only

Haha, I'm an idiot... Perfect, thanks @NickM-27

**Pull request merged**
