### PR TITLE
Ability to set different codec for restream and use go2rtc hardware

### PR DESCRIPTION
**Pull request by NickM-27**

### CODE REVIEW

**Review by blakeblackshear — APPROVED** [review]

**Comment by banthungprong** [comment]
Thanks!
But I think the problem starts "earlier".
I reduced my setup to only one mjpeg camera and checked the last version of the docker images that worked:
`image: ghcr.io/blakeblackshear/frigate:dev-3f05f74`

With the version 4 days ago I get only a green screen (no errors in the logs).
`image: ghcr.io/blakeblackshear/frigate:dev-59b52f3`

Is it possible that the switch to hw presets changed something that doesn't work for mjpeg streams?

```
cameras:
  mjpeg:
    enabled: True
    ffmpeg:
      inputs:
        - path: http://10.0.0.142/mjpeg/1
          roles:
            - detect
            - record
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjp>
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
    detect:
      width: 800
      height: 600
      fps: 10
    record:
      enabled: True
```

**Comment by NickM-27** [comment]
It wouldn't make sense to have no error logs though, also I don't see what hwaccel you're using, it's possible that the -vf filter doesn't work for mjpeg but I'd need to see more of the config to understand the issue

**Comment by banthungprong** [comment]
No errors in the logs would be ok if a "green" video isn't an error.

```
ffmpeg:
  global_args: -hide_banner -loglevel error
  hwaccel_args: preset-intel-vaapi
  input_args: preset-rtsp-generic
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic
```

**Comment by NickM-27** [comment]
For mjpeg cameras I'd suggest setting the hwaccel args manually and see if that works. Otherwise you can just use the restream from this PR to transcode the mjpeg stream to h264 and then use that as the source for detect and record

**Comment by banthungprong** [comment]
I did this before (you told me in another thread to use presets...). Same, same.
And I tried restreaming and transcoding h264 and using the rtsp-Url for detect and record. Didn't work.

**Comment by NickM-27** [comment]
> I did this before (you told me in another thread to use presets...). Same, same. And I tried restreaming and transcoding h264 and using the rtsp-Url for detect and record. Didn't work.

are you using the latest dev image? I'll have to see if I can put together an mjpeg stream to test, too much information to ask for to figure out what the problem is

**Comment by banthungprong** [comment]
Yes. Latest dev image. But not problem, mjpeg isn't so important (using an esp32cam with a printed case as door spy).
So please do not invest too much time - low prio.
With my h265-cams everything is working without any problems - that's relevant. I will move the frigate HW to Thailand in the summer: until now I have 5 cams in Thailand and the frigate NVR in Germany. Even with this strange configuration frigate is working flawless!

**Pull request merged**
