### PR TITLE
mqtt over websockets

### PR DESCRIPTION
**Pull request by blakeblackshear**
@paularmstrong implemented mqtt via websockets here. need to add a little error handling and debug logging before merging.

### CODE REVIEW

**Comment by blakeblackshear** [comment]
This does open up your mqtt server entirely via frigate's frontend, so we probably need to enforce a restriction to a topic prefix

**Comment by paularmstrong** [comment]
My assumption was going to be that it would be limited to the frigate installation's topic (eg, `mqtt_config.topic_prefix`), both sending and receiving. Possibly strip it from publishing the topic prefix to the WS and not needing it prepended when publishing messages back through the WS from the frontend

**Comment by blakeblackshear** [comment]
That's my plan.

**Comment by blakeblackshear** [comment]
gevent isnt precompiled for armv7, so I need to update the prebuilt wheels again.

**Comment by paularmstrong** [comment]
Trying to test this out, using local docker connected to another machine's MQTT. For some reason my local Frigate instance continually outputs "MQTT connected" in logs and doesn't see any updates to the MQTT switches. Can you point me where to debug what's going on?

**Comment by blakeblackshear** [comment]
That sounds like the thing some people experience when they aren't using a username and password for mqtt. I have never been able to reproduce it.

**Comment by paularmstrong** [comment]
I'm using username and password. 

It works fine on my production system with the same config, though that's both running in home assistant OS using addons for both mqtt and frigate.

In theory, this should work and update the debug stats via mqtt (though I built it on top of my open PR for unit tests) https://github.com/blakeblackshear/frigate/compare/db_retain...paularmstrong:websockets?expand=1 (latest commit is the important bit)

**Comment by blakeblackshear** [comment]
Maybe I am misunderstanding, but you need to use unique client ids if you have multiple instances connected to the same mqtt server.

**Comment by paularmstrong** [comment]
Ah, that's the issue. I wasn't aware of the `client_id` option. I've got a connection working and I'll post it up for use in a bit.

**Pull request merged**
