### PR TITLE
Add instructions for custom go2rtc build

### PR DESCRIPTION
**Pull request by NickM-27**

### CODE REVIEW

**Review by blakeblackshear — APPROVED** [review]

**Comment by cybertza** [comment]
[INFO] Starting go2rtc...
2023-09-20 17:04:30.314193025  ./run.user: line 72: /usr/local/go2rtc/bin/go2rtc: Permission denied
2023-09-20 17:04:30.317611032  [INFO] The go2rtc service exited with code 126 (by signal 0)


Dont think this works in 13b any more, (not that i tested it before)

but had to change that file prem to check, and it seemed that it only updated when that was replaced, but it could also be something i did supidly
SYSTEM 0.13.0-6AEDC39
go2rtc 1.7.1 [dashboard](http://172.16.103.7:5000/live/webrtc/)

@blakeblackshear 

May also be worth it to split the configs for 1.7 since it writes back keys to the config if you use homekit output, unless you have a plan for such ;p

I am busy testing it now, managed to setup the HK pairing on a docker insance on Unraid, and its super quick to stream cameras as apposed to frig=>ha=>HK

**Comment by NickM-27** [comment]
yeah, we'll need to support that, unfortunately don't have anything to test myself so will be difficult

**Comment by cybertza** [comment]
Ok so i didnt quite do it this way, but WE, what i would recommend you do to test this is the following

add the homekit to your FFrig config, then set it up with the PIN, (unique per cam) and what is entered on the HK config under find additional devices, my device isnt shown and then pair it, then go into your go2rtc config, and copy that key that its added to the cam, and add that your frig config

image
image

**Comment by cybertza** [comment]
Any idea how i would get this to work with Homekit?

 ```
 birdseye: exec:ffmpeg -hide_banner -f rawvideo -pix_fmt yuv420p -video_size 1280x720
    -r 10 -i /tmp/cache/birdseye -c:v libx264 -g 50 -profile:v high -level:v 4.1 -preset:v
    superfast -tune:v zerolatency -rtsp_transport tcp -f rtsp {output}
   
```
Reason im trying this is since i assume the problem is that there is a problem somehow related to that, since i am having issues streaming to HK, all the other streams works fine with the config as described above, but as i understand this is h264 output, but somewhere its not 


I am a bit out of my depth with why the Birdseye does not want to restream, I get the static frame but no stream, the rest of the cams are wokring well, when i look at the consumers i do not notice a difference, so i would then assume its somewhere in the producers area that the problem would be. Well, atleast i have gotten the cameras in with huge proformace increase vs pulling them via HA, 

There is so nice oppertunity now for also creating "last detected" and an "birdseye alike" last of person detected over all the cams, as a stream if people would want that.

Hope the above assists someone going down this path of early adoption, im sure that all this will be much easier in the future anyway ;p

**Comment by NickM-27** [comment]
are you saying that birdseye restream isn't working in the frigate webUI, or that it specifically isn't working in homekit?

**Comment by cybertza** [comment]
Its working in the Frigate WebUi, Its not streaming in HomeKit, but it does show the preview, Then when you open the stream it takes some time and then goes to "No Response"

i have recreated the cam in HomeKit, and so forth as well to test, same result, other cameras work great.

So in short everything / all cams work well both places just HK doesnt stream the Birdseye.

config is 

CAMS => Go2rtc => frig (with go2rtc as inputs) 

                Go2rtc => HomekIt
                
                frig Birdseye => go2rtc => Homekit

**Comment by NickM-27** [comment]
I wonder if homekit requires audio

**Pull request merged**
