### PR TITLE
Ability to set point of bounding box that triggers a zone

### PR DESCRIPTION
**Pull request by NickM-27**
## Description

Probably fits into a future release after `0.11` but happy to discuss either way.

Per discussion https://github.com/blakeblackshear/frigate/discussions/3262 there are some cases where the bottom center is difficult to create a zone for, zones can be configured to be trigger by (bottom, left, right, top)-center of the bounding box. 

Default remains the bottom-center

## Open Questions

Potentially could add others but I personally thought these four should suffice, but curious if more should be added?

### CODE REVIEW

**Review by NickM-27 — COMMENTED** [review]
(tried out the new built in VS code, it created this comment along with the commit for some reason lol)

**Comment by h3rbst** [comment]
@NickM-27 would reeeally really love to see this feature! I want to get notifications when somebody was at the letter box, but this is not possible with the bottom center pixel :( Any idea when this could be merged and be available?

**Comment by NickM-27** [comment]
> @NickM-27 would reeeally really love to see this feature! I want to get notifications when somebody was at the letter box, but this is not possible with the bottom center pixel :( Any idea when this could be merged and be available?

Not for 0.12

**Comment by h3rbst** [comment]
Is it possible to consider this for future releases? Would really love to see that feature! 🤩

**Comment by h3rbst** [comment]
@NickM-27 Don't want to annoy you, but is it possible to consider this PR in future Releases? Would really help me in detecting new letters in the postbox.
Or is there any other option in the meantime I missed to trigger an event when not the bottom pixel is in the zone?

**Pull request closed without merging**
