### PR TITLE
[Docs] Add missing hyphen to docker-compose cmd

### PR DESCRIPTION
**Pull request by baylanger**
Noticed a typo.

```
# docker compose
docker: 'compose' is not a docker command.
```

### CODE REVIEW

**Comment by NickM-27** [comment]
that's not a typo, `docker compose` and `docker-compose` can be valid depending on if it was installed via docker desktop or directly

**Comment by baylanger** [comment]
Gotcha :) ! Fantastic, I learned something new.

**Comment by deviant77** [comment]
> that's not a typo, `docker compose` and `docker-compose` can be valid depending on if it was installed via docker desktop or directly

Actually, `docker-compose` is version 1 of the binary and `docker compose` is version 2.
https://docs.docker.com/compose/faq/#what-is-the-difference-between-docker-compose-and-docker-compose

**Comment by blakeblackshear** [comment]
If you follow the official installation docs for docker, you will end up with `docker compose`, not `docker-compose`

**Comment by baylanger** [comment]
> Actually, `docker-compose` is version 1 of the binary and `docker compose` is version 2. https://docs.docker.com/compose/faq/#what-is-the-difference-between-docker-compose-and-docker-compose
>
lol - after digging around, I was ended up exactly on that page cuz I wanted understand the reasoning behind this.

On Synology, docker is provided by the manufacturer ... it might be possible to manually install a different/newer version.

**Comment by deviant77** [comment]
> > Actually, `docker-compose` is version 1 of the binary and `docker compose` is version 2. https://docs.docker.com/compose/faq/#what-is-the-difference-between-docker-compose-and-docker-compose
> 
> lol - after digging around, I was ended up exactly on that page cuz I wanted understand the reasoning behind this.
> 
> On Synology, docker is provided by the manufacturer ... it might be possible to manually install a different/newer version.

Ahh Synology... If you have a recent version of DSM, then it's actually `docker compose` version 2! :zany_face:
However in their wisdom they've renamed it `docker-compose`.

**Pull request closed without merging**
