### PR TITLE
Go2RTC configuration editor

### PR DESCRIPTION
**Pull request by skrashevich**
Web-editor for go2rtc configuration API, introduced in master branch (https://github.com/AlexxIT/go2rtc/pull/153, will be available from v0.1-rc.9 release)

### CODE REVIEW

**Comment by NickM-27** [comment]
This doesn't really work, by default the config is inside the container and so any edits to the config will be reset when the container restarts. You'll probably need to check if the file is at the custom file location and only show the go2rtc editor in that case. 

I also think this should be part of the same /config route and just have an option to choose between them

**Comment by skrashevich** [comment]
I anticipate that the entirety of the /config directory is located within a mounted partition. In my opinion, this is more correct than mounting exclusively the config.yml. Incidentally, in the current docker-compose configuration, the existing frigate configuration editor is also useless, as the config is mounted in read-only mode.

**Comment by skrashevich** [comment]
> You'll probably need to check if the file exists at the custom file location shown in the docs and only show the go2rtc editor in that case.

Thus, is it proposed to deprive the user of the convenient ability to create a configuration file from scratch?

**Comment by AlexxIT** [comment]
Maybe it makes sense to allow users to change the config?
This can be done in two ways - either by marking the folder with the config as volume. Or use `/config/go2rtc.yaml`.

Or are you planning to use go2rtc exclusively for Frigate? And if the user needs some additional functions from go2rtc - he will have to install another go2rtc. This can be a problem because two go2rtc can start fighting for open ports.

**Comment by NickM-27** [comment]
> I anticipate that the entirety of the /config directory is located within a mounted partition. In my opinion, this is more correct than mounting exclusively the config.yml.

The frigate-go2rtc file won't exist there and go2rtc is pointed at an internally held default config file unless the user chooses to override it

https://github.com/blakeblackshear/frigate/blob/dev/docker/rootfs/etc/services.d/go2rtc/run#L7

So it is irrelevant whether or not the entire directory is mounted because an internal file is used unless the user has created this.

> Incidentally, in the current docker-compose configuration, the existing frigate configuration editor is also useless, as the config is mounted in read-only mode.

all our docs have been updated to not have it in read-only mode.

> Thus, is it proposed to deprive the user of the convenient ability to create a configuration file from scratch?

it won't work that way though. You are using the go2rtc to pull the config file which by default is pointed at an internal file which when edited will be reset on restart so the editor will be useless without the custom file being stored.

**Comment by skrashevich** [comment]
> all our docs have been updated to not have it in read-only mode.
Allow me to disagree with you.
https://github.com/blakeblackshear/frigate/blob/dev/docker-compose.yml (line 30)

**Comment by NickM-27** [comment]
> > all our docs have been updated to not have it in read-only mode.
> > Allow me to disagree with you.
> > https://github.com/blakeblackshear/frigate/blob/dev/docker-compose.yml (line 30)

That's not documentation that is the dev container, has nothing to do with users using frigate.

**Comment by felipecrs** [comment]
So, maybe the configuration editor should have a toggle on whether use a custom config or not. The whole editor is greyed out if this toggle is not activated. 

But when it's activated, the user can write its own config in the editor, and when Saving, the `/config/frigate-go2rtc.yaml` file gets automatically created if it's not created yet.

If the file is already there, but user deactivates this option, we delete it.

**Comment by AlexxIT** [comment]
Latest go2rtc will have API (`/api`), that points to config location:

```json
{
    "config_path": "go2rtc.yaml",
    "host": "192.168.1.123:1984",
    "rtsp": {"listen": ":8554"},
    "version": "0.1-rc.8"
}
```

**Comment by NickM-27** [comment]
> So, maybe the configuration editor should have a toggle on whether use a custom config or not. The whole editor is greyed out if this toggle is not activated.
> 
> But when it's activated, the user can write its own config in the editor, and when Saving, the `/config/frigate-go2rtc.yaml` file gets automatically created if it's not created yet.
> 
> If the file is already there, but user deactivates this option, we delete it.

I don't think a toggle is necessary. But the problem I see right now is it is using go2rtc to save the contents of the file which will save to `/usr/local/go2rtc/go2rtc.yaml` by default which is useless. So we will need frigate to handle the saving of the config file so that it knows to save to the `/config/frigate-go2rtc.yaml` instead of the internal file

**Comment by felipecrs** [comment]
Or... we get rid of this internal go2rtc config at all. If we could set the Frigate mandatory customizations through either environment variables or through `--cli-flags`, that would solve some confusion. It would even simplify the docs because people would not need to make sure their own go2rtc contains the stuff needed by Frigate.

**Comment by NickM-27** [comment]
@AlexxIT the problem is by default we have a minimal go2rtc config stored inside the container which is used. We only use the user-defined go2rtc config if it exists. So go2rtc API will point to a file that is not mapped to user storage and will be reset on container restart

**Comment by felipecrs** [comment]
This is the minimal config btw: https://github.com/blakeblackshear/frigate/blob/dev/docker/rootfs/usr/local/go2rtc/go2rtc.yaml

**Comment by AlexxIT** [comment]
I can add the config in raw form as a cli parameter. Just need to decide what to do if there are two configurations.

**Comment by felipecrs** [comment]
So, what we would need, I guess, would be:

```console
go2rtc --log-format text --webrtc-candidate stun:8555
```

@AlexxIT, actually don't you think `stun:8555` could be part of the default go2rtc config? I think it doesn't cause any harm, in any situation, while makes it simpler for users.

Then, we would only need:

```console
go2rtc --log-format text
```

**Comment by NickM-27** [comment]
> Or... we get rid of this internal go2rtc config at all. If we could set the Frigate mandatory customizations through either `GO2RTC_ENVIRONMENT_VARIABLES` or through `--cli-flags`, that would solve some confusion. It would even simplify the docs because people would not need to make sure their own go2rtc contains the stuff needed by Frigate.

I don't see how that solves this current issue though, one way or another the user needs a specific setup to have the frigate-go2rtc.yaml file mapped to their storage. Otherwise saving the config will not meaningfully be saving anything.

**Comment by felipecrs** [comment]
> I can add the config in raw form as a cli parameter. Just need to decide what to do if there are two config (cli + file).

CLI should be preferred, that's the pattern I see for other applications. In this order:

1. CLI
2. Env var
3. Config file

**Comment by NickM-27** [comment]
Unless I am misunderstanding and it has already been agreed that if the frigate-go2rtc.yaml file does not exist, no config editor is shown

**Comment by felipecrs** [comment]
> I don't see how that solves this current issue though, one way or another the user needs a specific setup to have the frigate-go2rtc.yaml file mapped to their storage. Otherwise saving the config will not meaningfully be saving anything.

This is not much of an issue for Add-on users as the whole `/config` folder is mapped there. Perhaps we should also recommend mapping a `/config` folder for docker users, instead of mapping only the config files?

**Comment by NickM-27** [comment]
> > I don't see how that solves this current issue though, one way or another the user needs a specific setup to have the frigate-go2rtc.yaml file mapped to their storage. Otherwise saving the config will not meaningfully be saving anything.
> 
> This is not much of an issue for Add-on users as the whole `/config` folder is mapped there. Perhaps we should also recommend mapping a `/config` folder for docker users, instead of mapping only the config files?

It can be recommended but the scenario still needs to be handled

**Comment by felipecrs** [comment]
> Unless I am misunderstanding and it has already been agreed that if the frigate-go2rtc.yaml file does not exist, no config editor is shown

I'm sorry, my bad. I didn't read the whole conversation and I came here directly hopeful that I had a good idea to contribute.

**Comment by NickM-27** [comment]
> > Unless I am misunderstanding and it has already been agreed that if the frigate-go2rtc.yaml file does not exist, no config editor is shown
> 
> I'm sorry, my bad. I didn't read the whole conversation and I came here directly hopeful that I had a good idea to contribute.

I think we are working towards a solution that makes sense, but things need to be well thought out so users are not confused why editing a file is doing nothing after restarting.

**Comment by felipecrs** [comment]
> It can be recommended but the scenario still needs to be handled

It can be handled, I think:

1. If `frigate-go2rtc.yaml` exists:
    - If it is a file, all good.
    - If it is a folder (`--volume /path/to/non/existing/file:/config/frigate-go2rtc.yaml` creates an empty folder at `/config/frigate-go2rtc.yaml`, error.
3. If `frigate-go2rtc.yaml` does not exist, check if `/config` is a mount point:
    - If it is, all good, file can be created.
    - If it is not, error.
    
Or, if you want to simplify the setup, you just set a message in the editor if `frigate-go2rtc.yaml` does not exist or it's not a file:

_To edit the go2rtc configuration, make sure the file `/config/frigate-go2rtc.yaml` exists and is mounted._

**Comment by NickM-27** [comment]
> > It can be recommended but the scenario still needs to be handled
> 
> It can be handled, I think:
> 
> 1. If `frigate-go2rtc.yaml` exists:
>    
>    * If it is a file, all good.
>    * If it is a folder (`--volume /path/to/non/existing/file:/config/frigate-go2rtc.yaml` creates an empty folder at `/config/frigate-go2rtc.yaml`), error.
> 2. If `frigate-go2rtc.yaml` does not exist, check if `/config` is a mount point:
>    
>    * If it is, all good, file can be created.
>    * If it is not, error.
> 
> Or, if you want to simplify the setup, you just set a message in the editor if `frigate-go2rtc.yaml` does not exist or it's not a file:
> 
> _To edit the go2rtc configuration, make sure the file `/config/frigate-go2rtc.yaml` exists and is mounted from your host machine to the Frigate container._
> 
> Which is what was already proposed, basically.

Thanks for outlining it clearly, I think this makes sense. I do agree we should show that error message.

I also want to reiterate that I think we should have one `/config` route which has a tab selector to choose between the frigate and go2rtc config editors

**Comment by AlexxIT** [comment]
Well. Check it https://github.com/AlexxIT/go2rtc/commit/0b291f5185026953ce3fdeb9210586216de05248

Now you can use:

```
go2rtc -config "{log: {format: text}}" -config go2rtc1.yaml -config "{rtsp: {listen: ''}}" -config go2rtc2.yaml
```

**Comment by NickM-27** [comment]
> Well. Check it [AlexxIT/go2rtc@0b291f5](https://github.com/AlexxIT/go2rtc/commit/0b291f5185026953ce3fdeb9210586216de05248)
> 
> Now you can use:
> 
> ```
> go2rtc -config "{log: {format: text}}" -config go2rtc1.yaml -config "{rtsp: {listen: ''}}" -config go2rtc2.yaml
> ```
> 
> Every next will overwrite previous (but only defined params).

That is very cool, what happens if we do `-config fle_that_does_not_exist.yaml` ?

**Comment by AlexxIT** [comment]
It will be skipped
https://github.com/AlexxIT/go2rtc/blob/0b291f5185026953ce3fdeb9210586216de05248/cmd/app/app.go#L41

**Comment by NickM-27** [comment]
In that case I think we can remove the built in file and start go2rtc with a raw text config and also point it to frigate-go2rtc.yaml. 

When saving the file it may show an error that the file can not be written to. @skrashevich Do you want to handle rewriting the S6 logic to do this? Otherwise I can put up a PR for that part. 

Both of these will need to wait for go2rtc rc9 to be out before being merged here.

**Comment by skrashevich** [comment]
> Well. Check it [AlexxIT/go2rtc@0b291f5](https://github.com/AlexxIT/go2rtc/commit/0b291f5185026953ce3fdeb9210586216de05248)
> 
> Now you can use:
> 
> ```
> go2rtc -config "{log: {format: text}}" -config go2rtc1.yaml -config "{rtsp: {listen: ''}}" -config go2rtc2.yaml
> ```
> 
> Every next will overwrite previous (but only defined params).

There is another way of doing this.
https://github.com/AlexxIT/go2rtc/pull/170

**Comment by skrashevich** [comment]
> @skrashevich Do you want to handle rewriting the S6 logic to do this? Otherwise I can put up a PR for that part.

What S6 logic are you speaking?

**Comment by felipecrs** [comment]
@skrashevich you need to:

- Remove this file: https://github.com/blakeblackshear/frigate/blob/dev/docker/rootfs/usr/local/go2rtc/go2rtc.yaml

- Adjust this logic to point to the new behavior `-config '{ text mode }' -config /config/frigate-go2rtc.yaml`
  https://github.com/blakeblackshear/frigate/blob/dev/docker/rootfs/etc/services.d/go2rtc/run#L7-L15

**Comment by NickM-27** [comment]
> > @skrashevich Do you want to handle rewriting the S6 logic to do this? Otherwise I can put up a PR for that part.
> 
> What S6 logic are you speaking?

I'll just put a general summary of the current situation and changes that should be made:
1. do what @felipecrs said
2. We need to remove the specific go2rtc path in frigate webUI and include it inside the same config path with a selector (like the logs page)
3. Need to handle the case that the user has not created frigate-go2rtc.yaml, give an informative error message that the user needs to create this file before the config editor can be shown (we do not want a user editing a file which will not be persisted)

**Comment by skrashevich** [comment]
> @skrashevich you need to:
> 
> * Remove this file: https://github.com/blakeblackshear/frigate/blob/dev/docker/rootfs/usr/local/go2rtc/go2rtc.yaml
> * Adjust this logic to point to the new behavior `-config /config/frigate-go2rtc.yaml -config '{ text mode }'`
>   https://github.com/blakeblackshear/frigate/blob/dev/docker/rootfs/etc/services.d/go2rtc/run#L7-L15

Ok

**Comment by felipecrs** [comment]
I think this PR does not make sense anymore. Since https://github.com/blakeblackshear/frigate/pull/5106 now the go2rtc config is embedded in the frigate.yaml, which already has an editor.

**Comment by NickM-27** [comment]
yes, this should not be needed anymore 👍

**Pull request closed without merging**
