### PR TITLE
improvement: Experimental UI

### PR DESCRIPTION
**Pull request by johnmarksilly**
# Experimental UI

## Improvements

- Modified video player to use Video.js to support browsers that can't natively stream HLS
- Fixed glitch where the height of the container wouldn't stay the same causing it to be a pain to scrub through events.

### CODE REVIEW

**Comment by blakeblackshear** [comment]
can you rebase this?

**Comment by johnmarksilly** [comment]
Rebase on to which branch/commit?

**Comment by NickM-27** [comment]
> Rebase on to which branch/commit?

I think just need to pull in the latest changes on release-0.11.0 so the tests pass

**Comment by johnmarksilly** [comment]
@NickM-27 Good to go

**Review by NickM-27 — APPROVED** [review]

**Pull request merged**
