### PR TITLE
Birdseye Autolayout

### PR DESCRIPTION
**Pull request by NickM-27**
This PR works to attempt to fill in the full birdseye canvas with camera as opposed to the grid layout. This is especially useful for cameras like my hikvision panoramic which essentially takes up the same space as 2 16:9 cameras. There are a few behavior changes relative to the previous implementation:

- the birdseye aspect ratio matters, this should match the aspect ratio of the majority of your cameras so they fit nicely into the layout
- the birdseye resolution matters, the auto layout implementation will attempt to put all cameras in based on their native detect resolution and then scale down if there is not enough height available. 
- the order of the cameras matters and can be customized to better fit what is optimal

Screen Shot 2023-06-07 at 10 45 34 AM

### CODE REVIEW

**Comment by blakeblackshear** [comment]
Did you test this with portrait cameras as well?

**Comment by NickM-27** [comment]
No I haven't tested with portrait, I think it would work fine if the birdseye resolution was set to portrait but if it was the default horizontal I don't think this would allow portrait to take the full screen

**Review by blakeblackshear — APPROVED** [review]

**Comment by JeffWDH** [comment]
> No I haven't tested with portrait, I think it would work fine if the birdseye resolution was set to portrait but if it was the default horizontal I don't think this would allow portrait to take the full screen

Can confirm, a vertical camera gets squished into a box suitable for a normal horizontal camera. I think it would be nice to have the option for a vertical camera to take up two horizontal places.

Example:
```
|       |   H1   |
|   V   |--------|
|       |   H2   |
```

**Comment by JeffWDH** [comment]
@NickM-27 I was testing with two, one vertical and one horizontal. 

I just tested with one vertical and two horizontal and a similar layout happens, the vertical one gets squished into a.box suitable for a horizontal camera.

**Comment by NickM-27** [comment]
Thanks, I have fixed this https://github.com/blakeblackshear/frigate/pull/6779

**Comment by JeffWDH** [comment]
@NickM-27 Excellent, thank you very much for all the work you put into this project.

**Comment by ccutrer** [comment]
This is not working well with my one portrait camera. It's getting squished down tiny. I'm on 0.13.0-FF90DB3. I am seeing a couple log lines about `2023-06-12 22:08:29.727095303  [2023-06-12 22:08:29] frigate.output                 ERROR   : Canvas ratio is 810.0 > 720 :: 1.5`, which I'm not sure if it's related or not.

latest

**Comment by NickM-27** [comment]
@ccutrer Have you read the conversation above?

**Comment by ccutrer** [comment]
Yes. In particular
> I just tested with one vertical and two horizontal and a similar layout happens, the vertical one gets squished into a.box suitable for a horizontal camera.

But my screenshot looks like my portrait camera is somehow getting squished down to 1/4 the size of a box suitable for a landscape camera, not _one_. I also saw a similar thing when I had ~10 active cameras. I'm happy to test that PR out though. Are docker images not automatically generated for PRs?

**Comment by NickM-27** [comment]
it's the same issue, fixed in the PR. It is also worth noting that the cameras that come first in the order are given higher priority as far as sizing goes. So if you want the portrait camera to be higher size you should order it to be one of the first ones in the layout

**Comment by NickM-27** [comment]
yeah, you need to set the birdseye order with

```
cameras:
  your_camera:
    birdseye:
      order: x
```

**Comment by JeffWDH** [comment]
That makes much more sense than what I was doing :)

I ordered the vertical camera 0, and the other two 1 & 2. The birdseye stream is broken now and get the following errors in the log:
```
2023-06-13 14:51:23.811805977  Traceback (most recent call last):
2023-06-13 14:51:23.811812317    File "/opt/frigate/frigate/output.py", line 549, in update
2023-06-13 14:51:23.811813877      updated_frame = self.update_frame()
2023-06-13 14:51:23.811815797    File "/opt/frigate/frigate/output.py", line 525, in update_frame
2023-06-13 14:51:23.811816997      self.copy_to_position(
2023-06-13 14:51:23.811818237    File "/opt/frigate/frigate/output.py", line 251, in copy_to_position
2023-06-13 14:51:23.811819247      copy_yuv_to_position(
2023-06-13 14:51:23.811820387    File "/opt/frigate/frigate/util.py", line 481, in copy_yuv_to_position
2023-06-13 14:51:23.811821387      destination_frame[
2023-06-13 14:51:23.811822567  ValueError: could not broadcast input array from shape (1280,720) into shape (1080,720)
```

**Comment by NickM-27** [comment]
Interesting, I'll take a look at that but for now maybe try increasing the birdseye resolution slightly

**Comment by JeffWDH** [comment]
This is with:
  width: 2000
  height: 1100
image

No errors in the log

**Comment by NickM-27** [comment]
what is the resolution on the portrait cam?

**Comment by JeffWDH** [comment]
Detect (W/H): 720/1280
Record (W/H): 1440x2560

**Comment by DrSpaldo** [comment]
Will the changes made here give the potential for Birdseye to only display one camera? Ie. Only display the camera with the last motion, so you see the current/last motion camera better and not split?

**Comment by NickM-27** [comment]
> Will the changes made here give the potential for Birdseye to only display one camera? Ie. Only display the camera with the last motion, so you see the current/last motion camera better and not split?

Not sure I understand the question, birdseye always showed 1 camera if only 1 camera fit the activity type. These PRs only change the layout not the birdseye behavior itself

**Comment by DrSpaldo** [comment]
> 
> Not sure I understand the question, birdseye always showed 1 camera if only 1 camera fit the activity type. These PRs only change the layout not the birdseye behavior itself

Thanks @NickM-27 , I was hoping that the changes may allow for the display to only ever show one camera. The last camera that detected motion or an object. So that there is ever only one larger display but it would change depending on the most recent motion or object detection

**Comment by isaacolsen94** [comment]
So out of curiosity (tried testing real fast but couldn't get Unraid to download dev branch), if I have 6 x 16:9 feeds, and 2 4:3 feeds. would this be able to make 2 columns x 3 rows of 16:9 and 1 column 2 rows of 4:3 to fill the screen?

**Comment by NickM-27** [comment]
> So out of curiosity (tried testing real fast but couldn't get Unraid to download dev branch), if I have 6 x 16:9 feeds, and 2 4:3 feeds. would this be able to make 2 columns x 3 rows of 16:9 and 1 column 2 rows of 4:3 to fill the screen?

It would depend on the order of the cameras

**Pull request merged**
