### PR TITLE
GPU support

### PR DESCRIPTION
**Pull request by asmirnou**
### GPU via TensorRT

Object detection can run now on Nvidia CUDA GPUs. The logic of device selection is preserved: Edge TPU is detected and loaded first, if Coral isn't available, then GPU is determined, lastly, if no GPU, the program falls back to CPU.

On GPU TensorRT performs the inference, not TensorFlow. TensorRT takes a trained TensorFlow network and produces a highly optimized runtime engine which performs inference on an Nvidia GPU. TensorFlow saved neural network has to be parsed from its saved format into TensorRT using TensorFlow/UFF parser. There are a number of ways to do this, but the simplest is to grab ready UFF model from Nvidia [Jetson Nano Inference](https://github.com/dusty-nv/jetson-inference) project. Their [Model Download Mirror](https://github.com/dusty-nv/jetson-inference/releases/tag/model-mirror-190618) contains many models including SSD Mobilenet V1/V2 used in Frigate. 

### CPU: TensorFlow Lite -> Tensorflow

For CPU object detector TensorFlow Lite implementation was replaced with TensorFlow due to poor performance of the former. From the comparison below one can notice TensorFlow Lite running on desktop without any GPU delegate is **9 times worse** than TensorFlow. TensorFlow Lite runtime is still used for Coral, however, so this change should not impact the users. Whoever runs the Frigate without the Coral will appreciate performance gains.

## Performance comparison

Hardware: 
 - CPU: Intel Core i7
 - GPU: Nvidia GeForce GTX 860M
 - Camera: Android IP Webcam, 30 FPS max

#### 0.5.1-rc2 on CPU
<details>
<summary>Inference: 355 ms, 3 FPS max</summary>

```json
{
	"back": {
		"detection_fps": 2.8,
		"ffmpeg_pid": 35,
		"fps": 2.8,
		"pid": 37,
		"read_start": 0.0,
		"skipped_fps": 0.0
	},
	"coral": {
		"detection_start": 1586287886.987141,
		"fps": 2.8,
		"inference_speed": 355.42,
		"pid": 30
	},
	"plasma_store_rc": null
}
```
</details>

#### this PR on CPU
<details>
<summary>Inference: 40 ms, 24 FPS max</summary>

```json
{
	"back": {
		"detection_fps": 23.9,
		"ffmpeg_pid": 65,
		"fps": 5.0,
		"pid": 67,
		"read_start": 0.0,
		"skipped_fps": 0.0
	},
	"coral": {
		"detection_start": 1586288847.229801,
		"fps": 23.9,
		"inference_speed": 39.52,
		"pid": 31
	},
	"plasma_store_rc": null
}
```
</details>

#### this PR on GPU
<details>
<summary>Inference: 15 ms, 64 FPS max</summary>

```json
{
	"back": {
		"detection_fps": 25.9,
		"ffmpeg_pid": 88,
		"fps": 13.9,
		"pid": 46,
		"read_start": 1586289150.060212,
		"skipped_fps": 0.0
	},
	"coral": {
		"detection_start": 0.0,
		"fps": 25.9,
		"inference_speed": 15.11,
		"pid": 36
	},
	"plasma_store_rc": null
}
```
</details>

## Code changes explained

TensorFlow [properly set up](https://www.tensorflow.org/install/gpu#software_requirements) can perform the inference through GPU as well, but the reasons for choosing TensorRT were as follows:
- Object detection on TensorFlow is memory hungry: it reserves nearly all of the GPU memory and requires not less than 2 GiB just for initialization. 

  TensorRT performs the inference consuming only 365 MiB of GPU memory.
- GPU support shipped with TensorFlow is compatible with limited number of CUDA-enabled devices. In many of cases to be able to work with GPU TensorFlow has to be rebuilt from sources.

  TensorRT runtime supports all CUDA GPUs out of the box.

TensorRT engine is built at startup of Docker container, because the process of building the engine requires a GPU on board. Due to uncertainty whether a person who builds a Docker image has GPU or not and for the sake of possible CI automation, the process of building a TensoRT engine was moved to container startup.

Two Docker images are supposed to be build during release: with and without GPU support. The latter is nearly two times larger as it contains CUDA and TensorRT runtime. Users can choose which one suits their hardware.

In Docker image Python was downgraded from 3.7 to the default version 3.6.9 shipped with Ubuntu 18.04. I had to do it in order to install TensorRT wheels for Python in Docker image with GPU support. TensorRT is installed from Nvidia Debian repository and this method provides the wheels only for Python 3.6.9. The wheels for other Python versions are in Deb, Tar and Zip files of TensorRT distributive, which are free for download, but require Nvidia Developer Account and authentication. To avoid using any credentials, foreseeing possible automation and haven't found code binding to Python 3.7, I took the liberties to downgrade Python.

Inference on a CPU runs on any version of TensorFlow (I tested 1.15.2 and 2.1), but 1.15.2 occupies far less disk space, so for the sake of smaller Docker image, the lower version is installed.

### CODE REVIEW

**Comment by saket424** [comment]
@asmirnou 
When I try to build on a jetson nano the frigate base from Dockerfile using your pull request 121, i get an error

i965-va-driver and  opencv-python-headless 

no candidate to install

Can you explicitly state here the procedure you followed to build this PR for the jetson nano. Thanks

**Comment by asmirnou** [comment]
@saket424 I haven't got Jetson Nano and had no chance to test my PR on it. It may sound unfounded, but I think Python code of Frigate is compatible with Jetson devices. The build process for Jetson systems differs from the docker files, however, as Python, OpenCV, CUDA, CuDNN, TensorRT are already included in JetPack.

_i965-va-driver_ is intended for the Intel G45 chipsets and Intel HD Graphics for the Intel Core processor family. As they are not present in Jetson Nano, omit installing this library. To use FFmpeg on Jetson Nano, you may need to build it with [this](https://github.com/jocover/jetson-ffmpeg) library.

_Opencv-python_ [should be installed](https://forums.developer.nvidia.com/t/install-opencv-for-python3-in-jetson-nano/74042/2) in Nano's system wide Python installation. I assume this error comes from Python virtual environment, where the package is missing. To avoid building it from source, you may find useful the trick I used for PyCUDA: [copy](https://github.com/asmirnou/frigate/blob/gpu_support/Dockerfile.gpu#L144) Python wheels for a package into some directory and then [install](https://github.com/asmirnou/frigate/blob/gpu_support/Dockerfile.gpu#L171) them in another Python environment.

P.S. Makes sense to move the discussion about Jetson Nano to #103 as this PR is not specifically for Jetson systems, but Nvidia CUDA GPUs.

**Comment by blakeblackshear** [comment]
This looks great. Once 0.5.x gets fully stable, I will look at merging this in.

**Comment by blakeblackshear** [comment]
Please update this PR to point to `master`

**Comment by ne0ark** [comment]
Can ffmpeg also be modified to run CUDA and intel sync?

**Comment by miikkajo** [comment]
https://github.com/miikkajo/frigate/blob/gpu_support/Dockerfile.gpu

I'm using CUDA enabled ffmpeg, you need to build it from source and copy to final image

**Comment by ne0ark** [comment]
Can you please sent PR to point to master.

**Comment by ne0ark** [comment]
@miikkajo Can you also please share ffmpeg parameters you are using in configuration with -hwaccel cuda

**Comment by miikkajo** [comment]
for rtsp cam:

   take_frame: 2
    ffmpeg:
      input: rtsp://user:pass@192.168.1.81:88/videoSub
      hwaccel_args:
        - -hwaccel
        - cuda
      output_args:
        - -vf
        - "transpose=1"
        - -f
        - rawvideo
        - -pix_fmt
        - rgb24

transpose is for image rotate.

and for my reolink rtmp:

    ffmpeg:
      input: rtmp://192.168.1.82/bcs/channel0_sub.bcs?token=254&channel=1&stream=0&user=user&password=pass
      hwaccel_args:
        - -hwaccel
        - cuda
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -vsync
        - drop
        - -use_wallclock_as_timestamps
        - '1'

**Comment by ne0ark** [comment]
Thanks I tried it and it works well but cpu usage on 7 4k stream is still high ~7 on i7-4470 + Nvidia 1650 (~30 usage).

**Comment by burmjohn** [comment]
Any news when this might be merged in?

**Comment by blakeblackshear** [comment]
This is a very old PR. TensorRT does not support the version of python used by frigate, so GPU support is not in the near term plan.

**Comment by nordeep** [comment]
Is there any chance to come back to this PR? Seems TensorRT support last python versions - https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html

It would be great to have GPU support. The ability to run on a GPU will allow to involve more users. Not everyone has Edge TPU, but many have GPU.

**Pull request closed without merging**
