### PR TITLE
Added health check url

### PR DESCRIPTION
**Pull request by ivelin**
To address #53

### CODE REVIEW

**Comment by ivelin** [comment]
Example docker-compose.yml entry:

```

  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    image: ivelin/frigate:unofficial_pi4_aug_20_2019
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /opt/frigate/config:/config
      - /opt/frigate:/opt/frigate
    ports:
      - "5000:5000"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:5000/"]
      interval: 30s
      timeout: 1s
      retries: 10
```

Example Dockerfile entry:

```

HEALTHCHECK CMD curl --fail http://localhost:5000/ || exit 1

CMD ["python3", "-u", "detect_objects.py"]

```

**Comment by billimek** [comment]
This may be solved now with [this commit](https://github.com/blakeblackshear/frigate/commit/39d64f7ba71cfebafb4eca169ab9a4a4bb987e17#diff-7d64accf17244689e844fc4a9147dc19R69-R72).

It appears that the `/` route will give a 200 response with the string `Frigate is running. Alive and healthy!` when it is healthy?

**Comment by blakeblackshear** [comment]
I pulled in some of the changes from this PR. It is a starting point. Let me know if you think of specific things it would be helpful to check on that endpoint (coral status, threads running). Personally, I haven't experienced a failure that required a restart of the container yet.

**Comment by Draxter** [comment]
I think this needs to be revisited. While being able to monitor the frontend app using a curl healthcheck is useful, I think it's more useful for Frigate to monitor whether ffmpeg process is running, considering it has a tendency of sometimes failing for invalid data while the frontend continues to work fine.

**Comment by Steve-Tech** [comment]
I just found this and thought for the future people, you'd probably want to use `http://localhost:5000/api/` since just `http://localhost:5000/` is the web UI.

**Pull request closed without merging**
