### PR TITLE
Add support for easy translations

### LINKED ISSUE #3582: Contribute to the translation of the web interface
Hello I was reading the [contribution ](https://docs.frigate.video/contributing/#web-interface)section for the web section but I did not find information for the translation of the web interface I wanted to help

### LINKED ISSUE #3715: Language substitution
Is there any way to change these Title languages into other languages? I will translate and replace them myself
WX20220826-210520@2x

### PR DESCRIPTION
**Pull request by NickM-27**
No translations have been made, but the docs have been adjusted to be easy to setup translations without any code changes.

### CODE REVIEW

**Comment by menkej** [comment]
Nice work. Are you still working on fixing the test/lint errors @NickM-27 ? I could provide German translation.

**Comment by NickM-27** [comment]
@menkej I'm not done with the translations yet, have a few more pages to go but have gotten stuck working on other things.

**Comment by samuelstroschein** [comment]
Would [github/inlang/inlang](https://github.com/inlang/inlang) be of use for this PR? 

Inlang makes it easier to get contributions for translations and reduces the effort for maintainers. Happy to contribute to this PR or open another one.

**Comment by NickM-27** [comment]
The main work is just getting the strings in all the places of the code replaced. I think the current system won't be too bad for new translations but I think that can be ironed out once the initial version is working as expected with just english templates.

**Comment by samuelstroschein** [comment]
> The main work is just getting the strings in all the places of the code replaced.

I think inlang could help out to replace the string in the code.

The VSCode extension provides a keyboard shortcut (release in early March).  If you are using VSCode, I could open a PR? 
 
CleanShot 2023-02-14 at 21 27 42@2x

**Comment by NickM-27** [comment]
interesting, in that case feel free to make your own PR adding translations, this PR is decently out of date at this point

**Comment by samuelstroschein** [comment]
Starting the translation effort from scratch would be too much effort. let's see if other people want to contribute too

**Comment by NickM-27** [comment]
frontend has been rewritten in react and this will need to be rethought out

**Pull request closed without merging**
