### PR TITLE
Migrate default database path from `/media/frigate` to `/config`

### LINKED ISSUE #4856: Should not we store the database file in `/data` by default?
1. `/data` is unique per add-on, which persists for as long as the add-on is installed
2. Uninstalling the add-on would cause the database file to get deleted, which I think makes sense
3. I suppose several people maps their `/media/frigate` folder to an external (potentially an much slower HDD) device. It isn't smart to store the database in the HDD in this case.

### PR DESCRIPTION
**Pull request by felipecrs**
- Closes #4856

### CODE REVIEW

**Comment by felipecrs** [comment]
@NickM-27 this is working for me. Feel free to take a look on it, if you want.

**Comment by NickM-27** [comment]
You'll probably also want to update the config to point to the new location by default

**Comment by felipecrs** [comment]
You mean the docs?

**Comment by felipecrs** [comment]
lol that's the most important part. Thank you.

**Comment by bagobones** [comment]
Wouldn't /config/db make more sense (as the db is made up of several files)? Not sure if this would impact the docker mappings or not.. Some might want the ability to separate the config file and where the DB is stored if they have particularly huge setups or for backup reasons.

**Comment by NickM-27** [comment]
> Some might want the ability to separate the config file and where the DB is stored if they have particularly huge setups or for backup reasons.

This is already possible with frigate. This PR simply changes the default location.

**Comment by blakeblackshear** [comment]
can we get this rebased? I am ready to merge this.

**Comment by felipecrs** [comment]
Sure, I'll work on it.

**Comment by felipecrs** [comment]
@blakeblackshear done.

**Comment by felipecrs** [comment]
Just to remind, we should remove the following line for the add-on by the time we release the next beta:

https://github.com/blakeblackshear/frigate-hass-addons/blob/main/frigate/config.yaml#L51-L52

**Review by blakeblackshear — APPROVED** [review]

**Comment by NickM-27** [comment]
> Just to remind, we should remove the following line for the add-on by the time we release the next beta:
> 
> https://github.com/blakeblackshear/frigate-hass-addons/blob/5e67db091d07b37fe004c904b47eafe8d6bbaf12/frigate/config.yaml#L51-L52

what's the reasoning for that?

**Comment by felipecrs** [comment]
> what's the reasoning for that?

Actually it's not mandatory, it's just superfluous to have it set.

**Comment by NickM-27** [comment]
> > what's the reasoning for that?
> 
> Actually it's not mandatory, it's just superfluous to have it set.

I don't think that is correct. The file in addon is supposed to be called frigate.yml but by default frigate always looks for config.yml. The only way the addon knows to look for frigate.yml is because of this variable

**Comment by felipecrs** [comment]
Oh, that's right. Never mind, my bad!

**Comment by NickM-27** [comment]
this isn't working for me, it is exiting saying that the config file can not be found, but it is located at `/config/config.yaml`

**Comment by NickM-27** [comment]
I think the substitution was mixed up, will put up a PR to fix

**Pull request merged**
