### PR TITLE
Clean up output for vainfo and ffprobe

### LINKED ISSUE #5584: FFprobe "Copy" Button
### Describe the problem you are having

In 0.12, FFProbe is available directly on the System page for each camera, which is fantastic. The problem is if you use the "Copy" button, instead of actually copying the raw JSON, it copies an encoded-string version of the JSON, which is really hard to read when filing a ticket because double quotes are escaped, as are newlines. See "ffprobe output" below, which is a direct paste after pressing the "Copy" button.

### Version

0.12.0-27A31E7

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"15/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"display_aspect_ratio\": \"168:95\",\n          \"height\": 1520,\n          \"width\": 2688\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"AAC (Advanced Audio Coding)\"\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"15/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"display_aspect_ratio\": \"168:95\",\n          \"height\": 360,\n          \"width\": 640\n        }\n      ]\n    }\n  }\n]"
```

### Frigate stats

_No response_

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

_No response_

### PR DESCRIPTION
**Pull request by NickM-27**
Fixes #5584

### CODE REVIEW

**Comment by ccutrer** [comment]
You're removing the newlines, but `"` will still be escaped, no?

**Comment by NickM-27** [comment]
> You're removing the newlines, but `"` will still be escaped, no?

They are escaped, this is using regex. That being said I think it would be better to escape all whitespace

**Comment by blakeblackshear** [comment]
What of we just rendered the JSON into some kind of plain text output with new lines, etc? It's not that much better to view raw JSON without the escape characters.

**Comment by NickM-27** [comment]
> What of we just rendered the JSON into some kind of plain text output with new lines, etc? It's not that much better to view raw JSON without the escape characters. 

I believe that's how it's rendered already, this just affects how it's copied, unless I'm misunderstanding what you mean

**Comment by blakeblackshear** [comment]
I'm suggesting that we render it something like this instead of JSON in the UI:

**return_code**:
```
0
```

**stderr**:
```
```


**stdout**:
```
vainfo: VA-API version: 1.17 (libva 2.10.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Gemini Lake - 2.4.1
vainfo: Supported profile and entrypoints
 VAProfileMPEG2Simple :    VAEntrypointVLD
 VAProfileMPEG2Main :    VAEntrypointVLD
 VAProfileH264ConstrainedBaseline:   VAEntrypointVLD
 VAProfileH264ConstrainedBaseline:  VAEntrypointEncSlice
 VAProfileH264ConstrainedBaseline:    VAEntrypointEncSliceLP
 VAProfileH264Main :  VAEntrypointVLD
 VAProfileH264Main :   VAEntrypointEncSlice
 VAProfileH264Main :   VAEntrypointEncSliceLP
 VAProfileH264High : VAEntrypointVLD
 VAProfileH264High :  VAEntrypointEncSlice
 VAProfileH264High :  VAEntrypointEncSliceLP
 VAProfileH264MultiviewHigh :   VAEntrypointVLD
 VAProfileH264MultiviewHigh :   VAEntrypointEncSlice
 VAProfileH264StereoHigh : VAEntrypointVLD
 VAProfileH264StereoHigh :    VAEntrypointEncSlice
 VAProfileVC1Simple :   VAEntrypointVLD
 VAProfileVC1Main : VAEntrypointVLD
 VAProfileVC1Advanced :   VAEntrypointVLD
 VAProfileNone :    VAEntrypointVideoProc
 VAProfileJPEGBaseline :   VAEntrypointVLD
 VAProfileJPEGBaseline :    VAEntrypointEncPicture
 VAProfileVP8Version0_3 : VAEntrypointVLD
 VAProfileVP8Version0_3 : VAEntrypointEncSlice
 VAProfileHEVCMain : VAEntrypointVLD
 VAProfileHEVCMain :  VAEntrypointEncSlice
 VAProfileHEVCMain10 :    VAEntrypointVLD
 VAProfileHEVCMain10 :   VAEntrypointEncSlice
 VAProfileVP9Profile0 :    VAEntrypointVLD
 VAProfileVP9Profile0 :  VAEntrypointEncSlice
 VAProfileVP9Profile2 :   VAEntrypointVLD
```

**Comment by NickM-27** [comment]
Hopefully can do something similar with ffprobe

**Comment by NickM-27** [comment]
Here is the ffprobe output format now

Screen Shot 2023-02-25 at 15 58 58 PM

**Review by blakeblackshear — APPROVED** [review]

**Pull request merged**
