### PR TITLE
Allow detection to be disabled

### PR DESCRIPTION
**Pull request by rourke750**
Allows detection to be enabled or disabled via mqtt.  

Has not been tested yet, wanted to see if this was around what you were looking for.

### CODE REVIEW

**Comment by rourke750** [comment]
I've gone ahead and tested it and everything works

**Comment by rourke750** [comment]
@blakeblackshear just let me know what you need from this in order to merge or if you are just waiting on your changes to go through first.

**Comment by rourke750** [comment]
@blakeblackshear I've gone ahead and merged your changes in with mine

**Comment by seanb-uk** [comment]
It would be good to be able to do this on a per-camera basis, or at least to be able to dynamically set the "save clips" flag per camera. My use case is that I don't need detection or clips for one of my cameras when I'm home, as it'll just generate endless clips of me in the garden - I'm only interested in detection when I'm out or overnight (which I can automate through HA if there's a switch it can call to manage the cameras).

It doesn't even have to switch the stream and detection off - just the clips would do.

**Comment by ljmerza** [comment]
what's it going to take to get this merged? It's been a year and this is pretty nice feature to have.

**Comment by flaektrem** [comment]
It would be nice to have this feature. Arm/disarm mode

**Comment by blakeblackshear** [comment]
This is so old there is no way it can be merged as is. I am already working on it in a new branch.

**Pull request closed without merging**
