### PR TITLE
use a different method for blur and contrast to reduce CPU

### PR DESCRIPTION
**Pull request by blakeblackshear**

### CODE REVIEW

**Comment by NickM-27** [comment]
Pretty huge difference on mine

Screen Shot 2023-06-28 at 06 41 34 AM

**Comment by ccutrer** [comment]
Pretty massive difference for me, too. I'm at 20-25% idle CPU overall. Most process process is down to 1-3% CPU.

**Review by NickM-27 — APPROVED** [review]

**Comment by kdill00** [comment]
ooo this is hot right here.  im seeing a 50 percent reduction over every version of frigate ive used in the past and some issues with ram being gobbled up have stopped occurring.  Tracking is much smoother and bounding boxes seem more accurate.  Third time is a charm.  Default motion settings are really really sensitive though.  My card got close to temperature throttling within 2 minutes of starting frigate as it started processing 500 frames a second right off the bat.  Keep killing the game

**Comment by NickM-27** [comment]
> Default motion settings are really really sensitive though

it really depends on the camera, for most of mine they are basically perfect with the defaults.

**Comment by kdill00** [comment]
> > Default motion settings are really really sensitive though
> 
> it really depends on the camera, for most of mine they are basically perfect with the defaults.

Yeah. These cameras are in a bright environment with changing lights in different areas. I really like this lightning setting.  Seems to be pretty effective.

**Comment by kirsch33** [comment]
my CPU usage has fallen off a cliff with this PR, pretty cool

**Pull request merged**
