### PR TITLE
Cleanup and organize utils

### PR DESCRIPTION
**Pull request by NickM-27**
The util class was getting a bit unwieldy, I think it is good to organize the utils at this point

### CODE REVIEW

**Comment by skrashevich** [comment]
maybe, simplify this by use https://github.com/scientific-python/lazy_loader ?

**Comment by NickM-27** [comment]
> maybe, simplify this by use https://github.com/scientific-python/lazy_loader ?

Thanks, that is cleaner and eliminates needing to guess which sub module something is in

**Comment by skrashevich** [comment]
> actually, this doesn't work the way I thought it did. And as far as I can tell it breaks the code completion / type checking in vscode

can you provide an example?

**Comment by NickM-27** [comment]
> > actually, this doesn't work the way I thought it did. And as far as I can tell it breaks the code completion / type checking in vscode
> 
> can you provide an example?

As this PR is now vscode recognizes the function and ctrl + clicking it opens that function, also will warn if incorrect parameters are supplied to the function

Screen Shot 2023-07-05 at 16 13 28 PM

When trying to use lazy loading based on their readme, it does not recognize the functions. 

```
import frigate.util as util
```

Screen Shot 2023-07-05 at 16 14 39 PM

It is possible it could be some cache thing or something but I did restart vscode and also ran frigate. Frigate worked as expected but the issue above remained.

**Comment by skrashevich** [comment]
Are you sure you didn't forget to create appropriate .pyi files?

**Comment by NickM-27** [comment]
> https://github.com/scientific-python/lazy_loader

Ah, I saw type checkers but figured that would just be for mypy, I now see that it also applies to IDEs which makes sense. I will try this later and I expect that it will most likely solve the issue

**Comment by NickM-27** [comment]
Okay it is working now but I am unsure this really makes things any simpler, it will now require adding each function that is added to any util in the __init__.pyi file:

```python
__all__ = ['EventsPerSecond', ' clean_camera_user_pass', ' deep_merge', ' escape_special_characters', ' get_ffmpeg_arg_list', ' get_tz_modifiers', ' load_config_with_no_duplicates', ' load_labels', ' to_relative_box']
from .builtin import EventsPerSecond, clean_camera_user_pass, deep_merge, escape_special_characters, get_ffmpeg_arg_list, get_tz_modifiers, load_config_with_no_duplicates, load_labels, to_relative_box
```

and you will still have to use `utils.builtin.to_relative_box()` for example which still requires knowledge of which module the function is in.

I think something like this may be worth doing in the future but this PR is meant to be a simple reorganization effort

**Comment by skrashevich** [comment]
maybe, something like:
```python
import inspect
import .builtin as builtin_module

__all__ = [name for name, obj in inspect.getmembers(builtin_module) if not name.startswith('_') and (inspect.isfunction(obj) or inspect.isclass(obj))]
````

**Comment by blakeblackshear** [comment]
Yea. I don't see enough of a benefit for automatic imports. Breaks the navigation in github too.

Just a few conflicts to resolve now.

**Review by blakeblackshear — APPROVED** [review]

**Pull request merged**
