### PR TITLE
[stats] Add units to y axis labels

### PR DESCRIPTION
**Pull request by xconverge**

### CODE REVIEW

**Comment by xconverge** [comment]
This totally doesn't work, sorry, I need to write a different formatter for stepSize or something, will update it quickly

**Comment by NickM-27** [comment]
Personally I think it looks cleaner without units, and the units show in the top so they are known. Maybe other maintainers will have a different opinion

Also on the % part we don't want the scale to always be 0-100 because then you lose the graph entirely when the % is low

**Comment by xconverge** [comment]
Just to add some context of what I am seeing on my system and why I think it could use a tweak, what does yours look like?

image

For me this is mostly just a "pretty graphs" screen that doesnt really tell me much, but I dont need to make tweaks to cater specifically to my weird/low resources used system

The other fixes were more important for my system, so I will play with it more once I have those deployed and give it a few days to settle in

**Comment by NickM-27** [comment]
Seems fine to me, I'm not sure why the unit itself would make that much of a difference

**Comment by xconverge** [comment]
👍

**Pull request closed without merging**
