### PR TITLE
minor modifications to allow running directly on osx

### PR DESCRIPTION
**Pull request by josephhajduk**
Seeing some pretty great performance running the core directly on the mac so figured I would share my changes.  Can get 16 cpu detectors running at 30-40ms on my M1 pro, and allows ffmpeg to use hardware decoding.

I changed the camera metrics to only store the pid for the processes as that was all that was used. This is to work with spawn rather than fork (spawn is default on osx, and opencv was losing it's mind with fork for me)

ftruncate on osx doesn't always truncate as you would expect so I made a small change to ffmpeg buffer buffer

I added a check to ignore /dev/shm in stats on darwin

### CODE REVIEW

**Comment by NickM-27** [comment]
What does your docker config look like to pass the iGPU in for hardware decode?

Also, can you please elaborate which changes are required for what? I contribute to frigate running on a 14" mac M1 Pro and haven't seen any issues so just curious.

**Comment by josephhajduk** [comment]
I don't think its possible to pass the iGPU, these changes allow the core to run directly on the mac.  I installed apple's tensorflow and opencv with conda, along with all the other python reqs.  I use the docker container for everything else and point the frigate api back out to the host with  the following change to the nginx config.

```
upstream frigate_api {
      server host.docker.internal:5001;
      keepalive 1024;
    }
```

I commented out the usb stuff and the port 5001 assignment from the docker-compose.

Some obvious changes are required in const.py aswell.

As per the changes in the PR...

The changes in app.py, stats.py, and types.py is because Process can't be pickled and pythons multiprocessing on osx defaults to spawn rather than fork.    If you configure it to use fork, opencv seg faults for whatever reason.  I plan on investigating this further.  Regardless, only the pid is used from the Process anyways.

The changes in video.py is because on osx the framebuffer is sometimes larger than what you request, so the lhs isn't always the same size as the rhs.   ```frame_buffer[:frame_size]``` on the lhs fixes the issue.

The change in edgetpu.py is just a conditional import to use full tensor flow, as I don't believe there is a apple silicon version of tflite.

**Comment by NickM-27** [comment]
Oh okay I understand now, in that case will probably want to double check with @blakeblackshear but I believe we're not looking to support non-docker installs at this time.

**Comment by josephhajduk** [comment]
all good,  the performance boost is pretty huge though.  none of these changes should effect normal docker setups.

**Comment by NickM-27** [comment]
> all good,  the performance boost is pretty huge though.  none of these changes should effect normal docker setups.

If it's a demonstrable performance boost for docker setup that's a difference story, but (under the assumption) that docker is the only supported setup, I don't think we're looking to make changes that accommodate bare metal setups. Blake will confirm 👍

**Comment by josephhajduk** [comment]
just fyi with this config 
```
mqtt:
  host: 127.0.0.1

model:
  path: /Users/josephhajduk/IdeaProjects/frigate/cpu_model.tflite
  labelmap_path: /Users/josephhajduk/IdeaProjects/frigate/labelmap.txt

database:
  path: /Users/josephhajduk/IdeaProjects/frigate/media/frigate.db

cameras:
  test1:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:02:00
          roles:
            - snapshots
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test2:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:20:00
          roles:
            - snapshots
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test3:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:50:00
          roles:
            - snapshots
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test4:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:33:00
          roles:
            - snapshots
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test5:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:12:00
          roles:
            - snapshots
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test6:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:23:00
          roles:
            - snapshots
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test7:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:30:00
          roles:
            - snapshots
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test8:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:33:00
          roles:
            - snapshots
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test9:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:03:00
          roles:
            - clips
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test10:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:24:00
          roles:
            - clips
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test11:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:55:00
          roles:
            - clips
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test12:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:36:00
          roles:
            - clips
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test13:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:19:00
          roles:
            - clips
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test14:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:43:00
          roles:
            - clips
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test15:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:39:00
          roles:
            - clips
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5
  test16:
    ffmpeg:
      inputs:
        - path: /Users/josephhajduk/IdeaProjects/frigate/debug/test.mp4
          input_args: -re -fflags +genpts -ss 00:53:00
          roles:
            - clips
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - videotoolbox
    rtmp:
      enabled: False
    detect:
      enabled: True
      height: 960
      width: 1920
      fps: 5

detectors:
  cpu1:
    type: cpu
    num_threads: 1
  cpu2:
    type: cpu
    num_threads: 1
  cpu3:
    type: cpu
    num_threads: 1
  cpu4:
    type: cpu
    num_threads: 1
  cpu5:
    type: cpu
    num_threads: 1
  cpu6:
    type: cpu
    num_threads: 1
  cpu7:
    type: cpu
    num_threads: 1
  cpu8:
    type: cpu
    num_threads: 1
  cpu9:
    type: cpu
    num_threads: 1
  cpu10:
    type: cpu
    num_threads: 1
  cpu11:
    type: cpu
    num_threads: 1
  cpu12:
    type: cpu
    num_threads: 1
  cpu13:
    type: cpu
    num_threads: 1
  cpu14:
    type: cpu
    num_threads: 1
  cpu15:
    type: cpu
    num_threads: 1
  cpu16:
    type: cpu
    num_threads: 1
```

with this video (a recent feature film with lots of panning at a high bitrate, way worse than typical surveillance footage)
```
ffmpeg -i test.mp4
ffmpeg version 5.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.67.100
  Duration: 02:17:17.89, start: 0.000000, bitrate: 2638 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x960 [SAR 1:1 DAR 2:1], 2248 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 384 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
```

I am getting these numbers and the laptop is still usable (about 65% cpu on a m1 max mbp)
Screenshot 2022-08-21 at 00-00-14 Frigate

**Comment by skynet01** [comment]
Any guide on how you got this running? I have a mac mini m1 and i would love to run in on bare metal without docker. With docker I have an okish inference it spikes a lot (allocating 3 cpu's with 3 threads each, with 8 cameras). Two cameras are pointing outside that have a lot of movement.

Screen Shot 2022-09-12 at 10 14 25 PM

I even have a coral USB stick but you can't pass it to the docker container if it's running on a mac. If I pass it through parallels Coral keeps crashing every 30 seconds or so. 

Would be nice to have an option to run it directly.

**Comment by josephhajduk** [comment]
I started with https://developer.apple.com/metal/tensorflow-plugin/, I also installed opencv with conda, then installed the missing python dependencies.   I left everything other than the python frigate api in the docker container and ran it as normal but modified the nginx config as noted above.

**Comment by skynet01** [comment]
```I left everything other than the python frigate api in the docker container and ran it as normal but modified the nginx config as noted above.```

I get everything else, but how did you split this up? :)

**Comment by josephhajduk** [comment]
I didn't actually remove the frigate api from the docker container.   I shell into the docker container and change the nginx.conf to look like this
```
daemon off;
user root;
worker_processes  1;

error_log  /usr/local/nginx/logs/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /usr/local/nginx/logs/access.log  main;

    sendfile        on;

    keepalive_timeout  65;

    gzip on;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/x-javascript application/javascript text/javascript image/svg+xml image/x-icon image/bmp image/png image/gif image/jpeg image/jpg;
    gzip_proxied no-cache no-store private expired auth;
    gzip_vary on;

    upstream frigate_api {
      server host.docker.internal:5001;
      keepalive 1024;
    }

    upstream mqtt_ws {
      server host.docker.internal:5002;
      keepalive 1024;
    }

    upstream jsmpeg {
      server host.docker.internal:8082;
      keepalive 1024;
    }

    server {
        listen 5000;

        # vod settings
        vod_base_url '';
        vod_segments_base_url '';
        vod_mode mapped;
        vod_max_mapping_response_size 1m;
        vod_upstream_location /api;
        vod_align_segments_to_key_frames on;
        vod_manifest_segment_durations_mode accurate;

        # vod caches
        vod_metadata_cache metadata_cache 512m;
        vod_mapping_cache mapping_cache 5m 10m;

        # gzip manifests
        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        # file handle caching / aio
        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;
        aio on;

        location /vod/ {
            vod hls;

            secure_token $args;
			secure_token_types application/vnd.apple.mpegurl;

            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires -1;
        }

        location /stream/ {
            add_header 'Cache-Control' 'no-cache';
            add_header 'Access-Control-Allow-Origin' "$http_origin" always;
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Expose-Headers' 'Content-Length';
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' "$http_origin";
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            types {
                application/dash+xml mpd;
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
                image/jpeg jpg;
            }

            root /tmp;
        }

        location /clips/ {
            add_header 'Access-Control-Allow-Origin' "$http_origin" always;
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Expose-Headers' 'Content-Length';
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' "$http_origin";
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            types {
                video/mp4 mp4;
                image/jpeg jpg;
            }

            autoindex on;
            root /media/frigate;
        }

        location /cache/ {
                internal; # This tells nginx it's not accessible from the outside
                alias /tmp/cache/;
        }

        location /recordings/ {
            add_header 'Access-Control-Allow-Origin' "$http_origin" always;
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Expose-Headers' 'Content-Length';
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' "$http_origin";
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            types {
                video/mp4 mp4;
            }

            autoindex on;
            autoindex_format json;
            root /media/frigate;
        }

        location /ws {
            proxy_pass http://mqtt_ws/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        location /live/ {
            proxy_pass http://jsmpeg/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        location /api/ {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
            add_header Cache-Control "no-store";
            proxy_pass http://frigate_api/;
            proxy_pass_request_headers on;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        location / {
            add_header Cache-Control "no-cache";

            location ~* \.(?:js|css|svg|ico|png)$ {
                access_log off;
                expires 1y;
                add_header Cache-Control "public";
            }

            sub_filter 'href="/' 'href="$http_x_ingress_path/';
            sub_filter 'url(/' 'url($http_x_ingress_path/';
            sub_filter '"/dist/' '"$http_x_ingress_path/dist/';
            sub_filter '"/js/' '"$http_x_ingress_path/js/';
            sub_filter '<body>' '<body><script>window.baseUrl="$http_x_ingress_path";</script>';
            sub_filter_types text/css application/javascript;
            sub_filter_once off;

            root /opt/frigate/web;
            try_files $uri $uri/ /index.html;
        }
    }
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;
        allow publish 127.0.0.1;
        allow publish all;
        allow play all;
        application live {
            live on;
            record off;
            meta copy;
        }
    }
}
```

**Comment by t0mtaylor** [comment]
Why wasnt this merged @NickM-27  ? This is useful for now until Docker on MacOS has better GPU support, and would be good to see these changes in the latest release of Frigate

**Comment by NickM-27** [comment]
@t0mtaylor because like was explained above frigate is only supported to be run in docker, it is not supported to be run on bare metal.

**Comment by jasontitus** [comment]
I just spent some time on this path as well.  I understand the desire to only support docker but it seems like there will be growing interest in mac mini's as frigate servers and docker doesn't cut it (no hwaccel for video or onnx models).  It seems like the changes shouldn't be huge - managing the paths (config and such which are all hard coded - which seems to be a fine set of changes) and then just dealing with the multiprocessing changes and a conda environment for dependency and version management.  Should we just do it on a macfrigate fork or something?

**Comment by jasontitus** [comment]
Or I suppose the lowest impact we would be to bridge the ffmpeg and frame detection to processes outside of the docker container that could be using native libraries.

**Comment by angsanley** [comment]
> I just spent some time on this path as well. I understand the desire to only support docker but it seems like there will be growing interest in mac mini's as frigate servers and docker doesn't cut it (no hwaccel for video or onnx models). It seems like the changes shouldn't be huge - managing the paths (config and such which are all hard coded - which seems to be a fine set of changes) and then just dealing with the multiprocessing changes and a conda environment for dependency and version management. Should we just do it on a macfrigate fork or something?

Hey! I’m just getting started on running Frigate natively on macOS as well. Do you mind sharing your tips on dealing with the changes you mentioned? That would be super helpful!

Also, maybe a fork is a great idea to make this happen more smoothly. Let me know how I could help out with that!

**Pull request closed without merging**
