### PR TITLE
Add prometheus metrics - Redo 

### PR DESCRIPTION
**Pull request by mitchross**
Redo of -> https://github.com/blakeblackshear/frigate/pull/5594
Addresses https://github.com/blakeblackshear/frigate/issues/2266

## Proposed change
This PR adds comprehensive Prometheus metrics support to Frigate, enabling better monitoring and observability of the system. The integration:

- Exposes a `/metrics` endpoint in Prometheus format
- Leverages existing stats collection system
- Provides detailed metrics for:
  - Camera performance (FPS, detection rates)
  - System resources (CPU, memory, GPU usage)
  - Storage utilization
  - Detection performance
  - Service health metrics
  - Temperature monitoring

This will allow users to:
- Monitor Frigate performance using industry-standard tools
- Create custom dashboards in Grafana
- Set up alerts based on metrics
- Track long-term performance trends

The implementation piggybacks on the existing stats collection system, ensuring minimal overhead while providing valuable monitoring capabilities.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code
- [ ] Documentation Update

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Ruff (`ruff format frigate`)

Additional Notes:
- The implementation uses the official prometheus_client library
- Metrics follow Prometheus naming conventions
- No breaking changes to existing functionality
- Minimal performance impact as it uses existing stats collection
- All metrics are properly documented with descriptions
- Labels are used consistently for better querying

### CODE REVIEW

**Review by NickM-27 — APPROVED** [review]

**Comment by mitchross** [comment]
@NickM-27  how am I supposed to address the merge commit blocked issue?

**Comment by NickM-27** [comment]
This will need to target 0.16, I think it should be good to go now though once another maintainer can take a look

**Comment by mitchross** [comment]
> This will need to target 0.16, I think it should be good to go now though once another maintainer can take a look

thank you!

**Comment by hawkeye217** [comment]
Looks like the merge with the 0.16 branch brought in more changes than the original PR. The only thing I'd like to see is at least a mention somewhere in the docs for the new functionality/capabilities that this PR offers.

**Comment by mitchross** [comment]
> Looks like the merge with the 0.16 branch brought in more changes than the original PR. The only thing I'd like to see is at least a mention somewhere in the docs for the new functionality/capabilities that this PR offers.

Ok I added docs.. Not sure how many files i should check in for docs. I ran it locally, it had a ton of docs changed.. let me know if Im supposed to check all the newly generated files in?

**Comment by hawkeye217** [comment]
> > Looks like the merge with the 0.16 branch brought in more changes than the original PR. The only thing I'd like to see is at least a mention somewhere in the docs for the new functionality/capabilities that this PR offers.
> 
> Ok I added docs.. Not sure how many files i should check in for docs. I ran it locally, it had a ton of docs changed.. let me know if Im supposed to check all the newly generated files in?

I'd drop this under the Integrations sidebar entries under MQTT rather than Configuration. Otherwise, looks good.

**Comment by blakeblackshear** [comment]
Generally you are going to be better off rebasing your work on the 0.16 branch. That will get rid of the extra unrelated changes so the PR is cleaner.

**Comment by mitchross** [comment]
redoing on new branch -> https://github.com/blakeblackshear/frigate/pull/15521

**Pull request closed without merging**
