### PR TITLE
Move event-view to events table.

### LINKED ISSUE #1465: Feature Request - Retain Scroll Position on Events List
**Feature Request**
Retain the scroll position when using the browser back button to return from an event detail to the events list.

Whenever I am viewing events in the list, I will click the event to view the clip.  Unfortunately there is no way to navigate back to the events list without loosing the position on the 'timeline' of events from which you clicked.  It'd be nice when using the back button for the events screen to remember the last scroll position.

**Version of frigate**
1.13

### PR DESCRIPTION
**Pull request by sinamics**
Event viewer will open below the table row when clicking the image instead of opening new page. 
This will also resolve #1465 #1594 as the scroll position will not change. 

Brief overview:
- New event table row is open when clicking the event image. 
- It will automatically scroll the event into view.
- Scaled down the videoplayer, but ratio is maintained.
- Removed event details as its already in the events table.
- Moved the delete reducer from api to Events.js
- Added fixed position for the delete Dialog.
- Removed Event route.

Tested on Chrome, Firefox, Edge with 1000+ events.

**Note!**
Im currently trying to trace down some performance issue. When i scroll down large amount of events (700+), i notice the browser get slugish. This is also noticable in 0.9.0 without this mod, and probably 0.8.4 (not tested), but it became more noticable now as the event view is loaded from the same page events.js. 

Im not sure if this is only related to docker dev? I will update when i get more info.

event_view

### CODE REVIEW

**Comment by blakeblackshear** [comment]
Can we use the X icon for the Close button rather than the stacked bars? Also, lets move the close button to the right of the delete button.

**Comment by Sinamics** [comment]
Done. Moved button and added new close svg X

**Comment by blakeblackshear** [comment]
@Sinamics this looks good to me. unless you feel like there is a major regression in performance, I would like to merge this as is.

**Comment by Sinamics** [comment]
I will do some performance testing today and try to trace the issue, there might be some sort of memory leak somewhere.
I know some other people has complained about the events page been slow, and this could be related to that.

I`ll get back to you with my findings.

**Comment by jasonpstokes** [comment]
This is a good improvement, but a couple things for feedback:
1. In the desktop browser it appears to size the view for a 16:9 frame, before expanding the height for a 4:3 frame (which all my cameras are) - so the view only *just* fits on the screen. I can see all of the clip, it just feels cramped. :-)

This displays for a second (16:9):

image

Then this (4:3):

image

2. In the mobile view, on my Pixel 3 at least, it doesn't really work at all; can the video be left aligned in this view, and scaled to fit the width of the screen?

image

image

image

**Comment by Sinamics** [comment]
@jasonpstokes Thx for the feedback. Will look into this

**Comment by jasonpstokes** [comment]
Thanks for looking into it. Happy to help test if you do make changes.

**Comment by Sinamics** [comment]
> 1. In the desktop browser it appears to size the view for a 16:9 frame, before expanding the height for a 4:3 frame (which all my cameras are) - so the view only _just_ fits on the screen. I can see all of the clip, it just feels cramped. :-)

Videoplayer tries to scale the window upload loading (fluid), and will expand to the video ratio once loaded as you stated. Loading state will show the snapshot (poster image) before the video is fetched, hence the diffrent ratio for a split second. 
It might be better to only show the snapshot and not fetch video before play button is pressed, this will eliminate the flickering.

Videocontainer has a max-width of 60% and doubletapping the video will expand to fullsize window. This allows us to see all information in the window and let the user deside if the player should be opened in full view. I can make it larger so it wont feel that cramped for 4/3. 

> In the mobile view, on my Pixel 3 at least, it doesn't really work at all; can the video be left aligned in this view, and scaled to fit the width of the screen?

I will scale it up for mobile devices and make the UI better.

**Comment by jasonpstokes** [comment]
@Sinamics, hope I'm not out of line asking this: would some of what you've done for the events table also work for the main and/or recording views please?

Main view frame scaling for 4:3 video, as per #1557 or my dupe post #1642 (for screenshots).

The event clip selector in the recordings view on mobile is very small/could show a lot more.

Screenshot_20210904-152800_540

e.g. for a split second when the page loads it does fit the height of the screen, before resizing to fit within the clip:

Screenshot_20210904-152833_432

**Comment by Sinamics** [comment]
@jasonpstokes I can surely have a look and see if i can improve things to the better.

**Comment by jasonpstokes** [comment]
Hey @Sinamics hope you're doing well. Having used this for a few weeks now I have some more feedback for consideration/discussion. Sadly I don't have any programming skills to assist with this though - only just enough Photoshop skills to create some more mockups! :-)

Because the events table has multiple columns that are too wide for a mobile screen, causing horizontal scrolling, the video clip frame still overflows off the screen. So I personally prefer the Clips UI from 0.8.4, in that the clip info/clip video/best image all fit to the width of the screen (i.e. no horizontal scrolling). So although I like the idea of inline clips in 0.9.x, the UI in 0.8.4 "feels" neater/more ordered. (At least for me!)

So what if we made the table double height? This would allow a bigger clip image (easier to see the object) and for the clip's info to display over multiple lines that can be read in one go, rather than scrolling horizonatally. e.g.

image

IMO this might also be neater/easier to read on desktop screens too, as the current table is huge but does not display much!

image


Tapping the event would load the Clip and Best Image inline in a view similar to 0.8.4, e.g.

image

As the event details are already clearly viewable in the table, we don't need them again. 
Using icons for the Download buttons (in-line with the title) instead of text buttons saves that realestate, and I don't think we need a close button if we can just keep scrolling anyway. (Or if we want to close it, we can tap on the table image again, like we did to open it).

e.g the table continues below Best Image:

image

Hope this makes sense - what do you think?

**Comment by Sinamics** [comment]
@jasonpstokes I have been super busy with other project last weeks.  
It did make sense when reading through your comments, but i would need to spinn up the dev server to get better understanding. I will post a comment when i have looked into it, hopefully during the weekend.

**Comment by jasonpstokes** [comment]
No probs @Sinamics, totally understand!

@blakeblackshear keen too for any feedback you may have on the proposed events table re-design above, given you're the owner and all. :-)

**Comment by blakeblackshear** [comment]
It does look nicer. I do think that the events viewer and the recordings will be merged together anyway.

**Pull request merged**
