### PR TITLE
Add FAQ to explain why streams might work in VLC but not in Frigate

### PR DESCRIPTION
**Pull request by hawkeye217**
## Proposed change

Users often leave comments saying "my URL works fine when I put it in VLC but it doesn't work in Frigate, this must be a Frigate bug". This PR updates the docs with the primary reason why this occurs.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code
- [x] Documentation Update

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Ruff (`ruff format frigate`)

### CODE REVIEW

**Review by NickM-27 — COMMENTED** [review]
I'd also mention how vlc streams live but does not process the streams / does not have a requirement for a constant consistent stream

**Comment by hawkeye217** [comment]
> I'd also mention how vlc streams live but does not process the streams / does not have a requirement for a constant consistent stream

Good point, updated

**Comment by NickM-27** [comment]
Sorry but I just thought it might be good to mention that UDP can be configured with an input arg

**Comment by hawkeye217** [comment]
> Sorry but I just thought it might be good to mention that UDP can be configured with an input arg

All good. Good idea

**Review by NickM-27 — APPROVED** [review]

**Pull request merged**
