### PR TITLE
[Feature] Add timepicker to calendar

### PR DESCRIPTION
**Pull request by sinamics**
This is a continuation of #3302 and implementation of #3140
It was quite a hassle to get it right, but i think im almost there.

Main goal was to have one single list of hours, instead of two boxes with "after" and "before".
The list expands with the selected days in calendar. Each day has a slightly different gray toned background.

- If the selected days in calendar is > 1, the after must be in day 1 and before in last day.
- Last selected time must be greater than the first.

User will get a error message in the top if these condition is not met.

Remaining items:

- [x] make it more stylish
- [x] needs more comprehensive testing to make sure there is no unwanted side-effects

image

### CODE REVIEW

**Comment by sinamics** [comment]
- improved styles
- hidden on mobile devices for now. 
- updated calendar to accommodate the new after and before times.
- scrolls selected times into view

gif

**Comment by sinamics** [comment]
So i have tested quite a bit, and seems to work ok. 
It would be beneficial to have someone else test and provide feedback on the usefulness of this, as well as any potential issues.

**Comment by NickM-27** [comment]
@sinamics Can you please resolve the conflicts here?

**Comment by sinamics** [comment]
> @sinamics Can you please resolve the conflicts here?

sure can do.

**Review by NickM-27 — APPROVED** [review]

**Comment by NickM-27** [comment]
@sinamics I am going to do more looking into it but wanted to double check if this was tested after the rebase? I am not seeing the time picker next to the calendar (also not seeing any errors)

**Comment by dominikjas** [comment]
Hey,

This looks very handy and we would like to use it! Is there an approximate time when this will be included in the stable version?

Or is there a safe way to use it now? I tried it once with the last dev version, but the time picker was not visible there.

**Comment by sinamics** [comment]
its available in the dev builds if you want to test it out now.
https://github.com/blakeblackshear/frigate/pkgs/container/frigate

**Comment by dominikjas** [comment]
Mhm I won't get timepicker when I'm using this image "ghcr.io/blakeblackshear/frigate:dev-2d52fbd" :-/

This is my docker compose:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:dev-2d52fbd
    shm_size: "8gb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/volumes/frigate_config/_data/:/config/
      - /var/lib/docker/volumes/frigate_storage/_data:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "***"
```

and this is my frigate config:
```
mqtt:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: usb
#    model:
#      path: "/custom_model.tflite"
#  cpu1:
#    type: cpu
#    num_threads: 8

record:
  enabled: True
  retain:
    days: 30
    mode: active_objects
  events:
    pre_capture: 3
    post_capture: 3

snapshots:
  enabled: True
  clean_copy: True
  bounding_box: True

birdseye:
  enabled: false
  mode: continuous
  quality: 1

logger:
  default: info
  logs:
    frigate.event: debug

cameras:
  CAM07:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@***.***.***.***/h264Preview_01_main
          roles:
           - detect
           - record
    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
        - bus
    detect:
      width: 4608 # <---- update for your camera's resolution
      height: 1728 # <---- update for your camera's resolution
```

Did I miss something?

**Comment by NickM-27** [comment]
where are you looking for the time picker to be?

**Comment by dominikjas** [comment]
Thanks for the fast responses!
Here:
image

**Comment by NickM-27** [comment]
that is where it is, you press the calendar -> custom -> and then you see the time picker

Screen Shot 2023-07-13 at 15 07 46 PM

**Comment by dominikjas** [comment]
Still not there :-/

image
image

**Comment by sinamics** [comment]
@dominikjas can you goto system page, and make sure you have the dev build.

**Comment by NickM-27** [comment]
Also make sure you clear the cache on the browser as it may just not be loading the new frontend

**Comment by dominikjas** [comment]
Okay there seems to be another problem and as you already I expected the stable version was still loaded:

ERROR   : Migration failed: 014_event_updates_for_fp

The container has crasehd now too. Can you also help me with this ?

**Comment by NickM-27** [comment]
if you have changed between versions you likely have a corrupt DB

**Comment by dominikjas** [comment]
Oh okay good to know thank you very much! I just stopped my container, renamed the db to frigate_old.db, restarted the container and the timepicker works now:

 
image

Are there any plans to get this timepicker in the frigate hass-card plugin too?

**Comment by NickM-27** [comment]
> Are there any plans to get this timepicker in the frigate hass-card plugin too?

The frigate hass card is developed by another developer, and I believe it already supports features like the timpicker, timeline, etc.

**Comment by dominikjas** [comment]
Yes it has this timeline view but this was with a bigger amount of events a bit laggy on our home assistant. Would be nice to have it here: 

image


But well, this probably doesn't belong in this thread. 

Thank you again for the quick support!

**Pull request merged**
