### PR TITLE
Make tracker initialization configurable

### PR DESCRIPTION
**Pull request by NickM-27**

### CODE REVIEW

**Review by blakeblackshear — APPROVED** [review]

**Comment by kirsch33** [comment]
Can you offer some guidance on what situations would warrant changing this value? Or maybe just what you have noticed that lead to this PR? Very interested

**Comment by NickM-27** [comment]
I had a false positive package from the bench on my doorbell camera. The event was starting and ending within 1 second.  I didn't want to increase the detect fps but I wanted to give this camera more time to verify the detections are valid before tracking them.

**Comment by giantorth** [comment]
Pulled latest dev container and got this in my boot logs, is this a required config value now?
```
2023-10-31 16:09:49.674175480  Process camera_processor:front_yard:
2023-10-31 16:09:49.675341114  Traceback (most recent call last):
2023-10-31 16:09:49.675344309    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-31 16:09:49.675349471      self.run()
2023-10-31 16:09:49.675352374    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-31 16:09:49.675354581      self._target(*self._args, **self._kwargs)
2023-10-31 16:09:49.675356428    File "/opt/frigate/frigate/video.py", line 431, in track_camera
2023-10-31 16:09:49.675371802      object_tracker = NorfairTracker(config, ptz_metrics)
2023-10-31 16:09:49.675388574    File "/opt/frigate/frigate/track/norfair_tracker.py", line 83, in __init__
2023-10-31 16:09:49.675390257      initialization_delay=self.detect_config.min_initialized,
2023-10-31 16:09:49.675391811  AttributeError: 'DetectConfig' object has no attribute 'min_initialized'
2023-10-31 16:09:49.681343530  Process camera_processor:flood_light:
2023-10-31 16:09:49.682447335  Traceback (most recent call last):
2023-10-31 16:09:49.682494974    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-31 16:09:49.682497069      self.run()
2023-10-31 16:09:49.682520264    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-31 16:09:49.682522117      self._target(*self._args, **self._kwargs)
2023-10-31 16:09:49.682538542    File "/opt/frigate/frigate/video.py", line 431, in track_camera
2023-10-31 16:09:49.682540229      object_tracker = NorfairTracker(config, ptz_metrics)
2023-10-31 16:09:49.682556559    File "/opt/frigate/frigate/track/norfair_tracker.py", line 83, in __init__
2023-10-31 16:09:49.682558241      initialization_delay=self.detect_config.min_initialized,
2023-10-31 16:09:49.682601696  AttributeError: 'DetectConfig' object has no attribute 'min_initialized'
2023-10-31 16:09:49.690662093  Process camera_processor:doorbell:
2023-10-31 16:09:49.691801296  Traceback (most recent call last):
2023-10-31 16:09:49.691851269    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-31 16:09:49.691853377      self.run()
2023-10-31 16:09:49.691874119    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-31 16:09:49.691875890      self._target(*self._args, **self._kwargs)
2023-10-31 16:09:49.691891368    File "/opt/frigate/frigate/video.py", line 431, in track_camera
2023-10-31 16:09:49.691892974      object_tracker = NorfairTracker(config, ptz_metrics)
2023-10-31 16:09:49.691909543    File "/opt/frigate/frigate/track/norfair_tracker.py", line 83, in __init__
2023-10-31 16:09:49.691911195      initialization_delay=self.detect_config.min_initialized,
2023-10-31 16:09:49.691958001  AttributeError: 'DetectConfig' object has no attribute 'min_initialized'
2023-10-31 16:09:49.696959442  Process camera_processor:back_yard:
2023-10-31 16:09:49.698090388  Traceback (most recent call last):
2023-10-31 16:09:49.698093625    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-31 16:09:49.698095093      self.run()
2023-10-31 16:09:49.698096806    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-31 16:09:49.698098336      self._target(*self._args, **self._kwargs)
2023-10-31 16:09:49.698123677    File "/opt/frigate/frigate/video.py", line 431, in track_camera
2023-10-31 16:09:49.698125419      object_tracker = NorfairTracker(config, ptz_metrics)
2023-10-31 16:09:49.698126940    File "/opt/frigate/frigate/track/norfair_tracker.py", line 83, in __init__
2023-10-31 16:09:49.698128361      initialization_delay=self.detect_config.min_initialized,
2023-10-31 16:09:49.698129834  AttributeError: 'DetectConfig' object has no attribute 'min_initialized'
2023-10-31 16:09:49.706431471  Process camera_processor:patio:
2023-10-31 16:09:49.707504822  Traceback (most recent call last):
2023-10-31 16:09:49.707557428    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-31 16:09:49.707559467      self.run()
2023-10-31 16:09:49.707578900    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-31 16:09:49.707580620      self._target(*self._args, **self._kwargs)
2023-10-31 16:09:49.707599701    File "/opt/frigate/frigate/video.py", line 431, in track_camera
2023-10-31 16:09:49.707601347      object_tracker = NorfairTracker(config, ptz_metrics)
2023-10-31 16:09:49.707618284    File "/opt/frigate/frigate/track/norfair_tracker.py", line 83, in __init__
2023-10-31 16:09:49.707619951      initialization_delay=self.detect_config.min_initialized,
2023-10-31 16:09:49.707665866  AttributeError: 'DetectConfig' object has no attribute 'min_initialized'
2023-10-31 16:09:49.714132059  Process camera_processor:side_yard:
2023-10-31 16:09:49.715249339  Traceback (most recent call last):
2023-10-31 16:09:49.715295794    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-31 16:09:49.715297919      self.run()
2023-10-31 16:09:49.715318353    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-31 16:09:49.715320096      self._target(*self._args, **self._kwargs)
2023-10-31 16:09:49.715337404    File "/opt/frigate/frigate/video.py", line 431, in track_camera
2023-10-31 16:09:49.715339001      object_tracker = NorfairTracker(config, ptz_metrics)
2023-10-31 16:09:49.715361181    File "/opt/frigate/frigate/track/norfair_tracker.py", line 83, in __init__
2023-10-31 16:09:49.715362871      initialization_delay=self.detect_config.min_initialized,
2023-10-31 16:09:49.715409225  AttributeError: 'DetectConfig' object has no attribute 'min_initialized'
```

**Comment by NickM-27** [comment]
That doesn't seem right, I only have this set on one of my cameras and I'm not getting any errors. What is your config?

**Comment by giantorth** [comment]
Scratch that, was my fault for not merging a couple branches correctly!

**Pull request merged**
