### PR TITLE
Event Datepicker

### LINKED ISSUE #1318: Feature Request - Allow date / month filtering in the gui
I am running frigate (great NVR btw) via docker and it has a dedicated share for its clips.

### Problem / issue

If I need to go back to a particular day / month to get a clip I am unable to filter the gui by month or day so have to resort to going straight to disk to find the incident I need.

it is then more of a challenge to find the clip without an image of the video itself.

it would be great to be able to select the day / month for frigate to load, as manually going back a month in the gui takes a good while to do.

Thanks for your consideration :)

### PR DESCRIPTION
**Pull request by sinamics**
Resolves #1318 #1366

This is a pretty large PR which adds Datepicker filter to the events page. 
I have not used any 3rd packages, hence the large changelog.

This PR will be tagged as draft as some items remains.

Rough changelog:
- New Datepicker.jsx file
- New Calender.jsx file with new arrow icons.
- Added Datepicker switch option to Select.jsx

Remaining items:
- ~~Update Select.test.jsx with new datatype used.  (This PR would most likely fail as it is)~~
- ~~General testing, make sure correct timezone is used ect.~~
- ~~Current layout does not fit well on small devices. Im open for suggestions~~
- ~~Improve keyboard navigation~~

Datepicker

### CODE REVIEW

**Comment by Sinamics** [comment]
hided filters on small devices and added a Filter button.

Datepicker

**Comment by mitchross** [comment]
@blakeblackshear  whats needed on this PR for merge? Testing? Code review? Let me know how I can help.

**Comment by blakeblackshear** [comment]
I haven't had time to review it yet.

**Comment by gururise** [comment]
If it helps, I tested this on my desktop browser and it seems to work just fine. Hoping to be able to use this feature in an upcoming (10.0?) release.

**Pull request merged**
