### PR TITLE
feat(web): add minimal Dialog component

### PR DESCRIPTION
**Pull request by paularmstrong**
For use with features like #858 

cc @ScottRoach

### CODE REVIEW

**Comment by mitchross** [comment]
on a similar note, I've been wanting to add a feature for sorting events based on a time frame. Is this planned already? do you have a preferred UI for handling this?

**Comment by mitchross** [comment]
@paularmstrong When do you think this will get merged?

**Comment by paularmstrong** [comment]
@mitchross Do you have a need for it, or can it wait and go in with #858?

**Comment by mitchross** [comment]
@paularmstrong It can wait, I just want to help contribute with development on frontend!

**Pull request closed without merging**
