### PR TITLE
Update detectors.md to detail MODEL_CACHE_DIR env var

### PR DESCRIPTION
**Pull request by SlothCroissant**
Resolves confusion in https://github.com/blakeblackshear/frigate/discussions/9025

### CODE REVIEW

**Comment by NickM-27** [comment]
You are trying to apply a 0.13 change to 0.12 docs which can not be accepted as this is not the case in 0.12.

**Comment by NickM-27** [comment]
some of the things added here in the docs also don't make sense when applied to the way that 0.13 works

**Comment by SlothCroissant** [comment]
> You are trying to apply a 0.13 change to 0.12 docs which can not be accepted as this is not the case in 0.12.

Oooo apologies, didn't even notice I was merging into Master - are there 0.13 docs on a branch I should target instead? or should we just pause this PR till later?

**Comment by NickM-27** [comment]
You can see the 0.13 docs at https://deploy-preview-6262--frigate-docs.netlify.app/configuration/object_detectors#generate-models which may clear up any confusion that you had

**Comment by SlothCroissant** [comment]
> some of the things added here in the docs also don't make sense when applied to the way that 0.13 works

I'd love to learn more here (as I'm working on getting tensorrt running in 0.13b7 now) - though we can close this out and leverage the discussion instead

**Pull request closed without merging**
