### PR TITLE
Updated Documentation: Autotracking add support details for Sunba 405-D20X 4K camera.

### PR DESCRIPTION
**Pull request by ltomes**
## Proposed change
I added some documentation details for my camera. 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code
- [x] Documentation

## Additional information

Camera configuration as pulled by `gonvif` (Let me know if you expect this camera to work with `autotracking`, and I will close this MR and open a discussion):

```
{
  "Profiles": [
    {
      "Name": "mainStream",
      "VideoSourceConfiguration": {
        "Name": "V_SRC_CFG_000",
        "UseCount": 3,
        "token": "V_SRC_000",
        "SourceToken": "V_SRC_000",
        "Bounds": {
          "x": 0,
          "y": 0,
          "width": 4096,
          "height": 2160
        }
      },
      "AudioSourceConfiguration": {
        "Name": "A_SRC_CFG_000",
        "UseCount": 2,
        "token": "A_SRC_CFG_000",
        "SourceToken": "AudioSourceToken"
      },
      "VideoEncoderConfiguration": {
        "Name": "V_ENC_000",
        "UseCount": 1,
        "token": "000",
        "Encoding": "H264",
        "Resolution": {
          "Width": 4096,
          "Height": 2160
        },
        "Quality": 3,
        "RateControl": {
          "FrameRateLimit": 17,
          "BitrateLimit": 3828
        },
        "H264": {
          "GovLength": 34,
          "H264Profile": "Main"
        },
        "Multicast": {
          "Address": {
            "Type": "IPv4",
            "IPv4Address": "239.0.1.0"
          },
          "Port": 32002,
          "TTL": 2
        },
        "SessionTimeout": "PT10S"
      },
      "AudioEncoderConfiguration": {
        "Name": "A_ENC_000",
        "UseCount": 2,
        "token": "A_ENC_000",
        "Encoding": "G711",
        "Bitrate": 128,
        "SampleRate": 8,
        "Multicast": {
          "Address": {
            "Type": "IPv4",
            "IPv4Address": "239.0.1.0"
          },
          "Port": 32002,
          "TTL": 2
        },
        "SessionTimeout": "PT10S"
      },
      "VideoAnalyticsConfiguration": {
        "Name": "VideoAnalytics",
        "UseCount": 3,
        "token": "AnalyticsToken_0",
        "AnalyticsEngineConfiguration": {
          "AnalyticsModule": [
            {
              "Parameters": {
                "SimpleItem": [
                  {
                    "Name": "Sensitivity",
                    "Value": "50"
                  }
                ],
                "ElementItem": [
                  {
                    "Name": "Layout"
                  }
                ]
              },
              "Name": "MyCellMotionModule",
              "Type": "tt:CellMotionEngine"
            },
            {
              "Parameters": {
                "SimpleItem": [
                  {
                    "Name": "Sensitivity",
                    "Value": "50"
                  }
                ],
                "ElementItem": [
                  {
                    "Name": "Transformation"
                  },
                  {
                    "Name": "Field"
                  }
                ]
              },
              "Name": "MyTamperDetecModule",
              "Type": "tt:TamperEngine"
            }
          ]
        },
        "RuleEngineConfiguration": {
          "Rule": [
            {
              "Parameters": {
                "SimpleItem": [
                  {
                    "Name": "MinCount",
                    "Value": "5"
                  },
                  {
                    "Name": "AlarmOnDelay",
                    "Value": "100"
                  },
                  {
                    "Name": "AlarmOffDelay",
                    "Value": "100"
                  },
                  {
                    "Name": "ActiveCells",
                    "Value": "0P8A8A=="
                  }
                ]
              },
              "Name": "MyMotionDetectorRule",
              "Type": "tt:CellMotionDetector"
            },
            {
              "Parameters": {
                "ElementItem": [
                  {
                    "Name": "Field"
                  }
                ]
              },
              "Name": "MyTamperDetectorRule",
              "Type": "tt:TamperDetector"
            }
          ]
        }
      },
      "PTZConfiguration": {
        "Name": "PTZConfiguration",
        "UseCount": 3,
        "token": "PTZConfigurationToken",
        "NodeToken": "NODE_000",
        "DefaultAbsolutePantTiltPositionSpace": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace",
        "DefaultAbsoluteZoomPositionSpace": "http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace",
        "DefaultRelativePanTiltTranslationSpace": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace",
        "DefaultRelativeZoomTranslationSpace": "http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace",
        "DefaultContinuousPanTiltVelocitySpace": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace",
        "DefaultContinuousZoomVelocitySpace": "http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace",
        "DefaultPTZSpeed": {
          "PanTilt": {
            "x": 0.5,
            "y": 0.5,
            "space": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace"
          },
          "Zoom": {
            "x": 0.5,
            "space": "http://www.onvif.org/ver10/tptz/ZoomSpaces/ZoomGenericSpeedSpace"
          }
        },
        "DefaultPTZTimeout": "PT5S",
        "PanTiltLimits": {
          "Range": {
            "URI": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace",
            "XRange": {
              "Min": -1,
              "Max": 1
            },
            "YRange": {
              "Min": -1,
              "Max": 1
            }
          }
        },
        "ZoomLimits": {
          "Range": {
            "URI": "http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace",
            "XRange": {
              "Min": 0,
              "Max": 1
            }
          }
        },
        "Extension": {
          "PTControlDirection": {
            "EFlip": {
              "Mode": "OFF"
            },
            "Reverse": {
              "Mode": "OFF"
            }
          }
        }
      },
      "Extension": {},
      "token": "000",
      "fixed": true
    },
    {
      "Name": "subStream",
      "VideoSourceConfiguration": {
        "Name": "V_SRC_CFG_000",
        "UseCount": 3,
        "token": "V_SRC_000",
        "SourceToken": "V_SRC_000",
        "Bounds": {
          "x": 0,
          "y": 0,
          "width": 4096,
          "height": 2160
        }
      },
      "AudioSourceConfiguration": {
        "Name": "A_SRC_CFG_000",
        "UseCount": 2,
        "token": "A_SRC_CFG_000",
        "SourceToken": "AudioSourceToken"
      },
      "VideoEncoderConfiguration": {
        "Name": "V_ENC_001",
        "UseCount": 1,
        "token": "001",
        "Encoding": "H264",
        "Resolution": {
          "Width": 800,
          "Height": 448
        },
        "Quality": 4,
        "RateControl": {
          "FrameRateLimit": 15,
          "BitrateLimit": 578
        },
        "H264": {
          "GovLength": 30,
          "H264Profile": "Main"
        },
        "Multicast": {
          "Address": {
            "Type": "IPv4",
            "IPv4Address": "239.0.1.0"
          },
          "Port": 32002,
          "TTL": 2
        },
        "SessionTimeout": "PT10S"
      },
      "AudioEncoderConfiguration": {
        "Name": "A_ENC_000",
        "UseCount": 2,
        "token": "A_ENC_000",
        "Encoding": "G711",
        "Bitrate": 128,
        "SampleRate": 8,
        "Multicast": {
          "Address": {
            "Type": "IPv4",
            "IPv4Address": "239.0.1.0"
          },
          "Port": 32002,
          "TTL": 2
        },
        "SessionTimeout": "PT10S"
      },
      "VideoAnalyticsConfiguration": {
        "Name": "VideoAnalytics",
        "UseCount": 3,
        "token": "AnalyticsToken_0",
        "AnalyticsEngineConfiguration": {
          "AnalyticsModule": [
            {
              "Parameters": {
                "SimpleItem": [
                  {
                    "Name": "Sensitivity",
                    "Value": "50"
                  }
                ],
                "ElementItem": [
                  {
                    "Name": "Layout"
                  }
                ]
              },
              "Name": "MyCellMotionModule",
              "Type": "tt:CellMotionEngine"
            },
            {
              "Parameters": {
                "SimpleItem": [
                  {
                    "Name": "Sensitivity",
                    "Value": "50"
                  }
                ],
                "ElementItem": [
                  {
                    "Name": "Transformation"
                  },
                  {
                    "Name": "Field"
                  }
                ]
              },
              "Name": "MyTamperDetecModule",
              "Type": "tt:TamperEngine"
            }
          ]
        },
        "RuleEngineConfiguration": {
          "Rule": [
            {
              "Parameters": {
                "SimpleItem": [
                  {
                    "Name": "MinCount",
                    "Value": "5"
                  },
                  {
                    "Name": "AlarmOnDelay",
                    "Value": "100"
                  },
                  {
                    "Name": "AlarmOffDelay",
                    "Value": "100"
                  },
                  {
                    "Name": "ActiveCells",
                    "Value": "0P8A8A=="
                  }
                ]
              },
              "Name": "MyMotionDetectorRule",
              "Type": "tt:CellMotionDetector"
            },
            {
              "Parameters": {
                "ElementItem": [
                  {
                    "Name": "Field"
                  }
                ]
              },
              "Name": "MyTamperDetectorRule",
              "Type": "tt:TamperDetector"
            }
          ]
        }
      },
      "PTZConfiguration": {
        "Name": "PTZConfiguration",
        "UseCount": 3,
        "token": "PTZConfigurationToken",
        "NodeToken": "NODE_000",
        "DefaultAbsolutePantTiltPositionSpace": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace",
        "DefaultAbsoluteZoomPositionSpace": "http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace",
        "DefaultRelativePanTiltTranslationSpace": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace",
        "DefaultRelativeZoomTranslationSpace": "http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace",
        "DefaultContinuousPanTiltVelocitySpace": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace",
        "DefaultContinuousZoomVelocitySpace": "http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace",
        "DefaultPTZSpeed": {
          "PanTilt": {
            "x": 0.5,
            "y": 0.5,
            "space": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace"
          },
          "Zoom": {
            "x": 0.5,
            "space": "http://www.onvif.org/ver10/tptz/ZoomSpaces/ZoomGenericSpeedSpace"
          }
        },
        "DefaultPTZTimeout": "PT5S",
        "PanTiltLimits": {
          "Range": {
            "URI": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace",
            "XRange": {
              "Min": -1,
              "Max": 1
            },
            "YRange": {
              "Min": -1,
              "Max": 1
            }
          }
        },
        "ZoomLimits": {
          "Range": {
            "URI": "http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace",
            "XRange": {
              "Min": 0,
              "Max": 1
            }
          }
        },
        "Extension": {
          "PTControlDirection": {
            "EFlip": {
              "Mode": "OFF"
            },
            "Reverse": {
              "Mode": "OFF"
            }
          }
        }
      },
      "Extension": {},
      "token": "001",
      "fixed": true
    },
    {
      "Name": "snapStream",
      "VideoSourceConfiguration": {
        "Name": "V_SRC_CFG_000",
        "UseCount": 3,
        "token": "V_SRC_000",
        "SourceToken": "V_SRC_000",
        "Bounds": {
          "x": 0,
          "y": 0,
          "width": 4096,
          "height": 2160
        }
      },
      "VideoEncoderConfiguration": {
        "Name": "V_ENC_002",
        "UseCount": 1,
        "token": "002",
        "Encoding": "JPEG",
        "Resolution": {
          "Width": 704,
          "Height": 480
        },
        "Quality": 4,
        "RateControl": {
          "FrameRateLimit": 1,
          "BitrateLimit": 512
        },
        "Multicast": {
          "Address": {
            "Type": "IPv4",
            "IPv4Address": "239.0.1.0"
          },
          "Port": 32002,
          "TTL": 2
        },
        "SessionTimeout": "PT10S"
      },
      "VideoAnalyticsConfiguration": {
        "Name": "VideoAnalytics",
        "UseCount": 3,
        "token": "AnalyticsToken_0",
        "AnalyticsEngineConfiguration": {
          "AnalyticsModule": [
            {
              "Parameters": {
                "SimpleItem": [
                  {
                    "Name": "Sensitivity",
                    "Value": "50"
                  }
                ],
                "ElementItem": [
                  {
                    "Name": "Layout"
                  }
                ]
              },
              "Name": "MyCellMotionModule",
              "Type": "tt:CellMotionEngine"
            },
            {
              "Parameters": {
                "SimpleItem": [
                  {
                    "Name": "Sensitivity",
                    "Value": "50"
                  }
                ],
                "ElementItem": [
                  {
                    "Name": "Transformation"
                  },
                  {
                    "Name": "Field"
                  }
                ]
              },
              "Name": "MyTamperDetecModule",
              "Type": "tt:TamperEngine"
            }
          ]
        },
        "RuleEngineConfiguration": {
          "Rule": [
            {
              "Parameters": {
                "SimpleItem": [
                  {
                    "Name": "MinCount",
                    "Value": "5"
                  },
                  {
                    "Name": "AlarmOnDelay",
                    "Value": "100"
                  },
                  {
                    "Name": "AlarmOffDelay",
                    "Value": "100"
                  },
                  {
                    "Name": "ActiveCells",
                    "Value": "0P8A8A=="
                  }
                ]
              },
              "Name": "MyMotionDetectorRule",
              "Type": "tt:CellMotionDetector"
            },
            {
              "Parameters": {
                "ElementItem": [
                  {
                    "Name": "Field"
                  }
                ]
              },
              "Name": "MyTamperDetectorRule",
              "Type": "tt:TamperDetector"
            }
          ]
        }
      },
      "PTZConfiguration": {
        "Name": "PTZConfiguration",
        "UseCount": 3,
        "token": "PTZConfigurationToken",
        "NodeToken": "NODE_000",
        "DefaultAbsolutePantTiltPositionSpace": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace",
        "DefaultAbsoluteZoomPositionSpace": "http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace",
        "DefaultRelativePanTiltTranslationSpace": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace",
        "DefaultRelativeZoomTranslationSpace": "http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace",
        "DefaultContinuousPanTiltVelocitySpace": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace",
        "DefaultContinuousZoomVelocitySpace": "http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace",
        "DefaultPTZSpeed": {
          "PanTilt": {
            "x": 0.5,
            "y": 0.5,
            "space": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace"
          },
          "Zoom": {
            "x": 0.5,
            "space": "http://www.onvif.org/ver10/tptz/ZoomSpaces/ZoomGenericSpeedSpace"
          }
        },
        "DefaultPTZTimeout": "PT5S",
        "PanTiltLimits": {
          "Range": {
            "URI": "http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace",
            "XRange": {
              "Min": -1,
              "Max": 1
            },
            "YRange": {
              "Min": -1,
              "Max": 1
            }
          }
        },
        "ZoomLimits": {
          "Range": {
            "URI": "http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace",
            "XRange": {
              "Min": 0,
              "Max": 1
            }
          }
        },
        "Extension": {
          "PTControlDirection": {
            "EFlip": {
              "Mode": "OFF"
            },
            "Reverse": {
              "Mode": "OFF"
            }
          }
        }
      },
      "Extension": {},
      "token": "002",
      "fixed": true
    }
  ]
}
```

## Checklist

- [X] The code change is tested and works locally.
- [] Local tests pass. **Your PR cannot be merged unless tests pass**
- [X] There is no commented out code in this PR.
- [] The code has been formatted using Ruff (`ruff format frigate`)

### CODE REVIEW

**Comment by ltomes** [comment]
Pinging @hawkeye217 as I think this MR got lost under the dependabot MRs.

**Comment by hawkeye217** [comment]
The docs already show that the Sunba 405-D20X is not supported, so I'm not sure I understand what you're trying to add to the documentation here. Can you clarify?

**Comment by ltomes** [comment]
I believe there have been many Sunba 405-D20X revisions over the years. It's not one model. 
 405-D20x
 405-D20x V2 
 405-D20x Eco
 405-D20x 4k

Are the ones I know of.

It's useful to list which PTZ models don't meet frigates requirements. If it's not listed each user has to buy incompatible ptz hardware blindly untill they land on something that works.

**Comment by hawkeye217** [comment]
I don't think we need to add variants of a camera model to the list separately unless it actually does support autotracking when others of the same model don't.  I'd prefer the docs to just include a note on the existing Sunba 405-D20X line as something like: "4K variant, but likely others too".

**Comment by ltomes** [comment]
> I don't think we need to add variants of a camera model to the list separately unless it actually does support autotracking when others of the same model don't. I'd prefer the docs to just include a note on the existing Sunba 405-D20X line as something like: "4K variant, but likely others too".

Thanks for the reply/that makes sense to me. I updated my commit to just add more details to the one entry. I can open a discussion here on github where I share more details about why it was not compatible.

**Review by hawkeye217 — APPROVED** [review]

**Pull request merged**
