### PR TITLE
Override URL format

### PR DESCRIPTION
**Pull request by mr-onion-2**
My tiny contribution to this great project

Addresses #56 

If there's a better solution please don't hesitate to reject - I won't be offended :)

### CODE REVIEW

**Review by blakeblackshear — APPROVED** [review]

**Comment by nic0dk** [comment]
having to reolink, getting the ``` queue full. moving on ``` alot, when will this function be implemented ? :)

**Comment by aav7fl** [comment]
@blakeblackshear Any chance we can see this merged? I'd love to be able to switch to rtmp for my cameras. It should eliminate most problems that I'm having with corrupt streams.

**Comment by aav7fl** [comment]
Yea, looks like the `rtsp_transport` (and consequently `stimeout`) flag is not allowed for `rtmp` streams. https://ffmpeg.org/ffmpeg-protocols.html#rtmp

**Comment by aav7fl** [comment]
@blakeblackshear I created an alternative PR https://github.com/blakeblackshear/frigate/pull/75 on top of @mr-onion-2 's work. This adds in a different config option for rtmp. There is a tiny bit of code duplication now, but it's a bit cleaner to read with the `rtsp` and `rtmp` broken up.

**Comment by mr-onion-2** [comment]
Hi @aav7fl, I like it! More than happy for this one to be closed and superceded by #75

**Pull request closed without merging**
