### PR TITLE
Make Snapshots path configurable

### PR DESCRIPTION
**Pull request by judahrand**

### CODE REVIEW

**Comment by NickM-27** [comment]
I don't think we want to do this. Users can already map snapshots to wherever they want via docker, and as it is now this would break the frontend and the frigate integration

**Comment by judahrand** [comment]
> I don't think we want to do this. Users can already map snapshots to wherever they want via docker, and as it is now this would break the frontend and the frigate integration

This is a first step to a better implementation of https://github.com/blakeblackshear/frigate/pull/6586 which will use https://github.com/fsspec/universal_pathlib

**Comment by NickM-27** [comment]
There are many problems with this approach:
1. home assistant addon requires the files to be in /media/frigate, if a user configured this they would just break their config
2. this is only being used for snapshots. In 0.14 many other files will live in /media/frigate/clips that have not been accounted for here
3. like I said, the frontend and the integration would need a lot of changes

I am not sure if this is at all desirable either, I'd recommend not spending more time on it until you confirm that this is something Blake agrees with. https://github.com/blakeblackshear/frigate/pull/6586 was never agreed on and was a contribution from a community contributor / user

my personal opinion is this would just be handled outside of frigate and mapped to /media/frigate/clips via docker. I don't see a reason for frigate to support this directly.

**Comment by NickM-27** [comment]
> Are there not other config options which would break Home Assistant if set? I'm not sure "If the user misconfigures things it breaks." is a strong argument for not having configuration.

Not like this, a user would essentially be able to enter any path into this field when only /media/frigate/* or s3:// would work in this case. That is a bad experience for users and confusing. 

> This was deliberate as I was specifically only implementing this for snapshots initially. There is quite a lot of stuff for which it feels like there is much less value in writing to remote storage.

right, but that completely breaks frigate. You are replacing /media/frigate/clips with this custom path but then other parts of the code depend on this path existing and it won't if a user changed it. 

> Does these directly access the storage by assuming filepaths?

it access the paths which are exposed via nginx. 

To address the main problem of uploading to the cloud, cron is not the main option. Frigate already outputs all detections via mqtt. It could very easily be configured to output recordings for a given event when something occurs. Especially with the additional APIs that are available in 0.14.

If the main goal of this PR is for introduction of s3 then I really don't think making the snapshot path configurable is a good way to address it

**Comment by judahrand** [comment]
> > Are there not other config options which would break Home Assistant if set? I'm not sure "If the user misconfigures things it breaks." is a strong argument for not having configuration.
> 
> Not like this, a user would essentially be able to enter any path into this field when only /media/frigate/* or s3:// would work in this case. That is a bad experience for users and confusing.
> 
> > This was deliberate as I was specifically only implementing this for snapshots initially. There is quite a lot of stuff for which it feels like there is much less value in writing to remote storage.
> 
> right, but that completely breaks frigate. You are replacing /media/frigate/clips with this custom path but then other parts of the code depend on this path existing and it won't if a user changed it.
> 
> > Does these directly access the storage by assuming filepaths?
> 
> it accesses the paths which are exposed via nginx.
> 
> To address the main problem of uploading to the cloud, cron is not the main option. Frigate already outputs all detections via mqtt. It could very easily be configured to output recordings for a given event when something occurs. Especially with the additional APIs that are available in 0.14. You could also setup docker to write snapshots simultaneously to local and remote storage.
> 
> If the main goal of this PR is for introduction of s3 then I really don't think making the snapshot path configurable is a good way to address it. It voids the use case where a user might want to store locally and remotely simultaneously and it creates many other documentation, user support, and breaking change concerns.

I'll take the L here. Having played around some more I think the best solution is a combination of https://github.com/kahing/goofys, https://github.com/kahing/catfs, and the Docker mount. This downside being, however, that setup isn't possible using the Home Assistant add-on.

**Pull request closed without merging**
