### PR TITLE
WIP: Update web deps 1

### PR DESCRIPTION
**Pull request by herostrat**
Needs testing

### CODE REVIEW

**Comment by herostrat** [comment]
Hey @paularmstrong I am a bit lost here :(
You seem to really understand this whole frontend stuff, do you have any idea why the tests fail?

One error is very similar to:
https://github.com/testing-library/jest-dom/issues/382

**Comment by paularmstrong** [comment]
Update one dependency at a time to track down the issue.

**Comment by blakeblackshear** [comment]
I am already working on getting these updated and revamping the build tools again at the same time. Things change so fast that sometimes it easier to just migrate to new approaches.

**Comment by blakeblackshear** [comment]
Closing this as I addressed these in another PR

**Pull request closed without merging**
