### PR TITLE
Initial support for YOLOv3-tiny and YOLOv5

### PR DESCRIPTION
**Pull request by triptec**
This PR builds on the hard work of @no2chem's [PR](https://github.com/blakeblackshear/frigate/pull/1022)  and @jveitchmichaelis's [repo](https://github.com/jveitchmichaelis/edgetpu-yolo) and @iaverypadberg's [fork](https://github.com/iaverypadberg/edgetpu-yolo), amazing work!

My contribution is mainly copy+paste but it seems someone needs to do that as well ;)

Now I'm not suggesting this be merged. I just really wanted to be able to detect cats pissing in my carport and yolov5 does that for me without too many false positives. Now I'm kind of hoping this will inspire someone with more time/energy on their hands to clean this mess up and get it into frigate =)

To try this branch out
1. Follow the [setup instructions](https://docs.frigate.video/contributing#setup)
2. Get one of the models from [here](https://github.com/iaverypadberg/edgetpu-yolo/tree/main/models) and labels from [here](https://github.com/xuwanqi/yolov3-tensorrt/blob/master/coco_labels.txt)
3. And update the config accordingly, for example:
```
mqtt:
  host: mqtt

cameras:
  test:
    ffmpeg:
      inputs:
        - path: /media/frigate/cat1-15.MP4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - rtmp
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25

model:
  path: /media/frigate/yolov5s-int8-224.tflite
  height: 224
  width: 224
  type: 'yolov5'
  labelmap_path: '/media/frigate/coco_labels.txt'
```

### CODE REVIEW

**Comment by NickM-27** [comment]
For it to be mergeable it would need to target the release branch, not master.

**Comment by triptec** [comment]
@NickM-27 against the release branch? It seems both ahead and behind master?

**Comment by NickM-27** [comment]
> @NickM-27 against the release branch? It seems both ahead and behind master?

Yes, new features go to the release branch. Docs updates and bug fixes for current release go to master. (This is current branching strategy, blake said he'll revisit after another contributor discussed potential changes)

**Comment by blakeblackshear** [comment]
There are a lot of changes to add support for these model architectures. Are the models you are using trained on the same COCO dataset as all the other models? What benefits are you seeing?

**Comment by triptec** [comment]
I’ll is there any way to record a video with the debug annotations and maybe I can show the difference?

**Comment by blakeblackshear** [comment]
You either have to screen record or use the mjpeg feed as an input to ffmpeg.

**Comment by triptec** [comment]
Ok, I'll give that a try. I've also just received a coral dev board and thought I should try this code on it.

**Pull request closed without merging**
