### PR TITLE
Some fixes in audio processing

### PR DESCRIPTION
**Pull request by skrashevich**

### CODE REVIEW

**Comment by NickM-27** [comment]
Please don't make PRs to unmerged branches that are still being worked on

**Comment by skrashevich** [comment]
It's just that I have exactly the same function in development now :)

**Comment by NickM-27** [comment]
This is why it's good to ask / suggest an implementation before working on it.

Blake and I have already decided on the direction we want to go with the initial implementation of the audio feature for 0.13, I'm going to have my PR up today.

**Comment by skrashevich** [comment]
This is why it's good to public project roadmap ;)

**Comment by NickM-27** [comment]
> This is why it's good to public project roadmap ;)

Not sure what you mean, this feature is on the list of things being worked on for 0.13 https://github.com/blakeblackshear/frigate/pull/6262

**Comment by NickM-27** [comment]
Public roadmap is also irrelevant, if a contributor doesn't ask about their implementation of a feature before implementing it, there will always be a chance that it doesn't align with the authors vision and won't be accepted.

**Pull request closed without merging**
