### PR TITLE
Update home-assistant.md

### PR DESCRIPTION
**Pull request by gaco79**
Added mention of the Frigate Addon to the Home Assistant integration page.

It's not clear when arriving at the integration page that you must first install the Addon

### CODE REVIEW

**Comment by blakeblackshear** [comment]
Except that the integration does _not_ require the addon specifically. It just requires that you are running Frigate somewhere. It can be on a separate device.

**Comment by gaco79** [comment]
Ah. Fair enough. I still think that needs to be mentioned somewhere. I'll have another go and see what you think.

**Comment by NickM-27** [comment]
It is mentioned image

**Comment by gaco79** [comment]
OK. I guess you're happy as it is!

**Pull request closed without merging**
