### PR TITLE
UX: Disable enabled features if corresponding roles are not assigned to an input

### PR DESCRIPTION
**Pull request by skrashevich**
let's be no so strict in config

### CODE REVIEW

**Comment by NickM-27** [comment]
I don't think this is a good approach. Users are already confused why their recordings aren't working despite enabling it which is why frigate now forces recordings to be enabled in the config before they can be toggled via API. 

We do want to be strict, user is configuring recordings and frigate can not work with that configuration so it should stop so user is immediately aware that there is a problem without having to check the logs or assume recordings are working until they are not

**Comment by skrashevich** [comment]
My changes suggest not giving an error if the option is enabled globally, but the role is missing in a particular camera, simply disabling it. But, according to your last message, it makes sense to change behavior in this PR to the opposite

**Comment by NickM-27** [comment]
> My changes suggest not giving an error if the option is enabled globally, but the role is missing in a particular camera, simply disabling it. But, according to your last message, it makes sense to change behavior in this PR to the opposite

Maybe there is some misunderstanding, but to be clear I think things are good as they are. I don't see a reason for it to change. If a user enables recordings but has not assigned the record role to an input then frigate should throw a config validation error. This way the config would not be saved in the config editor and frigate is now allowed to start with ambiguous behavior.

**Comment by skrashevich** [comment]
Ok, another example: if a globally enable "audio", i wan't see an error if any camera hasn't this role. it's absolutely non-logical, in my opinion

**Comment by NickM-27** [comment]
> Ok, another example: if a globally enable "audio", i wan't see an error if any camera hasn't this role. it's absolutely non-logical, in my opinion

Yes, the global config is meant to set the config for all cameras, if in that scenario you only want audio events for some cameras then you should only enable audio for those cameras. 

A user enables global config for recordings and frigate starts so they think recordings are working for all their cameras and leave frigate alone. Only to find later that no recordings have been saved and an error is in the logs, this is a poor user experience and similar situations in the past have led to a lot of confusion in the GitHub support issues.

**Comment by blakeblackshear** [comment]
I think it would be good to have this apply for globally enabled settings as well. If `audio` is enabled globally, I think the config should be invalid if the role isn't assigned for any camera if it isn't disabled for that camera.

**Comment by NickM-27** [comment]
> I think it would be good to have this apply for globally enabled settings as well. If `audio` is enabled globally, I think the config should be invalid if the role isn't assigned for any camera if it isn't disabled for that camera.

Makes sense, and I believe that is how it works today for audio. Detect and record only work this way if there are multiple inputs

**Pull request closed without merging**
