### PR TITLE
Improve docs on exports API endpoints

### PR DESCRIPTION
**Pull request by SpangleLabs**
## Proposed change

- Adding comments about the optional "name" parameter for the API endpoint to create a new export.
- Adding an entry in the documentation about the /api/exports endpoint

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code (docs)
(Not sure if docs should be a separate type here, or whether this counts as new feature, for documenting features without docs, or bugfix for adding docs where they perhaps should have existed)

## Additional information

I was unsure whether this merges into dev or master, but I saw other PRs merged into master when updating docs (for example #14202) and dev branch will be headed towards post-0.14 changes now I suppose.
Originally I was planning to add an issue asking why these features weren't available in the API, but then I checked the API source and found they do exist.

One question I do have is that it seems like the /api/exports endpoint lists the video path relative to the container root, rather than relative to the web root. Is that intended? Should a user of that API strip "/media/frigate" from the video path, or that they should just use the export ID as `{frigate_url}/exports/{export_id}.mp4`

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [ ] The code has been formatted using Ruff (`ruff format frigate`) 
  (Not applicable for the docs directory?)

Screenshot:
image

### CODE REVIEW

**Comment by NickM-27** [comment]
Worth noting that in the dev branch the API docs are now generated automatically, this can be merged but it will be fixed automatically when 0.15 is released

> Is that intended? Should a user of that API strip "/media/frigate" from the video path

Yes

**Comment by SpangleLabs** [comment]
> Worth noting that in the dev branch the API docs are now generated automatically, this can be merged but it will be fixed automatically when 0.15 is released

Oh neat! I see, [docusaurus will be generating](https://github.com/blakeblackshear/frigate/blob/dev/docs/docusaurus.config.ts#L115) pages from [the openAPI spec](https://github.com/blakeblackshear/frigate/blob/dev/docs/static/frigate-api.yaml), that'll be cool for a lot of reasons.

Though I guess the json request and response body stuff still needs filling out for those:
image
image

I pondered whether I can add that too, while I'm digging around, but I can't see what actually generates [that openAPI spec file](https://github.com/blakeblackshear/frigate/blob/dev/docs/static/frigate-api.yaml) though, is it generated by the fastAPI definitions, or is that part not yet defined? Or is it intended to be manually modifying the openapi spec file?

**Comment by NickM-27** [comment]
it is generated by fastapi, though I believe the contributor that implemented fastapi has already planned to work out building out the schema of responses.

**Review by NickM-27 — APPROVED** [review]

**Review by hawkeye217 — APPROVED** [review]

**Comment by iursevla** [comment]
@SpangleLabs I'm currently updating the requetsts/responses to have better/more information 🙏 

I will be working on this for 1-2 weeks and every endpoint should have a better documentation

If you find any incongruency please let me know. Whenever I open a new PR if I remember I'll tag you

**Pull request merged**
