### PR TITLE
Update go2rtc

### PR DESCRIPTION
**Pull request by a2nt**
I have tested it with Rockchip - works ok

ghcr.io/a2nt/frigate:dev-rk-98d1afcb-rk

### CODE REVIEW

**Comment by NickM-27** [comment]
the docs and links need to be updated as well

**Comment by MarcA711** [comment]
@a2nt I guess you are interested in hardware acceleration for Rockchip socs?
The hardware acceleration presets from this go2rtc version work only with the older FFmpeg fork from hbiyik. Frigate now uses the fork from nyanmisaka since it works better. The go2rtc presets need to be updated, see https://github.com/AlexxIT/go2rtc/issues/979

Maybe it is better to update go2rtc after the presets were updated.

**Comment by NickM-27** [comment]
I think it is fine to update go2rtc now in general, there are many fixes in 1.9.0/1

**Comment by a2nt** [comment]
> @a2nt I guess you are interested in hardware acceleration for Rockchip socs? The hardware acceleration presets from this go2rtc version work only with the older FFmpeg fork from hbiyik. Frigate now uses the fork from nyanmisaka since it works better. The go2rtc presets need to be updated, see [AlexxIT/go2rtc#979](https://github.com/AlexxIT/go2rtc/issues/979)
> 
> Maybe it is better to update go2rtc after the presets were updated.

Hmmm I don't experience any performance issues current go2rtc 1.8.5 version at frigate by AlexxIT has a bit higher CPU usage than 1.9.1 by AlexxIT using h264. I don't see big difference

But will look forward for updated presets

**Comment by NickM-27** [comment]
this has been handled in a separate PR

**Pull request closed without merging**
