### PR TITLE
Add enabling/disabling camera capture via MQTT

### PR DESCRIPTION
**Pull request by cobryan05**
Adds new MQTT topic,

  frigate/<camera>/capture/state

to dynamically enable or disable capturing from a camera.

The ffmpeg process is terminated when the capture state is OFF and is resumed when the capture state is ON.

### CODE REVIEW

**Comment by NickM-27** [comment]
I know this is in draft but wanted to suggest instead of having a new capture_enabled field we should use the existing `enabled` field

**Comment by cobryan05** [comment]
> I know this is in draft but wanted to suggest instead of having a new capture_enabled field we should use the existing `enabled` field

Does that field have no other function? I'm not looking to break anything else, just looking to get minimal changes to get my use case to work :)

**Comment by NickM-27** [comment]
The field exists to disable the camera which is functionally what is being done here anyway. I also don't see the capture_enabled field being used so if the user set that to false on startup then capture would still be enabled.

**Comment by cobryan05** [comment]
> The field exists to disable the camera which is functionally what is being done here anyway. I also don't see the capture_enabled field being used so if the user set that to false on startup then capture would still be enabled.

I think I can address not respecting the initial setting....

The 'capture_enabled' is more of a 'pause/resume' for an enabled camera.  The base 'enabled' setting is checked at start-up and if disabled then the python capture process won't be started. If I combined the two I would have to modify this behavior. 'Disabled' cameras would still spawn the capture python processes on boot, they would just be in a paused state. I'm not sure where else in the code this change would affect

**Comment by NickM-27** [comment]
Right, what I am suggesting is perhaps some of that behavior can change to meet this feature. Having a full enabled, capture enabled, recording enabled (which could be affected by your capture changes if the user is using the same stream for record and detect) then it could get quite confusing which toggle / config option is used for what.

**Comment by cobryan05** [comment]
I'll just leave this here as a draft for now. Someone else requesting this feature might be able to use this as a starting point, or if I get the rest of my project working then I'll probably try to get this more finalized... but this gets me where I need to be for now and I'm not immediately looking to spend more time diving into frigate code.

**Comment by citgot** [comment]
Is this for disabling/enabling individual cameras without the need for restarting Frigate? As for turning off indoor cameras when occupancy is true or similar? If you got this working I hope you will see this draft through to a final product

**Comment by NickM-27** [comment]
> Is this for disabling/enabling individual cameras without the need for restarting Frigate? As for turning off indoor cameras when occupancy is true or similar? If you got this working I hope you will see this draft through to a final product

Yes, that is what this PR is addressing

**Comment by NickM-27** [comment]
I have changed my mind and I can see why you may want to disable the capture without disabling recording.

Have you been testing this, how has it been working?

**Comment by cobryan05** [comment]
It's been working pretty well for me. I'm using this to have Frigate be an NVR for a rainforest-related company's security doorbells and cameras.

Frigate in general shows the "No Frames Have Been Received" error message on these cameras, until a motion detection event triggers enabling capture on the camera. When the camera is enabled ffmpeg starts up, opens an RTSP stream (which causes a live stream to be relayed from the cloud server) and the "No Frames Have Been Received" message goes away to show the live stream, which Frigate does a good job of then recording and saving clips of.

In HomeAssistant I just put the Frigate card on a page with a set of toggle switches to enable the different cameras, so if I wanted to view it live I can with just the one extra step of enabling the camera.

I'd say it probably works 90-95% of the time.  I don't think any of the issues are on Frigates side, sometimes ffmpeg just isn't happy with the rtsp connection, which I suspect could be an issue with the other side of the connection as well.

There also is often some corruption at the very start and end of the videos, but overall it is working well enough for me that I am happy with it, and I haven't had to touch it for a few days and its still doing its thing.

I agree that the name 'capture' could be confusing.  This really just suspends/resumes the video connection to the camera, which of course everything else then relies on. I'd definitely be happy with finding a better name for it.  Maybe call it "suspend_camera" or something.

I did take a quick look at using 'enable' setting, but when I couldn't immediately figure out how make changes to the, eg, .tsx files actually take effect I didn't spend too much time on it.

**Comment by chatziko** [comment]
This is a well needed feature, looking forward to it!

Some thoughts:

- I don't think that a camera without an active ffmpeg process should be displayed as "disabled" or "suspended". One can still watch a live feed from the camera (via go2rtc), or view past recordings etc. The camera still works, we just don't have a constant feed from it.

- Having multiple boolean flags is likely to be confusing for users, especially when there is overlap between them and no clear semantics. I personally don't see a need for an "ffmpeg" flag, frigate should just automatically close ffmpeg when not needed (when all possible uses of ffmpeg are disabled). Note that go2rtc also runs ffmpeg only when needed.

**Comment by conorlap** [comment]
This would be a great feature. My use case is:

I have internal cameras powered through smart plugs that only turn on when my partner and I are both out of the house.
My dashboard only displays the camera cards when the smart plugs are on (conditional cards).

Currently Frigate gives lots of errors when the cameras are off so being able to call an API/send mqtt to disable the camera within Frigate as part of my 'both of us are away from home' automation would be very useful.

**Comment by NickM-27** [comment]
Unfortunately there's no way to get this in without some considerable changes because there are a number of edge cases and things to consider:

1. This mainly works when a user is using the same path (thus the same ffmpeg process) for detect and record. If a user has a separate process for record it will not be paused
2. If a user has their config setup to do 24/7 motion or object based recording then the detect ffmpeg process can't paused ever otherwise they would never get recordings even if these things happened. That would need to be checked / safeguarded against, only allowing if recordings are currently set to off. 
3. I think stream_processing is a better choice of naming than capture which could easily be confused with recording.

**Comment by citgot** [comment]
Why would you have to safeguard regarding your second point @NickM-27 ? Isn’t that quite obvious for a user that if you “disable” the camera it won’t record? I mean, the user has made the choice via MQTT to disable the camera and thus it wouldn’t be a surprise that the motion recording is also inactive? Or am I missing something?
I’m eagerly awaiting this to be merged as I need that functionality in my system. Maybe that’s why I don’t see the problem. 

Regarding your first point though, that would be a problem. So in many cases both the main and sub stream needs to be ignored to get the right functionality?

**Comment by NickM-27** [comment]
> Why would you have to safeguard regarding your second point @NickM-27 ? Isn’t that quite obvious for a user that if you “disable” the camera it won’t record? I mean, the user has made the choice via MQTT to disable the camera and thus it wouldn’t be a surprise that the motion recording is also inactive? Or am I missing something?

No, because this is not necessarily full disabling. You might want to disable processing of objects / motion but still keep 24/7 recordings and not realize the two are linked. If you look at the support issues you will find seemingly obvious things in the docs and otherwise that are not clear and this can be due to any number of reasons. 

We should not depend on obvious behavior, if a users config asks for 24/7 motion based recordings it should not be possible to disable processing unless recording is disabled. And not possible to enable recording unless processing is also enabled.

> Regarding your first point though, that would be a problem. So in many cases both the main and sub stream needs to be ignored to get the right functionality?

Not sure what you mean by ignored

**Comment by chatziko** [comment]
I agree with @NickM-27 's comments, which further support my belief that the whole procedure should be automatic, with no aditional flags visible to the user.

A connection to the camera is a technical means for implementing a feature, such as recording or motion detection. A user should be able to disable the features (not the technical means). Then, if a connection is not needed because all features it supports are disabled, it should be automatically closed.

**Comment by NickM-27** [comment]
also to add context, we are already planning in a future version of frigate to always use separate ffmpeg processes for recording and detect even if they have the same path as this will allow a lot of flexibility for different default ffmpeg args and other things. 

The side effect of that is it would also simplify the handling of this since the recording switch could simply pause the recording maintainer and recording ffmpeg process. Then we'd need the stream_processing switch to do what it already does here.

**Comment by Yonny24** [comment]
Following this as I was looking to disable specific cameras via mqtt or some switch easily utilizing the enabled: false/true option.
I only use the cameras for motion detection really at certain times. When I disabled motion detection I want to disable the camera completely so it does not consume cpu resources.

Is this the concept of this project?

Thanks

**Comment by Gifford47** [comment]
@NickM-27 
I wanted to ask what the status of this feature is? for me it is also very important, because my cameras are turned on only after certain events. So I would like to know if this feature is actively planned? if yes, how can i help or sould be tested?

**Comment by NickM-27** [comment]
> @NickM-27 I wanted to ask what the status of this feature is? for me it is also very important, because my cameras are turned on only after certain events. So I would like to know if this feature is actively planned? if yes, how can i help or sould be tested?

the issues and concerns have been listed above. The author of the PR can address them and mark this as ready for review, or someone else can try to work on it. 

I don't personally have any plans to work on this any time soon; there are changes planned for a future version of frigate that will make this simpler so I don't know that it makes sense to work on this right now

**Comment by cobryan05** [comment]
> The author of the PR can address them and mark this as ready for review, or someone else can try to work on it.

Just so no one is getting their hopes up waiting for me on this, I have no plans to do further work on this either

**Comment by NickM-27** [comment]
Thanks for clarifying, in that case I'll close this PR. Anyone can feel free to pick it up and be sure to consider the issues stated above.

**Comment by danishru** [comment]
In Frigate 0.14 there is a mention of enable\disable each camera, but it can't be done without restarting Frigate addon, as it is done for detection and recording. Maybe there is another way to turn off camera without restarting?

**Pull request closed without merging**
