### PR TITLE
Stop tracked thumbnail from being cached

### PR DESCRIPTION
**Pull request by NickM-27**
I noticed after merging #2944 that the thumbnails under camera were being cached and not updating (even after deleting the related event).

### CODE REVIEW

**Comment by blakeblackshear** [comment]
Probably best to set cache control headers appropriately instead. I need to look at doing this in nginx.

**Comment by NickM-27** [comment]
> Probably best to set cache control headers appropriately instead. I need to look at doing this in nginx. 

Okay I see, that makes sense. Should I close this then?

**Comment by blakeblackshear** [comment]
It's fine to keep open as a reminder

**Comment by NickM-27** [comment]
bot

**Pull request closed without merging**
