### PR TITLE
A higher limit for recording segments *** suggestion ***

### PR DESCRIPTION
**Pull request by LaurenceGough**
*** suggestion ***

I'd like to test a higher limit for recording segments to avoid recording loss. Say, changing 5 to 20. Is there a downside apart from potentially using a bit more cache?

I'm a bit new to all this "Once a pull request is opened, you can discuss and review the potential changes with collaborators". 

I really do apologise if this is not the intended purpose in this branch / project.

Thank you

### CODE REVIEW

**Comment by NickM-27** [comment]
I don't think it makes sense to outright make the limit higher. For users that have setups that only retain segments with motion it may lead to a lot more cache use and other slow downs. 

It could potentially make sense to make the limit a bit higher when the retain mode is all, but I am not familiar enough with this code to say for sure if that is a good idea or not.

**Comment by blakeblackshear** [comment]
The changes I made recently clear out the cache proactively across every retention mode, so it shouldn't be an issue. I would rather make this a config option that defaults to 5 with a warning that you really shouldn't need to increase it unless there you have temporary periods of slowness on your recordings storage.

**Comment by ccutrer** [comment]
Can this be re-opened as not-stale?

**Comment by NickM-27** [comment]
#5818 serves as the open issue. It makes no sense to keep this PR open given that this PR does not implement the feature in the form that was suggested to be accepted as a feature in frigate.

**Comment by ccutrer** [comment]
Sounds good. I assumed that issue is only being tracked as a support request, not an actual software enhancement request.

**Pull request closed without merging**
