### PR TITLE
Use hassio-addon as docker base image

### PR DESCRIPTION
**Pull request by felipecrs**
This switches the base image to the https://github.com/hassio-addons/addon-debian-base, which abstracts a bunch of things for us, and can still be used outside Home Assistant.

It also comes with s6-overlay v3.

### CODE REVIEW

**Comment by felipecrs** [comment]
If you believe it's not a good idea to use the hassio base, I can simply make the changes here. But I don't see why not, it's very well versioned.

**Comment by NickM-27** [comment]
Personally, I prefer using a debian base because IMO it makes more sense to start minimal and add the things we want as opposed to using the addon base image and then fighting it by removing some of what it's adding.

Will of course be happy to hear other perspectives

**Comment by felipecrs** [comment]
As per @frenck's feedback on https://github.com/hassio-addons/addon-debian-base/pull/126#discussion_r1021996284, I no longer think we should use the hass community base addon. I'll change the PR accordingly.

**Comment by felipecrs** [comment]
> @felipecrs There is no need to ping/mention me here. You've effectively pulled me into this conversation and notified me. I have no part in this PR. Please avoid that. Thanks 👍

Understood. Really sorry about it. Please unsubscribe from this PR this time.

**Pull request closed without merging**
