### PR TITLE
Add docs for installing Frigate as PWA

### PR DESCRIPTION
**Pull request by NickM-27**

### CODE REVIEW

**Review by hawkeye217 — APPROVED** [review]

**Comment by mathgim** [comment]
Hi @NickM-27,
Thank you for the incredible work you guys are doing. The latest UI is quite something! Congrats!
 I am trying to install the pwa on Android and something is lacking in the documentation. It does not say which url to access before using the install as an app feature. 
For instance, I use frigate addon and integration on home assistant OS  with duckdns for external access so I tried to install frigate as an app from the addon url but of course it offers to install home assistant...
I am sure I miss something..

**Comment by NickM-27** [comment]
you have to be accessing Frigate UI directly, not through home assistant. I will make a note of that in the docs

**Comment by mathgim** [comment]
Yes that's what I thought I understood when reading few things online. But I can't figure out how to access frigate directly in my setup. 😅

**Comment by NickM-27** [comment]
Start by exposing port 8971 then create a proxy to it

**Comment by mathgim** [comment]
I am so sorry, what do you mean by create a proxy? 
Exposing port means opening it with my internet router, this I think I understood xD

**Comment by NickM-27** [comment]
No it means opening it in the docker container, not on your router

**Comment by mathgim** [comment]
I use frigate addon on Home Assistant OS and core. Which means I do not handle directly docker components. Is this still feasible? Thank you for your help on that topic!
________________________________
De : Nicolas Mowen ***@***.***>
Envoyé : mercredi 30 octobre 2024 12:00
À : blakeblackshear/frigate ***@***.***>
Cc : Mathieu Gimenez ***@***.***>; Comment ***@***.***>
Objet : Re: [blakeblackshear/frigate] Add docs for installing Frigate as PWA (PR #12995)


No it means opening it in the docker container, not on your router

**Comment by NickM-27** [comment]
yes, just go to addon settings and enable the port

**Comment by mathgim** [comment]
Ok, thank you Nicolas, I did so, and now I hace access to the frigate login page using https://my_local_ip:8971.
I even access it externally using duckdns by opening the port on my internet router.
But I still can't install the pwa and I assume it is because of some ssl certificate issue. I have no problem when accessing the 8123 port but trying to access 8971 is raising an alert by the browser about the certificate.

________________________________
De : Nicolas Mowen ***@***.***>
Envoyé : mercredi, octobre 30, 2024 4:54:18 PM
À : blakeblackshear/frigate ***@***.***>
Cc : Mathieu Gimenez ***@***.***>; Comment ***@***.***>
Objet : Re: [blakeblackshear/frigate] Add docs for installing Frigate as PWA (PR #12995)


yes, just go to addon settings and enable the port

**Pull request merged**
