### PR TITLE
Enabling RTSP with no authentication 

### PR DESCRIPTION
**Pull request by pizzato**
This is something I needed for running this on my cameras with no auth. 

I noticed another pull request on the same function, so this will need merging with those changes if integrated.

Thanks for the great project.

### CODE REVIEW

**Comment by hawkeye217** [comment]
I know this doesn't affect you directly, but would or @blakeblackshear consider maybe also adding an optional `protocol:` to the config file?  One of my cameras streams via http, not rtsp, and it'd be great to have this feature in an official release.  

Original code:
``
    return 'rtsp://{}:{}@{}:{}{}'.format(rtsp_config['user'], 
	        rtsp_config['password'], rtsp_config['host'], rtsp_config['port'],
	        rtsp_config['path'])
``

A quick change could be something like this below, while adding a `protocol: http` to the config file.

``
    return '{}://{}:{}@{}:{}{}'.format(rtsp_config['protocol'],rtsp_config['user'], 
	        rtsp_config['password'], rtsp_config['host'], rtsp_config['port'],
	        rtsp_config['path'])
``

**Comment by hawkeye217** [comment]
Actually, it looks like https://github.com/blakeblackshear/frigate/pull/65 might be able to do what I need, and @blakeblackshear already committed it.

**Comment by pizzato** [comment]
Just noticed that #65 and the original code should work with no user+pass. I believe I had some problems when first using this project and modifying this fixed.

I'll close this pull request as it seems not relevant.

**Comment by pizzato** [comment]
Actually.. apologies for this. Just reopening to point out that #65 and the original code, both use ``rtsp_config['user']`` and ``rtsp_config['password']``, which will fail on no user, no pass. The url should be fine if using something like ``rtsp_config.get('user','')`` instead.

**Pull request closed without merging**
