### PR TITLE
Filtering on Frigate+ submits in frontend

### PR DESCRIPTION
**Pull request by tpjanssen**
Initial draft. Please give your feedback.

### CODE REVIEW

**Comment by tpjanssen** [comment]
Filter icon should not be visible in case Frigate+ is not used.... Currently the filter is always visible.

**Comment by tpjanssen** [comment]
Any thoughts on this?

**Comment by NickM-27** [comment]
Probably good for now, I am thinking in 0.14 the filtering UI will be completely redone

**Review by NickM-27 — APPROVED** [review]

**Comment by tpjanssen** [comment]
@blakeblackshear any idea when this PR gets merged into dev? That will make my life a bit simpler... 😉

**Pull request merged**
