### PR TITLE
Vertical scroll and videoplayer scaling

### PR DESCRIPTION
**Pull request by sinamics**
This PR is related to #1557.

This one should be discussed before merged. Especially point 2 bellow.

1. Hided event information, and added button `View Event Details`
2. Scaled down the events videoplayer to 2/3 for `md`. This makes the UI much cleaner in my opinion. 
  ~~Had to remove `data-vjs-player` for the scaling to work, but as i understand, this might be important.~~
  Any comment for this one?

3. Added less padding on Buttons for smaller devices `sm`

Im open for discussion if we should choose a diffrent route regards videoplayer scaling.

events
events_sm

### CODE REVIEW

**Comment by jameswarner62** [comment]
Only speaking from a visual perspective, changes to event view look good - the collapse of event info makes a lot of sense.

I think the de-padding on sm might be a little too drastic - looks hard to hit with touch on mobile, and vertical space is less of an issue there anyway...

How does a 2/3 scaled player look on recordings viewer?

**Comment by Sinamics** [comment]
@jameswarner62 Recording page is not affected as i moved the 2/3 wrapper to event page only. 
The only thing that bothers me is that the 2/3 would not be consistent between pages, but it looks / feels better for sure. 
I could agree with you on the padding. This might brake the dev style rule as well.  🤔 

I will do some more testing next days and see what i come up with.

**Comment by jasonpstokes** [comment]
Looking a lot better, as currently when I view an event 2/3 of the clip are off the screen! But could you instead scale the video to something like 80% of the of the window's height, so the buttons are still visible under the clip but you maximise the viewing of the clip for the current screen/window size?

Also as mentioned above those buttons look a little thin in the mobile view.

**Comment by Sinamics** [comment]
- Reverted the button padding. 
- Buttons centered on small devices
- Changed to 3/4 scaling. This makes the player larger but still able to view all buttons.
- Reduced padding for the header-bar, this creates more space to play with as it as pretty huge.
- Fixed navbar frigate logo alignment, header-bar and main logo did not align propely when scrolling.

Also keep in mind that double click the image / video will open full screen.

main
small

**Comment by jameswarner62** [comment]
Looks really nice!

**Comment by Sinamics** [comment]
So, this took a new path and i have been playing with this new event viewer.
Instead of opening a new page for event-view, i have merged it directly into the events when clicking the image. 
This will also resolve #1465 as the scroll position will not change. 

This might be beyond what this PR was ment for, but like Elon Musk use to say, "Do not optimize things that should not be there in the first place"

So instead of optimzing the video scale in event page, this might be a nicer and cleaner solution. 
Let me know what you think. I can split these into two diffrente PR`s if required. 

See video below.
[Demo Video](https://drive.google.com/file/d/1LF_BMYWnHwmc0vhfMmxxP7W6MsXPpLXU/view?usp=sharing 'Demo Video')

**Comment by blakeblackshear** [comment]
Can you rebase this so I can test it out?

**Comment by Sinamics** [comment]
@blakeblackshear i will create a new PR for the "event view" and close this thread.
I just need to perform some more testing, but it should be ready later today or tomorrow latest.

**Comment by Sinamics** [comment]
As this turned out to be a much larger PR than first expected, i have splitted this into several other PR`s.

- Moved event view to events table.  #1596
- Reduce navbar padding / height #1587
- Remove misplaced comma in Header #1586


closing this PR.

**Pull request closed without merging**
