### PR TITLE
FEAT: Storage API &  Frontend

### PR DESCRIPTION
**Pull request by NickM-27**
I think it would be really cool to have a storage page in the frontend that displays the storage used by each camera so it is easier to visualize how that cameras retention settings contribute to overall storage use. Perhaps in a future PR management could be added but for now I think the information is helpful.

ToDo:

- [x] Add Storage API
- [x] Create storage route

Screen Shot 2022-11-29 at 16 23 52 PM

### CODE REVIEW

**Comment by NickM-27** [comment]
Current view of what it looks like

Screen Shot 2022-07-01 at 12 36 03 PM

**Comment by NickM-27** [comment]
Screen Shot 2022-07-01 at 13 47 18 PM

**Comment by felipecrs** [comment]
Oh wow, this is amazing! One suggestion would be to also display the total space, consumed space, and available space in human readable bytes. Or even in percentage as well.

**Comment by NickM-27** [comment]
Updated UI that includes other storage and sizes


Screen Shot 2022-07-10 at 2 50 37 PM

**Comment by NickM-27** [comment]
The storage is slow to calculate I assume due to dockerized file system. `du -h` from the same location is almost instant on my host and takes ~10 seconds inside the container. Doesn't seem that there is much I can do about this

**Comment by felipecrs** [comment]
Out of curiosity:

image

Inside of the Hass addon.

**Comment by NickM-27** [comment]
This is what I see:

### Host

Screen Shot 2022-07-19 at 6 45 23 AM

### Container

Screen Shot 2022-07-19 at 6 47 59 AM

**Comment by NickM-27** [comment]
It might be better to run this command on stats initialization, include it in stats, and then just use that for the page. Maybe have it refresh every few minutes or something 🤔

**Comment by felipecrs** [comment]
Perhaps you can switch to `ncdu` or `duc`?

```
sudo apt install -y ncdu
sudo apt install -y duc
```

They have optimizations in speed over `du` which most likely is worth it.

**Comment by NickM-27** [comment]
> Perhaps you can switch to `ncdu` or `duc`?
> 
> ```
> sudo apt install -y ncdu
> sudo apt install -y duc
> ```
> 
> They have optimizations in speed over `du` which most likely is worth it.

Thanks, ncdu appears to be faster and I think can work with the way I am using it

**Comment by NickM-27** [comment]
With the new segment calculation in `StorageMaintainer` it makes this incredibly quick and simple so an external tool is no longer needed. 

I am going to look in to a different frontend tool for displaying this info since it is clunky and I can't get good results

**Comment by NickM-27** [comment]
I decided not to go with the graph / bar component. Seemed too random / difficult to work with and I think it is better that the styles match the new system page.

**Review by blakeblackshear — APPROVED** [review]

**Pull request merged**
