### PR TITLE
Rewrite birdseye auto layout

### LINKED ISSUE #6802: Bug: wrong camera dimension calculation for birdseye
### Describe the problem you are having

```
2023-06-14 21:37:08.347713182  Traceback (most recent call last):
2023-06-14 21:37:08.347717528    File "/opt/frigate/frigate/output.py", line 549, in update
2023-06-14 21:37:08.347718362      updated_frame = self.update_frame()
2023-06-14 21:37:08.347719160    File "/opt/frigate/frigate/output.py", line 525, in update_frame
2023-06-14 21:37:08.347719827      self.copy_to_position(
2023-06-14 21:37:08.347720573    File "/opt/frigate/frigate/output.py", line 251, in copy_to_position
2023-06-14 21:37:08.347721350      copy_yuv_to_position(
2023-06-14 21:37:08.347722078    File "/opt/frigate/frigate/util.py", line 481, in copy_yuv_to_position
2023-06-14 21:37:08.347722667      destination_frame[
2023-06-14 21:37:08.347723383  ValueError: could not broadcast input array from shape (1080,1920) into shape (1080,1280)

```

this bug introduced in PR #6734 
if I comment out this lines:
```
 if camera_aspect < canvas_aspect:
                    camera_dims[0] *= camera_aspect / canvas_aspect
                    camera_dims[1] *= camera_aspect / canvas_aspect
``` 
always will work again

### Version

 dev-ff1b5c8

### Frigate config file

```yaml
detectors:
  deepstack:      
    type: deepstack
    api_url: http://192.168.88.50:5500/v1/vision/custom/ipcam-yolov5x6
    api_timeout: 0.5

go2rtc:
  ffmpeg:
    h264_nvenc: "-codec:v h264_nvenc -preset:v medium -b:v 4096k -maxrate 4096k -bufsize 4096k -r 24 -pix_fmt yuv420p -g 48"

  rtsp:
    default_query: "video&audio"

  webrtc:
    listen: ":8555"
    candidates:
      - 192.168.88.60:8555

  streams:
    kitchen: "rtsp://192.168.88.18:8080/video/h264#audio=aac#audio=pcm"
    livingroom: "rtsp://192.168.88.178:8080/video/h264#audio=aac"
    yard: rtsp://192.168.88.50:8554/yard
    secondfloor: rtsp://192.168.88.50:8554/secondfloor
    welcome: rtsp://192.168.88.50:8554/welcome

birdseye:
  enabled: True
  mode: continuous
  restream: True

ffmpeg:
  global_args: -hide_banner -loglevel debug
  hwaccel_args: preset-nvidia-h264
  #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  input_args: preset-rtsp-restream
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v hevc_nvenc -tag:v hvc1 -c:a copy

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 10
    mode: motion
  events:
    pre_capture: 30
    post_capture: 120
    retain:
      default: 7
      mode: motion
      objects:
        person: 180
        bottle: 1
        car: 7

snapshots:
  enabled: True
  height: 1080

cameras:
  livingroom:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/livingroom
          roles:
            - detect
            - record
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      height: 1080
      quality: 100
    detect:
      fps: 10
      width: 1920
      height: 1080
    motion:
      mask:
        - 1763,0,1920,368,1268,506,924,530,789,509,695,509,686,537,680,633,659,899,0,886,0,0

  kitchen:
    ffmpeg:
      inputs:
   
        - path: rtsp://localhost:8554/kitchen
          roles:
            - detect
            - record
     
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      height: 960
      quality: 100
    detect:
      fps: 10
      width: 1280
      height: 960
  yard:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.88.50:8554/yard
          roles:
            - detect
            - record
             
    detect:
      width: 1920
      height: 1080
      fps: 5
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      height: 1080
      quality: 100
       
    motion:
      mask:
        - 0,0,0,720,273,720,262,535,410,518,647,477,662,236,966,253,972,0
        - 1280,0,1280,692,1103,607,1058,602,1054,720,943,720,965,0
    zones:
      gates:
        coordinates: 783,278,775,337,694,327,696,269
    record:
      events:
        pre_capture: 30
        post_capture: 120
        retain:
          default: 7
          mode: motion

  secondfloor:
    ffmpeg:
      inputs:
       
        - path: rtsp://192.168.88.50:8554/secondfloor
          roles:
            - detect
            - record
     
      hwaccel_args: preset-nvidia-h264
    detect:
      width: 1920
      height: 1080
      fps: 10
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      height: 1080
      quality: 100

  welcome:
    ffmpeg:
      inputs:
       
        - path: rtsp://192.168.88.50:8554/welcome
          roles:
            - detect
            - record
      hwaccel_args: preset-nvidia-h264
     
    detect:
      width: 1920
      height: 1080
      fps: 10
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1080
  terasse:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.88.50:8554/terasse?mp4 #rtsp://192.168.88.50:8554/terasse?mp4
          roles:
            - detect
            - record
              #- path: "rtsp://192.168.88.195:554/user=admin_password=QuuOEfOI_channel=0_stream=0.sdp?real_stream#hardware=cuda"
              #roles:
              #- restream
      hwaccel_args: preset-nvidia-h264
      
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      height: 1288
      quality: 100
    detect:
      width: 2288
      height: 1288
      fps: 10
```

### Relevant log output

```shell
2023-06-14 21:37:08.347713182  Traceback (most recent call last):
2023-06-14 21:37:08.347717528    File "/opt/frigate/frigate/output.py", line 549, in update
2023-06-14 21:37:08.347718362      updated_frame = self.update_frame()
2023-06-14 21:37:08.347719160    File "/opt/frigate/frigate/output.py", line 525, in update_frame
2023-06-14 21:37:08.347719827      self.copy_to_position(
2023-06-14 21:37:08.347720573    File "/opt/frigate/frigate/output.py", line 251, in copy_to_position
2023-06-14 21:37:08.347721350      copy_yuv_to_position(
2023-06-14 21:37:08.347722078    File "/opt/frigate/frigate/util.py", line 481, in copy_yuv_to_position
2023-06-14 21:37:08.347722667      destination_frame[
2023-06-14 21:37:08.347723383  ValueError: could not broadcast input array from shape (1080,1920) into shape (1080,1280)
```

### Frigate stats

_No response_

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Any other information that may be helpful

_No response_

### LINKED ISSUE #6812: Birdseye autolayout is less optimized than previous grid layout
### Describe the problem you are having

image

I circled the boundaries of the cameras with red frames for clarity

cameras dimensions, from left top: 1280x960, 1920x1080, 1920x1080, 2288x1288 (no mistake here), 1920x1080, 1920x1080

### Version

dev-3efa77f

### Frigate config file

```yaml
see #6802
```

### Relevant log output

```shell
no relevant
```

### FFprobe output from your camera

```shell
no relevant
```

### Frigate stats

_No response_

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

### Any other information that may be helpful

_No response_

### PR DESCRIPTION
**Pull request by NickM-27**
This rewrite removes the manual 2 camera layout for the auto layout and refactors the auto layout to use aspect ratios instead of resolutions to determine the optimal layout that will fit

Fixes #6802 
Closes #6812

### CODE REVIEW

**Comment by skrashevich** [comment]
About #6812: it got much better. But alignment of 6 cameras as it used to look is better anyway ;)

image

**Comment by NickM-27** [comment]
Thank you for testing 👍

Technically the old view was "incorrect" because it gave all your cameras the same aspect ratio despite the fact that the cameras have different aspect radios.

**Review by blakeblackshear — APPROVED** [review]
This is definitely an improvement over what is currently in dev. We could also consider determining a fixed set of aspect ratios that play nice and fit all cameras within those boxes even if some black bars are left for some cameras.

**Comment by JeffWDH** [comment]
This was a huge improvement for my use case (one vertical + two horizontal cameras).

**Comment by ccutrer** [comment]
I'm getting occasional errors in my log today:

```
2023-06-16 20:33:27.886144797  [2023-06-16 20:33:27] frigate.output                 ERROR   : Error finding appropriate birdseye layout
```

And an unusual layout: https://capture.dropbox.com/knX0XY34ChyjdkdC
I don't think I would consider that a bug. It could be better, but I have a feeling that no matter the strategy that's being used, there's going to be some unusual cases that will cause weird things.

Running 0.13.0-B668102

**Comment by NickM-27** [comment]
What are the detect resolutions of the cameras? Most likely this is caused by one that is nonstandard.

**Comment by ccutrer** [comment]
The default detect resolution is 1280x720.

Exceptions are:
  doorbell (not pictured in the birdseye screenshot above): 960x720
  south_side (the portrait in the screenshot): 360x640

**Comment by NickM-27** [comment]
Are you running birdseye with all 33 cameras? Or what does that look like?

**Comment by ccutrer** [comment]
Birdseye config:

```yaml
birdseye:
  mode: objects
  width: 1920
  height: 1080
  restream: true
```

No camera is excluded from birdseye. No order overrides or anything. Cameras are all alphabetical in my config file.

**Comment by NickM-27** [comment]
Most likely the portrait will need to be capped at a certain height and not take up the entire height of the birdseye view.

**Comment by kc2zgu** [comment]
I don't like how everything is packed into the top/left corner when the entire screen isn't filled. Would it be possible to either center or spread out the images when there is extra space?

Also in some recent builds the web UI seems to shrink the view to less than the requested size even when the window is more than large enough. With 5 cameras (maybe this is a special case due to the mix of aspect ratios I'm using) and birdseye configured for 1536x864, on a 1920x1080 monitor, it ends up using maybe 15% of the total screen area for actual images, and they're all much too small to be useful. Even at 2560x1440 it gets scaled down despite having LOTS of extra room.

**Comment by NickM-27** [comment]
You'll have to be more specific. The goal with this PR is to use the entire screen. If it's not then we'd need to know your version, config, and an image of what it looks like. 

As far as the size of birdseye player; right now it's limited unless your press the Fullscreen button. There is discussion in another pr to add another button which makes the player take up the whole browser window along with the Fullscreen button

**Comment by skrashevich** [comment]
> The goal with this PR is to use the entire screen (or as much as will fit with given cameras).

In real world, this (and previous) PR reduces the canvas area used, rather than increasing :(

**Comment by NickM-27** [comment]
> > The goal with this PR is to use the entire screen (or as much as will fit with given cameras).
> 
> 
> 
> In real world, this (and previous) PR reduces the canvas area used, rather than increasing :(

Maybe in your specific setup (which was already explained above) but in many others it greatly increases it.

**Comment by kc2zgu** [comment]
I know there's a fullscreen option (although even that looks too blurry to actually be the resolution I set, so I don't know if something in the browser is downsampling then later upscaling it.) But in non-fullscreen even in cases where there is more than enough space available on the screen, and other pages use it, birdseye scales everything down unnecessarily. I'll try to find that other PR.

As for the layout itself, with >4 cameras it seems to jump to a 3-row layout which is significantly underfilled with only 5 or 6 cameras. With 4:3 cameras it gets even worse and IMO doesn't look very good (that could be just my own tastes though and not the use cases other people are going for). I wonder if it would be possible to simply scale up the entire layout once it's calculated so it fills as much space as possible. Or horizontally center each row so the odd empty space at the end doesn't always end up at the right edge.

frigate-birdseye-b668102

**Comment by kc2zgu** [comment]
The above screenshot is on a 1920x1080 screen with the browser title bar cropped out and birdseye size set to 1536x864. While it doesn't actually have quite enough vertical space in this case, it scales down much more than necessary (all the way down to 1088x612).

**Comment by NickM-27** [comment]
> > The goal with this PR is to use the entire screen (or as much as will fit with given cameras).
> 
> 
> 
> In real world, this (and previous) PR reduces the canvas area used, rather than increasing :(

Maybe in your specific setup (which was already explained above) but in many others it greatly increases it. 

Previous implementation:

Screen Shot 2023-06-16 at 15 39 42 PM

New Implementation:

Screen Shot 2023-06-16 at 15 41 18 PM

**Comment by NickM-27** [comment]
@kc2zgu to be clear, the birdseye stream is generated with your detect stream, so maybe your detect stream resolution is just too low?

**Comment by NickM-27** [comment]
While I was working on this I had it more aggressively try to fill the vertical space but that led to some cases where the horizontal space would not fit. I think I know a way to improve that now though

**Comment by kc2zgu** [comment]
Detect streams are running at equal to or higher than birdseye resolution so I don't think that's causing any problems. The player is being scaled within the browser window and I think it's being too aggressive.

**Comment by NickM-27** [comment]
> Detect streams are running at equal to or higher than birdseye resolution so I don't think that's causing any problems. The player is being scaled within the browser window and I think it's being too aggressive.

if it is blurry in fullscreen then it has nothing to do with the browser scaling, but the non-fullscreen browser scaling is the current expected behavior as I said above.

**Comment by NickM-27** [comment]
I don't really see a need to center it (but that could be something for later). Besides the centering though, I am more or less working on what you have put there now.

**Comment by NickM-27** [comment]
the main thing right now is that all cameras are being treated the same, so while more space could be used they would be bigger than other cameras of the same aspect ratio. if that limit was taken off then even more space could be used but it would lead to even more unpredictable layouts potentially

**Comment by kc2zgu** [comment]
Centering isn't a big deal, just something I thought would look a little more visually pleasing. Personally I think even an option to insert some empty space between images would be useful sometimes too.

Not filling all the space though means that when the aspect ratios of the cameras don't happen to line up well with the layout it can leave a lot of unused pixels on the table.

**Comment by NickM-27** [comment]
@kc2zgu so you have 2 16:9 cameras and 3 4:3 right?

**Comment by kc2zgu** [comment]
What I'm saying is to scale up the entire layout once it's been calculated to fill out as much unused space as possible (without changing aspect ratio). That wouldn't make any cameras proportionally larger than they are now, everything would get expanded by the same amount.

Yes, 2 cameras are 16:9 and 3 are 4:3.

**Comment by NickM-27** [comment]
> What I'm saying is to scale up the entire layout once it's been calculated to fill out as much unused space as possible (without changing aspect ratio).

yes, like I said above I had the same idea and am currently working on that. In any case, the advice from the previous birdseye PR still stands that you will find the best luck when you match the birdseye aspect ratio to match the aspect ratio of a majority of your cameras.

**Comment by NickM-27** [comment]
Here is the same layout you posted above but with the scaling up logic in place

Screen Shot 2023-06-16 at 16 27 08 PM

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate/pull/6825 - Discussion can continue here

**Pull request merged**
