### PR TITLE
Feature: Live Preview for Camera Streams

### PR DESCRIPTION
**Pull request by skrashevich**
just hover mouse over camera snapshot In main page

### CODE REVIEW

**Review by CoMPaTech — COMMENTED** [review]
Nice feature! Code LGTM

**Comment by skrashevich** [comment]
up

**Comment by mabed-fr** [comment]
Sounds interesting a reason not to approve?

**Comment by NickM-27** [comment]
The webUI is being rewritten for 0.14, in fact the camera images now update dynamically once per minute or once per second when an active object is visible on the camera.

**Comment by mabed-fr** [comment]
Amazing idea!

Should you closed the issue?

**Comment by NickM-27** [comment]
Hover to view higher fps could still be implemented and also 0.14 hasn't been merged to dev yet.

**Comment by NickM-27** [comment]
Thank you for your pull request, closing this as the new UI implements live players by default

**Pull request closed without merging**
