### PR TITLE
Change camera stats to be more structured

### PR DESCRIPTION
**Pull request by tpjanssen**

### CODE REVIEW

**Review by NickM-27 — CHANGES_REQUESTED** [review]
I don't think we want this data to be duplicated, that will create more clutter and data sent in each stats response

**Comment by tpjanssen** [comment]
What's your proposal? Remove the lop level stats (and break things)? Or close this PR, and leave every thing as is?

**Comment by NickM-27** [comment]
I think it would be best to get @blakeblackshear opinion on if this change should be done now and if so how to handle

I think breaking change would be preferred to duplicating data, frigate webUI and frigate integration would require addressing for this

**Review by NickM-27 — CHANGES_REQUESTED** [review]
You will need to fix the frontend so it pulls from the camera stats correctly

**Comment by tpjanssen** [comment]
@NickM-27 I can do this today, if you want

**Review by NickM-27 — APPROVED** [review]

**Pull request merged**
