### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by blakeblackshear**

### CODE REVIEW

**Comment by NickM-27** [comment]
@johnmarksilly Wasn't sure of the best place to put notes on #2830 so I'll try here. I built and ran on my setup and it looks awesome, but found a couple issues:

1. Works great on mobile, however on desktop the timeline and camera viewing work however when I try to actually play a video on desktop it doesn't work and just keeps showing the snapshot. Same video plays just fine on mobile.
2. Similarly, on mobile the black background makes sense but on desktop it looks out of place, wondering if on desktop it can be made to match the frigate dark theme color? I think perhaps the light theme works as expected.

**Comment by johnmarksilly** [comment]
Thanks for trying it out! Are you using an iPhone on mobile and chrome on desktop? Safari is working solidly for me both mobile and desktop. I'm having issues with how Chrome queues up the HLS playlist. I'm thinking it's not interpreting the response type correctly, but I'm not sure yet as I have just noticed it.

Yeah I had a large internal debate over the color scheme. It felt much more misplaced in my personal opinion to have the theme blue as the background as normally in the real world video is displayed on black or white backgrounds to matte the footage. It could be customized 🤷🏻‍♂️

**Comment by NickM-27** [comment]
> Thanks for trying it out! Are you using an iPhone on mobile and chrome on desktop? Safari is working solidly for me both mobile and desktop. I'm having issues with how Chrome queues up the HLS playlist. I'm thinking it's not interpreting the response type correctly, but I'm not sure yet as I have just noticed it.
> 
> Yeah I had a large internal debate over the color scheme. It felt much more misplaced in my personal opinion to have the theme blue as the background as normally in the real world video is displayed on black or white backgrounds to matte the footage. It could be customized 🤷🏻‍♂️

It was actually on Chrome for desktop and Chrome for mobile as well (iOS). I just tried it on chrome Android and that worked as well. If you have anything you want to test for desktop, let me know and I'll be happy to give it a go.

As far as the colors go, I agree it is nuanced / could go either way. Here is a screenshot of what I see for context, it feels a little disjointed (in my personal opinion). To be fair though, after using frigate for many months it is possible I am just used to the other colors ¯\_(ツ)_/¯﻿

Screen Shot 2022-02-27 at 3 58 22 PM

**Comment by NickM-27** [comment]
@johnmarksilly also just curious, are there any plans to re-implement the `Tracked Objects` section?

image

**Comment by johnmarksilly** [comment]
I was actually planning on implementing them as filters which would strip out any events that don't match the filter. So it would rebuild the timeline with just the events you are sorting for. 

I agree. I definitely struggled with the look of the black as well. I typically use the live and timeline views on my phone more than my desktop but everyone's use-case is different. It would be great to be able to customize the theme a bit too and ultimately I am looking for people to submit feedback about it.

**Comment by NickM-27** [comment]
> I was actually planning on implementing them as filters which would strip out any events that don't match the filter. So it would rebuild the timeline with just the events you are sorting for. 
> 
> I agree. I definitely struggled with the look of the black as well. I typically use the live and timeline views on my phone more than my desktop but everyone's use-case is different. It would be great to be able to customize the theme a bit too and ultimately I am looking for people to submit feedback about it. 
> 
> As for the Chrome desktop issues, it is definitely strange. I was having a hard time figuring out what was wrong with it. I'll keep looking at it as I implement more features. Hence the "experimental" flag haha. 

Yeah completely understand the experimental! :)

And cool, it's a small detail but I enjoy seeing the images for the tracker objects so I'll enjoy using it that way as well 👍

**Comment by blakeblackshear** [comment]
I am going to work on performance of some database calls and the recordings endpoint. Once that is done, I think we are ready for the first beta.

**Comment by NickM-27** [comment]
Is there anything else that needs to be addressed before beta 3 is sent out?

**Comment by NickM-27** [comment]
@johnmarksilly 

1. Curious about this as well.
2. I don't believe it does currently
3. 👍 

> Does the new sub_label actually have facial recognition enabled? I'm a bit confused how that works. Saw it in the docs, but don't really understand it.

It's an API that can be interfaced with by apps or manually , the facial recognition part is not implemented in Frigate curently. [Double Take](https://github.com/jakowenko/double-take) (facial recognition software) already has support built in such that recognized faces are automatically sent back to frigate and setting `sub_label`. It is totally 👌

**Comment by johnmarksilly** [comment]
Cool cool! That double-take project is really neat. I'll have to spend some time working with that too! Thanks for the info.

**Pull request merged**
