### PR TITLE
Add color to logs making them easier to parse

### PR DESCRIPTION
**Pull request by NickM-27**
### Before:

Screen Shot 2022-10-02 at 12 36 47 PM

### After:

Screen Shot 2022-10-02 at 13 13 03 PM

### CODE REVIEW

**Review by menkej — COMMENTED** [review]
Looks fine for me. What about the Web-Lint warning for line 67 of HistoryVideo.tsx

**Comment by menkej** [comment]
> > What about the Web-Lint warning for line 67 of HistoryVideo.tsx
> That's GitHub's built in check, we have our own lint checks which passed

Ok, fine. I dunno react (yet), I just noticed. How do you lint the web code? I just noticed the use of black for the python parts.

**Comment by NickM-27** [comment]
For python we have many parts including black, sort, mypy, and others

Web just uses the built in npm lint check

**Comment by dcousens** [comment]
This should be behind a command line flag, either `--color` or `--no-color`

**Comment by NickM-27** [comment]
> This should be behind a command line flag, either `--color` or `--no-color`

If anything it would be an option in frigate configuration, but I am curious under what circumstances one would not want it enabled?

**Comment by dcousens** [comment]
@NickM-27 if in any way you are interacting with these logs outside of viewing stdout _in a compatible tty_, colors encoded in this way can be quite annoying.

For example, `stdout` and `stderr`, if captured from Frigate as part of a `systemd` service, would already be colorized in this manner. 
Or maybe if you are parsing the logs for a particular event or error, you now need to ensure your tooling ignores color encoding.

It's bad practice, and it's why you typically see color as optional, and for things like `--color=auto`, it is using some fun tricks to ensure that the output is only colored if it is going to an interactive tty (not say, a `.log` file).

**Comment by blakeblackshear** [comment]
I agree. I have been bitten by colorized logs many times. In many programs they show up wrapped in funky unicode characters. We are gonna hate that when everyone starts posting logs that way in support requests.

**Comment by NickM-27** [comment]
Is there a different approach to adding color to logs? Perhaps one where the program displaying the logs shows the color based on the log itself?

I know in Unraid that frigate is one of the only docker containers which doesn't have colored logs, but I've also put these logs in other places (copy/paste) and not seen any unexpected characters. That leads me to believe either Unraid is doing some niceness when copying the logs or there's other methods for adding colored logs which don't rely on Unicode 🤔

**Comment by blakeblackshear** [comment]
I'm not sure. I have always tried to avoid them. Maybe we can show a log stream in frigate directly and show colors there. It should be easy enough to relay them over websockets.

**Comment by NickM-27** [comment]
That sounds better too since that'll be the main place people view from (and I assume we'll offer a copy logs button which could strip them out anyway)

**Pull request closed without merging**
