### PR TITLE
feat: Timeline UI — First Iteration

### PR DESCRIPTION
**Pull request by johnmarksilly**
### Timeline UI

Created a new _"experimental"_ UI for viewing events and live camera views

To be completed before PR is ready
- [x] Investigate using the recordings framework for faster loading (load segments instead)
- [x] Add config for using new UI
- [x] Update docs
- [x] Handle no events for today
- [x] Load first timeline entry (most recent) and scroll to that event
- [x] Play/Pause + disable arrows on end indices
- [x] Placeholder sizing while video is loading to reduce "buggy" looking element + missing image
- [x] Move timeline while video plays (timeline will be disabled while video is playing)
- [x] Add global padding back to pages (except new route)
- [x] Make sure change complies with dark mode

For the history books: https://github.com/blakeblackshear/frigate/pull/2633

### CODE REVIEW

**Comment by johnmarksilly** [comment]
I'll merge master in

**Comment by johnmarksilly** [comment]
@blakeblackshear I think this is ready to re-run

**Comment by blakeblackshear** [comment]
I am going to go ahead and merge this in. I decided to overhaul a bunch of the frontend in another branch, so I will fixup any issues I find when rebasing.

**Comment by jcastro** [comment]
How do I see this UI? I'm on 0.11 beta-2. I couldn't find anything on the docs either. Thanks!

**Comment by NickM-27** [comment]
> How do I see this UI? I'm on 0.11 beta-2. I couldn't find anything on the docs either. Thanks!

You have to add 

```
ui:
  use_experimental: true
```

In the config, then open a camera

**Comment by user897943** [comment]
> > How do I see this UI? I'm on 0.11 beta-2. I couldn't find anything on the docs either. Thanks!
> 
> You have to add
> 
> ```
> ui:
>   use_experimental: true
> ```
> 
> In the config, then open a camera

How is it supposed to look like? I don't create events (I use 24/7 always-on recording rather than event/motion based). I read somewhere in discussions that this was supposed to look similar to how Nest cameras present the timeline in their app (continuously scrollable throughout the recording history, showing flags for events (in this case events would have to be enabled). It would be helpful to see a screenshot for what it's supposed to look like.

**Comment by NickM-27** [comment]
@user897943 here are some screenshots from my dev setup

Screen Shot 2022-05-26 at 8 22 37 AM
Screen Shot 2022-05-26 at 8 22 54 AM
Screen Shot 2022-05-26 at 8 23 03 AM

**Comment by user897943** [comment]
> @user897943 here are some screenshots from my dev setup
> 
> Screen Shot 2022-05-26 at 8 22 37 AM
> 
> Screen Shot 2022-05-26 at 8 22 54 AM
> 
> Screen Shot 2022-05-26 at 8 23 03 AM

Cool! I get that after adding the key for experimental UI on the config. But I can see that it relies on events, otherwise it shows nothing... I guess it makes sense... Maybe I should get a coral to do processing, with CPU processing the server struggles when events are enabled... Good job anyway, can't wait to see how you improve that going forward :)

**Comment by NickM-27** [comment]
>  Good job anyway, can't wait to see how you improve that going forward :)

To give credit where credit is due, @johnmarksilly is the author of this feature as it is now, but I believe there will be improvements to it 👍

**Comment by BBaoVanC** [comment]
Just now tried out the 0.11.0 beta and I'm also having trouble playing video in the history tab.

Where it will play:

- Android, both Chrome & Firefox
- iPhone, Safari
- macOS, Safari

Where it won't play:

- Linux, both Chromium and Firefox
- macOS, both Firefox and Chromium

The error I get on the devices where it doesn't work is along the lines of (taken from Firefox on Linux for example):

```
Cannot play media. No decoders for requested formats: application/vnd.apple.mpegurl
```

**Comment by johnmarksilly** [comment]
> Just now tried out the 0.11.0 beta and I'm also having trouble playing video in the history tab.
> 
> Where it will play:
> 
> * Android, both Chrome & Firefox
> * iPhone, Safari
> * macOS, Safari
> 
> Where it won't play:
> 
> * Linux, both Chromium and Firefox
> * macOS, both Firefox and Chromium
> 
> The error I get on the devices where it doesn't work is along the lines of (taken from Firefox on Linux for example):
> 
> ```
> Cannot play media. No decoders for requested formats: application/vnd.apple.mpegurl
> ```

Fix PR is on the way:
https://github.com/blakeblackshear/frigate/pull/3298

**Comment by vertex-github** [comment]
👍 This looks (and works) great.  Working really well on Windows 10 / Firefox with all my cameras.  The only thing I would tweak would be to also show a long timeline activity timeline - the current view seems to show an hour - it would be helpful if I could get an at-a-glance overview of events for the last N days (perhaps displayed below the current play buttons).  If I could click on that timeline to quick jump to different days it would be awesome.

Also, would be helpful if the log output acknowledged the `experimental` setting - I wasn't sure it had taken after I added that to my config and restarted.

**Comment by vertex-github** [comment]
One issue I just noticed:  If I look at camera A in the history timeline, then select Camera B, the history timeline is not loaded correctly if there is no active event at the same point in time for Cam B.  I have to click "Live" then back to "History" and then the history is loaded correctly and the control jumps/scrolls to the most recent activity marker

**Comment by eatoff8** [comment]
Just trying out this new experimental UI today. Doesnt work on chrome or edge on my PC, but works fine on my phone (I understand there is a fix coming).

The events work fine across all cameras, but it appears I can only view events. As in my cameras that are constantly recording - I cant view the full timeline using the experimental UI, I have to go through via the recordings to view that. Is that a bug or is this working as intended? It would be great if it could be used to view both.

**Comment by johnmarksilly** [comment]
> Just trying out this new experimental UI today. Doesnt work on chrome or edge on my PC, but works fine on my phone (I understand there is a fix coming).
> 
> The events work fine across all cameras, but it appears I can only view events. As in my cameras that are constantly recording - I cant view the full timeline using the experimental UI, I have to go through via the recordings to view that. Is that a bug or is this working as intended? It would be great if it could be used to view both.

It is not a bug, but just not included. I also record 24/7 and my timeline works by pulling up the recording instead of the events individually. I haven't published this change yet because I haven't yet wrote the code to check if you have 24/7 recordings enabled or not.

There is an open pull request to merge in a fix for the other browsers.

**Comment by craigmdennis** [comment]
What happened to this? I see no reference of the experimental UI in the main repo anymore.

**Comment by NickM-27** [comment]
> What happened to this? I see no reference of the experimental UI in the main repo anymore.

It's still in release-0.11 which is in RC and hasn't been merged to master yet

**Comment by craigmdennis** [comment]
Sometimes I wish there was a facepalm emoji. 

Thanks!

**Comment by Buster14** [comment]
+1 for this, wife really like milestone xprotect's android timeline, it's the only reason I keep my windows vm.
Really helpful for non-tech savvy people. Is there any plan to implement this to the android app?

**Comment by NickM-27** [comment]
> Is there any plan to implement this to the android app?

There is no official android app, can't say about the community app.

**Comment by ericnotthered** [comment]
I'm sure I'm going to do a facepalm as well, but I'm running 0.11.1 and I don't see the "History" option.  :(

This is using MS Edge on Windows 11.

image

I'm pretty new to Frigate, so please be gentle.  :)

**Comment by NickM-27** [comment]
@ericnotthered this feature is experimental. You must enable it, see the 0.11 release notes on how to do so

**Comment by NickM-27** [comment]
If you enabled it and it's still not working, be sure to hard refresh the browser.

**Pull request merged**
