### PR TITLE
Fix Firefox oversized delete icon

### PR DESCRIPTION
**Pull request by NickM-27**
Per https://github.com/blakeblackshear/frigate/discussions/3221#discussioncomment-2776981

### CODE REVIEW

**Comment by daveonkels** [comment]
Still seeing the oversized icon issue in FF on beta3 - was there a regression?
Screenshot from 2022-06-11 08-12-34

**Comment by NickM-27** [comment]
> Still seeing the oversized icon issue in FF on beta3 - was there a regression?
> Screenshot from 2022-06-11 08-12-34
> 

Make sure you do ctrl + F5 or CMD + R to clear browser cache

**Comment by Bod1985** [comment]
I'm also seeing on Firefox for Windows despite clearing cache and history

**Comment by NickM-27** [comment]
> I'm also seeing on Firefox for Windows despite clearing cache and history

Are you on the latest version? I checked downloading firefox on mac and windows and it looks appropriately sized 🤔

**Comment by Bod1985** [comment]
> > I'm also seeing on Firefox for Windows despite clearing cache and history
> 
> Are you on the latest version? I checked downloading firefox on mac and windows and it looks appropriately sized 🤔

Sadly yes, I'm using Firefox 101.0.1 (64-bit) on Windows 10

image

**Comment by daveonkels** [comment]
Same here. Hard refresh a number of times. Icon is sized correctly in Chromium.

**Comment by deviant77** [comment]
Same here too. Firefox on Windows 11, and Firefox on Android.

> Are you on the latest version? I checked downloading firefox on mac and windows and it looks appropriately sized 🤔

Are you using the same beta-3 image as us?

Am I right in thinking the JavaScript is built at the time of the docker image build?
If so, then `/opt/frigate/web/assets/Events.9dffa921.js` in the docker image does not contain your commit.

**Comment by NickM-27** [comment]
I'm using my own build, that would explain it

**Comment by deviant77** [comment]
It could explain why a similar fix for #3230 is also missing in beta 3.

**Comment by deviant77** [comment]
> @deviant77 @daveonkels @Bod1985 Please try with the just released beta04 as it should now be fixed, let me know if it isn't. Thanks!

Yep, now fixed. Thank you!

**Comment by daveonkels** [comment]
Confirmed as well. Thanks @NickM-27

**Pull request merged**
