### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by scstraus**
Doesn't hurt to be complete with install instructions though it should be obvious to most..

### CODE REVIEW

**Comment by scstraus** [comment]
Also added a link to coral runtime installation instructions since I had overlooked that on mine for a while.

**Review by blakeblackshear — COMMENTED** [review]
You shouldn't have to do this since the runtime is included in the container. What were you running into?

**Review by scstraus — COMMENTED** [review]
Yes second link is better. Goes straight to instructions.

**Comment by scstraus** [comment]
Sorry, just noticed your comment. I was getting this before I installed the runtime:

```
frigate    | ERROR: Failed to retrieve TPU context.
frigate    | ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.
frigate    | 
frigate    | Failed in Tensor allocation, status_code: 1
```

After I installed the runtime, it didn't have this issue..  It's worth noting that I'm running Ubuntu Server in a VM under Windows. Not sure if that makes any difference. I do have the Coral passed through to the container.

**Comment by blakeblackshear** [comment]
Not sure what is different, but I haven't run into that on any of the devices I have tested so far. You can see where I am already installing the edgetpu libraries in the container here: https://github.com/blakeblackshear/frigate/blob/master/Dockerfile#L81-L89

Since it installs on the host, the only part of that install script that could even apply to Frigate would be the permissions set on the USB device, but I haven't found that to be necessary. Containers are almost completely isolated from the host. I wonder if the unplug/replug process you did during the install script is actually what fixed it.

**Comment by scstraus** [comment]
Might be.. I had plugged it in prior to installing frigate, so maybe unplugging and plugging was all that was necessary.. At any rate, I guess you can ignore that bit of the pull request unless we figure out that something above the unplugging and replugging was needed.

**Pull request closed without merging**
