### PR TITLE
fix(web): mask zone editor to handle object filter masks

### LINKED ISSUE #523: Mask config changes
The motion mask has been moved under the `motion` config entry in recent changes. Also, there are now object level masks available as filters.

```yaml
cameras:
  front_door:
    ...
    motion:
      mask: poly,0,900,1080,900,1080,1920,0,1920
    ...
    objects:
      filters:
        person:
          min_area: 5000
          threshold: 0.6
          mask: poly,574,1058,772,1072,768,632,439,636,34,600
```

Also note that I updated to a docker based build process for the frontend @paularmstrong

### PR DESCRIPTION
**Pull request by paularmstrong**
Includes additional handlers for adding/removing masks, as well as click to copy configs. 

This ended up a lot larger than anticipated due to the number of ways to configure masks, so would appreciate someone giving it a test to make sure nothing is crashing.

fixes #523

https://user-images.githubusercontent.com/33297/104775898-ff1a7180-572d-11eb-907d-2a424cd1b31c.mp4

### CODE REVIEW

**Comment by blakeblackshear** [comment]
Noticed a few things:
- When I go to drag the dots around for the mask, the dot often jumps to the left side of the image. This was happening prior to this change as well.
- My buttons don't have colors like yours
image
- Also, does snowpack support hashed versioning filenames as a part of the build? I think we are going to run into typical caching issues with the current file names.

**Comment by paularmstrong** [comment]
> When I go to drag the dots around for the mask, the dot often jumps to the left side of the image. This was happening prior to this change as well.

What browser and version? I haven't experienced this

> Also, does snowpack support hashed versioning filenames as a part of the build? I think we are going to run into typical caching issues with the current file names.

Via plugin, yes. I'll add that in this patch

**Comment by paularmstrong** [comment]
> > When I go to drag the dots around for the mask, the dot often jumps to the left side of the image. This was happening prior to this change as well.

> What browser and version? I haven't experienced this

I'm going to guess Firefox. I just fired it up and found out it doesn't work at all. ...sigh... I'll work on that separately

**Comment by blakeblackshear** [comment]
Latest Chrome actually. It may be better to comment out the link to the mask editor for now. I am hoping to get a release candidate out this weekend. We also need to be clear that the mask "editor" is not actually an "editor", but more of a tool. If not, we will generate a bunch of support requests with people asking where the save button is.

**Comment by paularmstrong** [comment]
> We also need to be clear that the mask "editor" is not actually an "editor", but more of a tool. If not, we will generate a bunch of support requests with people asking where the save button is.

How about renaming it to "mask maker" and adding instructions to the page? I had wanted to do that, but it slipped my mind

**Comment by paularmstrong** [comment]
Also, I saw you made me a contributor. Do you mind if I push changes to beta4 to fix issues or would you prefer PRs?

**Comment by blakeblackshear** [comment]
PRs for now. I am committing directly to that branch at the moment.

**Comment by blakeblackshear** [comment]
I also removed support for image mask types. Everything is configured like zones (poly only) now.

**Comment by paularmstrong** [comment]
I've rebased on latest beta4 for the Firefox fixes and added some text to the top of the page to hopefully explain that it's just a helper, not an actual editor that can save. I'm working on file hashing for cache issues separately.

**Comment by blakeblackshear** [comment]
Looks like there are some conflicts after merging your other PR.

**Comment by blakeblackshear** [comment]
Another thing to note is that the latest data for the `events` api includes `has_clip` and `has_snapshot` to indicate if there is a clip/snapshot of the event. At the moment, if there isn't clip, the video viewer loads with a missing video file. The full resolution snapshot is available at the same path as the video, but with a `.jpg` extension instead of `.mp4`.
image

**Comment by paularmstrong** [comment]
Fixed merge conflict and updated the event endpoint to not try to load a clip if it doesn't exist and shows the full-size snapshot. Will definitely spend more time on that view once things settle down a bit.

**Pull request merged**
