### PR TITLE
0.12.0 Release

### PR DESCRIPTION
**Pull request by blakeblackshear**
For this release, the *goals* are to focus on stability, diagnostics, and device compatibility. No promises, but these are the guardrails.

Docs preview: https://deploy-preview-4055--frigate-docs.netlify.app/

### Stability

- [x] Proper daylight savings time fix by switching to storing files with unix timestamps rather than YYYY-HH folders (client should specify timezone in API calls to avoid any assumptions about timezone on backend)
- [x] Ensure recording durations are a reasonable amount of time to avoid corruption
- [x] Incorporate [go2rtc](https://github.com/AlexxIT/go2rtc) to get rid of common RTMP related issues and provide new live view options
- [x] Ensure Frigate doesn't fill up storage and crash
- [x] Hwaccel presets so defaults can be updated without requiring users to change config files
- [x] Attempt to remove VOD module with a direct m3u8 playlist builder
- [x] Make MQTT optional and more gracefully handle connection failures and reconnects
- [x] Detect if segments stop being written to tmp when record is enabled and restart the ffmpeg process responsible for record

### Diagnostics/Troubleshooting

- [x] CPU/GPU stats per process per camera
- [x] Storage information (per camera too)
- [x] Logs in UI
- [x] Logs from nginx/ffmpeg/go2rtc etc more easily available
- [x] Simple pattern matching for secret scrubbing in logs, etc
- [ ] Github action to scrub secrets in issues
- [x] Ability to execute ffprobe/vainfo etc in container and get output for diagnosis
- [x] Replace green screen with helpful placeholder message
- [x] Error out on duplicate keys in config file like #4213 
- [x] More helpful output from config validation errors for things like extra keys
- [x] Show yaml config in the UI to reduce posts with json config

### Device support

- [x] TensorRT
- [x] OpenVINO

### Known issues

- [x] BASE_PATH not being properly replaced in monaco editor
- [x] When watching MSE live view on android, if you scroll down past the video and then back up, playback is broken
- [x] iOS does not support MSE, instead of loading forever should show error message
- [x] Recordings playback when selecting an hour starts playback ~10 minutes before the hour (in America/Chicago, possibly others)

### CODE REVIEW

**Comment by pdecat** [comment]
>  Proper daylight savings time fix by switching to storing files with unix timestamps rather than YYYY-HH folders (client should specify timezone in API calls to avoid any assumptions about timezone on backend)

What about keeping YYYY-HH folders but  use UTC instead to avoid DST issues?

**Comment by blakeblackshear** [comment]
> What about keeping YYYY-HH folders but use UTC instead to avoid DST issues?

That could work too

**Comment by andrew-lemon** [comment]
I like Frigate's feature where the camera's stream fills the computer screen when you click on the image of the camera's live view. This feature would really be great if it would switch over to the camera's stream identified as "rtmp" in the config file when it does this. For example, I use the low res stream for "detect", but use the high res stream for "rtmp". I would like to see the high res stream when I click on the live image to fill the screen. Would this be possible given that you're planning to incorporate go2rtc?

**Comment by blakeblackshear** [comment]
> I like Frigate's feature where the camera's stream fills the computer screen when you click on the image of the camera's live view. This feature would really be great if it would switch over to the camera's stream identified as "rtmp" in the config file when it does this. For example, I use the low res stream for "detect", but use the high res stream for "rtmp". I would like to see the high res stream when I click on the live image to fill the screen. Would this be possible given that you're planning to incorporate go2rtc?

Yes. The current live view requires decoding the video stream which would require lots of CPU. go2rtc would allow a direct passthrough of the video to the frontend so the higher resolution can be used.

**Comment by blakeblackshear** [comment]
> Given that go2rtc allows for direct passthrough of the video to the frontend, could the "camera" tab in the Frigate UI show the low res live feeds instead of snapshots as they currently do?

That's technically already possible without go2rtc. There are existing feature requests for that.

**Comment by thinkloop** [comment]
> * Proper daylight savings time fix by switching to storing files with unix timestamps rather than YYYY-HH folders (client should specify timezone in API calls to avoid any assumptions about timezone on backend)

Would this means that all the files would be in one folder?

> *What about keeping YYYY-HH folders but use UTC instead to avoid DST issues?

Personally I would much prefer this solution, unix timestamps are annoying to work with as a human.

**Comment by blakeblackshear** [comment]
> Would this means that all the files would be in one folder?

Not necessarily.
 
> Personally I would much prefer this solution, unix timestamps are annoying to work with as a human.

This will probably be just as easy, but why do you need to interact with the segment data? I think of them like internal binary blob storage for the database not intended to be used directly.

**Comment by thinkloop** [comment]
> but why do you need to interact with the segment data

That's always the dream, but in the end we still rely on our laptop fans to discover errant processes 😛. In my case I concatenated segments to make a timelapse that eneded up being exceptionally easy to accomplish given how nicely organized everything in frigate is.

**Comment by rsnodgrass** [comment]
With go2rtc being integrated directly, does this mean we can stop using the go2rtc add-on within Home Assistant? What if Frigate is running on a host other than HA how would the streams be exposed via HA when external to the network? _Thanks for continually making Frigate better!!!_

**Comment by NickM-27** [comment]
> With go2rtc being integrated directly, does this mean we can stop using the go2rtc add-on within Home Assistant? What if Frigate is running on a host other than HA how would the WebRTC streams be exposed via HA when external to the network? _Thanks for continually making Frigate better!!!_

It depends what all you're using go2rtc for. In this initial implementation not all go2rtc features will necessarily be available. There will also be some caveats with things like webRTC where you may need to run frigate as host

**Comment by LordNex** [comment]
> > It depends what all you're using go2rtc for. In this initial implementation not all go2rtc features will necessarily be available. There will also be some caveats with things like webRTC where you may need to run frigate as host
> 
> 
> 
> Basically the bare minimum just to get fast streams viewable via Home Assistant without laginess on startup. Streaming the RTMP feeds directly through HA from separate Frigate host are slow. Planned to use go2rtc to provide WebRTC stream that was much faster via the Frigate lovelace card/integration.

To bad it doesn't work well with UI generators like Dwain's Dashboard. This last rebuild of HA I went with it just as an ease of use case setup. Boy I wish I wouldn't and had just shard coded the yaml. Given DD is nice and looks well. But very prone to bugs and breaks with updates, can't work with some outside plugins like WebRTC's card, and lack of any real follow through development that would allow it to work with WebRTC

I tried adding it and it broke the setup to where I could not remove it except by manually editing the file.

**Comment by LordNex** [comment]
Can't wait to see TensorRT. I would love to have Frigate on my 4gig Jetson Nano with the Coral TPU attached to be able to get the best out of the object detection while also having a GPU to encode and decode streams.

**Comment by NickM-27** [comment]
> Can't wait to see TensorRT. I would love to have Frigate on my 4gig Jetson Nano with the Coral TPU attached to be able to get the best out of the object detection while also having a GPU to encode and decode streams. 

I'm confused, that setup wouldn't use TensorRT unless you mean using that and a coral.

What you're describing should be possible today.

**Comment by kdill00** [comment]
Yeah you should already to be able to accomplish what you stated. Tensorrt is to use the GPU for detection. Jetsons have an nvdec chip in them. You should be able follow nvidia hwaccel docs to get where you want. Let me know if you have any questions or trouble.  If you have performance issues, apply the settings -threads 1 -surfaces 10 in this line: -c:v h264 -threads 1 -surfaces 10

this will limit the decoding hardware to the minimum required memory needed for a successful decode. (According to NVIDIA docs 8 is the minimum needed for full fps decode so you can probably get away with less if needed, play with it). I don’t know if the one you have has DLA cores or what but if their are multiple GPUs displayed when you do nvidia-smi you need to add -gpus “corresponding GPU number”. So your hwaccel should look like -c:v h264_cuvid -gpus “1” -threads 1 -surfaces 10    

-gpus setting not needed if only a single one or the one you want to use is GPU 0. If it doesn’t work let me know as their is another way to engage nvidia hw decoding with ffmpeg if this does not work. It’s just consumes more memory on the gpu and isn’t ideal unless all work is staying on the GPU which with frigate it current doesn’t.

**Comment by user897943** [comment]
Awesome!!! Finally storage management.. can't wait!! please allow the amount of space to be personalized, I mean a setting like: "recordings_autodelete_max_storage_percent=80" meaning "fill up to 80% of my drive and then live auto-delete the oldest recordings, always keeping the latest footage". The 80% includes system files, app data, etc not just frigate. Further, it would be nice to dedicate a whole drive/partition to frigate and still specify a percentage to keep some space spare for whatever reason. Also, different strategies to manage space such as: auto delete oldest to record newest, or stop recording but warn, or "smart storage", for example based on the current available space fill as much as possible up to 90% then if the user starts writing to the hard drive and filling up, auto delete old footage to release space for user files up to a configurable timeframe for recordings, for example "keep at least 1 day/24hrs, more if possible". Adjust the available space based on the total storage partition available storage %. That would allow users to prioritize either personal files OR recordings, and decide if they wanna stop recordings or let Frigate auto delete older footage. As for important footage, do what car dashcams have done for years: allow the user to "flag" a specific timeframe as a locked file and then DO NOT auto delete that file, basically a way to protect something from being automatically deleted by the storage manager by flagging it as important. Would also be amazing to have a way to select a timeframe using day/month/year hour:minute START and END then hit export and get a download of that timescale between START date/time and END date/time. So if someone comes and asks for footage starting at 27/10/2022 10:45PM and 28/10/2022 01:05AM you can specify that on the camera recordings page, hit export and Frigate uses ffmpeg to merge the recordings and downloads just that timeframe.

**Comment by NickM-27** [comment]
@user897943 all of these are potential future improvements, but as the release goals at the top show: the focus for 0.12 is to have frigate be more stable in this case meaning not crash and continue to record even when storage is almost full.

**Comment by user897943** [comment]
Awesome but what strategy will be used to manage?

**Comment by NickM-27** [comment]
> Awesome but what strategy will be used to manage?

As was implemented in https://github.com/blakeblackshear/frigate/pull/3942 if frigate detects that there is not enough space for 1 hour of recordings then frigate will delete recordings from oldest to newest until there is a total space for 2 hours of recording and continue this cycle. If a user fills their storage with unrelated files and frigate has no more recordings to delete then it will not crash on being unable to move recording to the recordings drive.

**Comment by user897943** [comment]
> > Awesome but what strategy will be used to manage?
> 
> As was implemented in #3942 if frigate detects that there is not enough space for 1 hour of recordings then frigate will delete recordings from oldest to newest until there is a total space for 2 hours of recording and continue this cycle. If a user fills their storage with unrelated files and frigate has no more recordings to delete then it will not crash on being unable to move recording to the recordings drive.

That's a very good start!!! Brilliant :) but if it doesn't crash at least it should notify. Is there a way to implement some sort of SMTP/email notification system so that Frigate can warn when it's out of space? Because crashing is definitely a way to find out but worse is it not crashing and the user is thinking that there's space when there isn't... Definitely need a way to notify about warnings and errors.

**Comment by felalex** [comment]
Hi everyone,

I see that it's planned for the next release to support GPU inferencing with TensorRT. 
I've been wondering regarding whether it's also planned to support using both GPU (TensorRT) and Coral for inferencing at the same time. 
Something like :
detectors:
  coral:
    type: edgetpu
    device: usb
  cuda:
    type: tensorrt

If so, then it will probably require different models,  per detector type (I presume no one will want a different model for different instances of the same detector type).

So then the config will probably have to look like:

detectors:
  coral:
    type: edgetpu
    device: usb
    model:  < optional model config>
  cuda:
    type: tensorrt
    model: <model config>

Is that something being considered?

**Comment by blakeblackshear** [comment]
> I've been wondering regarding whether it's also planned to support using both GPU (TensorRT) and Coral for inferencing at the same time

Yes. A mixed set of detectors is already supported.

**Comment by NateMeyer** [comment]
> > I've been wondering regarding whether it's also planned to support using both GPU (TensorRT) and Coral for inferencing at the same time
> 
> Yes. A mixed set of detectors is already supported.

For a mixed set of detectors, I think the model configuration will be detector-framework-specific.  Do we need to tweak the model config to account for this?

**Comment by blakeblackshear** [comment]
> For a mixed set of detectors, I think the model configuration will be detector-framework-specific. Do we need to tweak the model config to account for this?

I think that will be necessary, yea. Perhaps the model config should now be nested under the detector.

**Comment by LordNex** [comment]
> Yeah you should already to be able to accomplish what you stated. Tensorrt is to use the GPU for detection. Jetsons have an nvdec chip in them. You should be able follow nvidia hwaccel docs to get where you want. If you have performance issues, apply the settings -threads 1 -surfaces 10 in this line: -c:v h264_cuvid -threads 1 -surfaces 10
> 
> 
> 
> this will limit the decoding hardware to the minimum required memory needed for a successful decode. (According to NVIDIA docs 8 surfaces is the minimum needed for a good decode so you can probably get away with less if needed, play with it). I don’t know if the one you have has DLA cores or what but if their are multiple GPUs displayed when you do nvidia-smi you need to add -gpus “corresponding GPU number”. So your hwaccel should look like -c:v h264_cuvid -gpus “1” -threads 1 -surfaces 10    
> 
> 
> 
> -gpus setting not needed if only a single one or the one you want to use is GPU 0. If it doesn’t work let me know as their is another way to engage nvidia hw decoding with ffmpeg if this does not work. It’s just consumes more memory on the gpu and isn’t ideal unless all work is staying on the GPU which with frigate it current doesn’t. 
> 
> 
> 
> The other setting nvidia explicitly recommends when decoding with ffmpeg is -vsync 0 before the hwaccel args to prevent NVDEC from accidentally duplicated frames when it shouldnt.  I have not really seen much of a difference either way with that setting but it is stated it should always be used when decoding if possible.

Thank you for such a detailed explanation. I'm going to give it a try here soon( have to disassemble the case to get to the SD Card ). I'll start from scratch with the Jetson Nano SDK Image and try and add from there. Mine is the 4 gig Nano that was out prior to the big chip shortage and I know it has a buttload of CUDA cores. But I'm not sure about DLA cores, I'll have to check. But I don't remember it showing multiple GPUs when running jtop. 

Currently I've been having pretty good success just utilizing my 40 core PowerEdge R620 and the TPU attached to a passed through usb adapter. I'm then leveraging DoubleTake and CompreFace on my Home Assistant install for recognition and final verifications. So all I'm looking for Frigate to do is the heavy NVR load, RTMP, go2rtc, or decoding/encoding of stream feeds to Home Assistant and devices, and then utilize the TPU for recognition of Person, Face, or Car and send those to DoubleTake via MQTT for processing. 

Ultimately I would love to see added ability probably from DoubleTake to take URLs and "scrap" images with the corresponding information and present that as well. Places such as the Sex Offenders List, Departmental of Corrections, and Social Media should allow us to be able to detect who is at our door and as much information as possible before we open the door. I know networking and IT like the back of my hand but I wouldn't consider myself a programmer by any means. Although I'm trying to learn.

**Comment by bagobones** [comment]
> 
> > Personally I would much prefer this solution, unix timestamps are annoying to work with as a human.
> 
> This will probably be just as easy, but why do you need to interact with the segment data? I think of them like internal binary blob storage for the database not intended to be used directly.

As per some of my feature requests I GREATLY prefer self documented files that don't depend on the Application OR the DB to work to function.. Having a logical / human readable / searchable file system means I could backup a days worth of videos without needing Frigate to view them or know when they were made or if the DB corrupts or something I still can go back through historic videos with file system search and a video player.

**Comment by invisible999** [comment]
> Thank you for such a detailed explanation. I'm going to give it a try here soon( have to disassemble the case to get to the SD Card ). I'll start from scratch with the Jetson Nano SDK Image and try and add from there. Mine is the 4 gig Nano that was out prior to the big chip shortage and I know it has a buttload of CUDA cores. But I'm not sure about DLA cores, I'll have to check. But I don't remember it showing multiple GPUs when running jtop.

Replied to you in another thread - please share the outcome. I also have Nano 4GB sitting waiting for good use and GPU-accelerated object detection with HA would be the perfect use of it.

**Comment by felipecrs** [comment]
With the new presets option, perhaps the following can also be squeezed into 0.12?

- https://github.com/blakeblackshear/frigate/issues/4369

**Comment by NickM-27** [comment]
> With the new presets option, perhaps the following can also be squeezed into 0.12?
> 
> - https://github.com/blakeblackshear/frigate/issues/4369

Feel free to make a PR

**Comment by herostrat** [comment]
@NickM-27 man you are on fire.
Thank you very very much for fixing and implementing one feature after another. I really look forward every day to peek into the commits to see what you and blake did this time 😄 

Thank you ❤️‍🔥

**Comment by LordNex** [comment]
> @NickM-27 man you are on fire.
> 
> Thank you very very much for fixing and implementing one feature after another. I really look forward every day to peek into the commits to see what you and blake did this time 😄 
> 
> 
> 
> Thank you ❤️‍🔥 

Ditto here. I can't wait to beta test this out!

**Comment by nickp27** [comment]
Hi there, I have been running a 0.12 preview build but just started getting this frigate.util errors turning up in the logs tonight. They don't seem to be affecting functionality as yet. I can't see what they relate to either.

image

**Comment by NickM-27** [comment]
> Hi there, I have been running a 0.12 preview build but just started getting this frigate.util errors turning up in the logs tonight. They don't seem to be affecting functionality as yet. I can't see what they relate to either.
> 
> image
> 

What hardware are you running and what exact version of 0.12 are you running? It might be stats for Intel hwaccel but the empty logs should have been fixed in a recent commit 2 days ago.

**Comment by roger-** [comment]
Looking forward to testing out all the great changes. 

Is there a link to a preview docker build for 0.12? And any plans for a release date?

**Comment by NickM-27** [comment]
> Looking forward to testing out all the great changes. 
> 
> Is there a link to a preview docker build for 0.12? And any plans for a release date?

Check the packages on the main frigate page, that's where the dev builds are. And there's going to be a beta before the release.

**Comment by NickM-27** [comment]
> Thanks for the great work on Frigate !
> 
> I've tried dev-45c43d7 and I'm experiencing a strange thing: I have 6 cameras in the config, working great with 0.11. I've made the change to use `restream` option for each of them for 0.11 dev, and for two of them, not sure why, I have the placeholder message displayed with the following error in the log:
> 
> ```
> 2022-12-13 19:07:38.266687545  [2022-12-13 19:07:38] frigate.video                  ERROR   : view1: Unable to read frames from ffmpeg process.
> 2022-12-13 19:07:38.266711412  [2022-12-13 19:07:38] frigate.video                  ERROR   : view1: ffmpeg process is not running. exiting capture thread...
> 2022-12-13 19:07:38.363755803  [2022-12-13 19:07:38] frigate.video                  ERROR   : view2: Unable to read frames from ffmpeg process.
> 2022-12-13 19:07:38.363839858  [2022-12-13 19:07:38] frigate.video                  ERROR   : view2: ffmpeg process is not running. exiting capture thread...
> 2022-12-13 19:07:40.967537814  [2022-12-13 19:07:40] watchdog.view2           ERROR   : Ffmpeg process crashed unexpectedly for view2.
> 2022-12-13 19:07:40.967626572  [2022-12-13 19:07:40] watchdog.view2           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> 2022-12-13 19:07:40.967678009  [2022-12-13 19:07:40] watchdog.view1           ERROR   : Ffmpeg process crashed unexpectedly for view1.
> 2022-12-13 19:07:40.972056763  [2022-12-13 19:07:40] ffmpeg.view2.detect      ERROR   : [rtsp @ 0x56174aaec840] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
> 2022-12-13 19:07:40.972165835  [2022-12-13 19:07:40] watchdog.view1           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> 2022-12-13 19:07:40.972234959  [2022-12-13 19:07:40] ffmpeg.view2.detect      ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> 2022-12-13 19:07:40.972287893  [2022-12-13 19:07:40] ffmpeg.view2.detect      ERROR   : Output file #0 does not contain any stream
> 2022-12-13 19:07:40.972336768  [2022-12-13 19:07:40] ffmpeg.view1.detect      ERROR   : [rtsp @ 0x56208bda4840] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
> 2022-12-13 19:07:40.972388509  [2022-12-13 19:07:40] ffmpeg.view1.detect      ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
> 2022-12-13 19:07:40.972459406  [2022-12-13 19:07:40] ffmpeg.view1.detect      ERROR   : Output file #0 does not contain any stream
> ```
> 
> Then, those two cameras will not be displayed until I click on the `ffprobe` button for those two cameras on the new `/system` page. After clicking on the `ffprobe` button, the cameras are displayed.

The restream option doesn't affect the cameras running in frigate, unless you changed your config and where the cameras are pointing? Creating an issue and answering those questions would probably be better

**Comment by user897943** [comment]
Off topic, but I want to thank you and others pushing code for .12. 😍 Happy belated Xmas and a great New Year. Thanks for making Frigate and maintaining it in such a timely way!

**Comment by baylanger** [comment]
Like others, definitely eager to see 0.12 out to everyone.

Per the original post, the following remain to be completed.

1. Github action to scrub secrets in issues - Something I could definitely do 🤔 :)
  Ref : https://docs.github.com/en/enterprise-cloud@latest/code-security/secret-scanning/configuring-secret-scanning-for-your-repositories
2. TensorRT
3. Recording playback "before the hour" bug.

TensorRT being the support of a new device, is there a possibility of a beta release w/o TensorRT?

**Comment by NickM-27** [comment]
> Like others, definitely eager to see 0.12 out to everyone.
> 
> 
> 
> Per the original post, the following remain to be completed.
> 
> 
> 
> 1. Github action to scrub secrets in issues - Something I could definitely do 🤔 :)
> 
>   Ref : https://docs.github.com/en/enterprise-cloud@latest/code-security/secret-scanning/configuring-secret-scanning-for-your-repositories
> 
> 2. TensorRT
> 
> 3. Recording playback "before the hour" bug.
> 
> 
> 
> TensorRT being the support of a new device, is there a possibility of a beta release w/o TensorRT?

I don't think this is necessary, the tensorrt is already in PR and it's better to have everything consistent so we know what issues come from where. 

If you're that eager to try 0.12 there's already dev images available.

**Comment by baylanger** [comment]
> If you're that eager to try 0.12 there's already dev images available.
>
I look on hub docker for the dev images... so the reason for the request.

I just noticed this PR's "build+post" job. It's currently running. Whenever it succeeds, I guess the logs will guide me to the image.

**Comment by NickM-27** [comment]
The images are here: https://github.com/blakeblackshear/frigate/pkgs/container/frigate

**Comment by Rob-Powell** [comment]
is it possible to allow transcoding of the restream into another format? due to low support for h265 i would like to transcode rather than just copy the stream.  i.e from restream source (h265) transcoded into recording and for live viewing (h264)

**Comment by NickM-27** [comment]
> is it possible to allow transcoding of the restream into another format? due to low support for h265 i would like to transcode rather than just copy the stream.  i.e from restream source (h265) transcoded into recording and for live viewing (h264)

Yes but it needs to be done by setting the camera up manually with the frigate-go2rtc file as explained in the beta docs.

**Comment by Rob-Powell** [comment]
> > is it possible to allow transcoding of the restream into another format? due to low support for h265 i would like to transcode rather than just copy the stream.  i.e from restream source (h265) transcoded into recording and for live viewing (h264)
> 
> Yes but it needs to be done by setting the camera up manually with the frigate-go2rtc file as explained in the beta docs.

Thanks Nick - went down a bit of a rabbit hole but managed to get it working. I had to modify the contents of restream.py to convert video to h264 and then add the #hardware=cuda flag for go2rtc as well as pull the dev release to get version .6 of gortc with the fixed hardware support. Works great now and amazing work on the .12 release many awesome improvements for the community.

Would it be better to add a gortc_args param to the config file under each camera stream and then pass this arg through so users could more easily override if needed? I would be happy to contribute a PR if this is the way you want to go.

**Comment by NickM-27** [comment]
@Rob-Powell we want the restream to be transparent so there should be nothing implementation specific (nothing specific to go2rtc in the config itself). There are a number of needs to transcoding so I have added that https://github.com/blakeblackshear/frigate/pull/4876 and the `#hardware` will be detected automatically with hwaccel ffmpeg presets

**Comment by LordNex** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/blakeblackshear/reviewers)

**Review by NickM-27 — APPROVED** [review]

**Pull request merged**
