### PR TITLE
Upgrade TensorRT to 8.6.1

### PR DESCRIPTION
**Pull request by NateMeyer**
This pull request updates the TensorRT libraries to 8.6.1 and the Cuda libraries to 12.1 in order to support the latest GPUs from Nvidia. Should address Issue #6666 

This update also is able to do the model conversion from within the frigate image, which allows us to integrate it into the startup scripts.

Tasks:

- [x] Update Libraries
- [x] Update scripts to convert models locally
- [x] Setup scripts to convert models automatically
- [x] Update documentation
- [ ] Testing

### CODE REVIEW

**Comment by NateMeyer** [comment]
If someone has a Maxwell card (GTX 900 series or equivalent Quadro) I would appreciate some help testing this.  I'm not confident if the latest libraries work on Maxwell, but I think they should.

image: ghcr.io/natemeyer/frigate:0.13-7155cc4-tensorrt

To download/convert yolo model:

```bash
docker run --gpus=all --rm -it -v `pwd`/trt-models:/trt-models -e USE_FP16=false --entrypoint /bin/bash ghcr.io/natemeyer/frigate:0.13-7155cc4-tensorrt /tensorrt_models.sh
```

**Comment by NickM-27** [comment]
The model cache should be in /config https://github.com/blakeblackshear/frigate/blob/9e531b0b5bf34634dc6c44e7eca7e5eaf5a52a25/frigate/const.py#L3

**Comment by NateMeyer** [comment]
> The model cache should be in /config
> 
> https://github.com/blakeblackshear/frigate/blob/9e531b0b5bf34634dc6c44e7eca7e5eaf5a52a25/frigate/const.py#L3

Sure, I'll update that in the script and the docs I just pushed.

**Comment by NateMeyer** [comment]
I've run into an issue where the trt-model-prepare task times out and I can't figure out how to make s6-rc wait longer for the model conversion script to finish.  From what I can tell, it is supposed to wait forever for the oneshot to complete.  I tried adding a 10 minute `timeout-up` file, but that didn't change the behavior at all.

Is there anyone more familiar with s6-rc who is able to provide some insight?

**Comment by NickM-27** [comment]
@felipecrs do you know what's going on here?

**Comment by felipecrs** [comment]
@NateMeyer my understanding is the same as yours, s6 was supposed to wait forever for oneshots to complete.

I would recommend you open an issue in the s6-overlay repository, usually they are very helpful.

Another thing you can try is to move the oneshot logic to the longrun service logic, so that you can  perform whatever you need before actually running the service.

**Comment by NateMeyer** [comment]
> 
> I would recommend you open an issue in the s6-overlay repository, usually they are very helpful.
> 

Thanks, this was helpful and pointed me in the right direction.  Turns out there is an environment variable for changing the default timeout.  This variable is now set only for the tensorrt image.  Tested and was able to generate a model now during init.  This solution adds a couple minutes to the first start but should be much less painful than the other preconditions.

Unfortunately, I'm not too hopeful this will work on the Maxwell cards.  I may have to roll back to 8.5.3 instead.

Also, thinking ahead we might want to nest these models in a version folder inside the model cache.  Any changes to the TensorRT libraries in future versions will need models to be regenerated, and we could do that automatically if we keep them in dedicated folders. Thoughts?

**Comment by NickM-27** [comment]
I would suggest making it a tensort_version specific to make it obvious, but yeah that seems reasonable to me.

**Comment by NateMeyer** [comment]
I've hit a slight snag on the TensorRT stuff last week.  I updated my gpu driver and my PC hard crashes whenever it does object detection.  I've found a driver version I can roll back to for now, but I'm opening a thread on NVidia's forums for them to take a look too.  

I'll probably update the PR this weekend with a branch using 8.5 instead of 8.6 that I think works for Maxwell cards.

**Comment by NateMeyer** [comment]
Closing this in favor of #7006

**Pull request closed without merging**
