### PR TITLE
Scale birdseye layout up to max size after it has been calculated

### PR DESCRIPTION
**Pull request by NickM-27**
Once the layout is calculated, find if the width and height have available space and if so scale the entire layout to fit the smaller bound

### CODE REVIEW

**Review by blakeblackshear — APPROVED** [review]

**Comment by vertex-github** [comment]
Ive got 10 cameras and this new layout makes all my birdsview views small. I did have a detect block set for each camera, and it resulted in a small view.  Ive just removed all those (using default global detect width/height) and restarted (latest 13 beta 2) and the birdseye view is jamming all the images up into the top row (7 across the width) and 3 across the 2nd row.  There's plenty of space available - easily more than 50% available on screen.  Switching to full screen results in the same layout and camera view size with black padding on left/right of the two rows)

**Comment by NickM-27** [comment]
> Switching to full screen results in the same layout and camera view size with black padding on left/right of the two rows). Changing browser window size doesnt have any impact on displayed image size - no scaling going on. Im running on a 4K screen with continuous birdseye mode

that's expected, birdseye is created on the backend and based on the configured birdseye resolution -- not the resolution of the display that it is being displayed on

as far as layout issues go, I'd need to know what you have set for camera detect resolutions and for birdseye resolution

**Comment by vertex-github** [comment]
Ive removed all camera detect resolutions (I believe in the new builds its
auto-detected? )  Do you need the actual detected resolutions?
I have not set any birdseye width/height in my config.

**Comment by vertex-github** [comment]
Camera name - resolution:
K - 640x480
B - 640x480
OF - 640x480
OU - 640x480
D - 640x360 (sic)
G1 - ffprobe is failing (from UI)
G2 - 600x800
G3 - 640x480
H - 1280x720 (no substream on this)

**Comment by NickM-27** [comment]
I've identified an issue with 4:3 cameras and how the layout is scaled after it is calculated

**Comment by vertex-github** [comment]
Awesome. Could I specify an ordering and work around this problem until the
next beta comes out?

N

**Comment by NickM-27** [comment]
if you remove the portrait camera (600x800) I would expect that it would work a lot better.

**Pull request merged**
