### PR TITLE
Update ESXi documentation to point to latest instructions

### PR DESCRIPTION
**Pull request by lamw**
This change updates the current ESXi documentation to point to the latest instructions for setting up Frigate (in container) running on ESXi and consuming both Coral USB TPU and iGPU passthrough which was just published at https://williamlam.com/2023/05/frigate-nvr-with-coral-tpu-igpu-passthrough-using-esxi-on-intel-nuc.html

### CODE REVIEW

**Review by NickM-27 — DISMISSED** [review]

**Comment by blakeblackshear** [comment]
Should this target master?

**Comment by lamw** [comment]
@blakeblackshear Happy to change, if I didn't pick right branch. I wasn't sure if promotion in master was done as part of your release process?

**Comment by lamw** [comment]
@blakeblackshear Looks like I had only cloned `dev` branch when I had forked repo, should I have checked out master and then submitted the doc PR against that? Not sure if that screwed something up ... I may need to close and re-open

**Comment by blakeblackshear** [comment]
You can probably rebase on master and force push.

**Pull request closed without merging**
