### PR TITLE
GenAI: add ability to save JPGs sent to provider

### PR DESCRIPTION
**Pull request by leccelecce**
## Proposed change
This adds a config option `save_thumbnails` to GenAI config, which will write JPGs out to the clips directory. It's disabled by default.

Purpose is to help debug GenAI results. I'm already seeing some interesting things like multiple blank thumbnails being sent.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code
- [ ] Documentation Update

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 

## Checklist

- [X] The code change is tested and works locally.
- [X] Local tests pass. **Your PR cannot be merged unless tests pass**
- [X] There is no commented out code in this PR.
- [X] The code has been formatted using Ruff (`ruff format frigate`)

### CODE REVIEW

**Comment by hawkeye217** [comment]
Curious what the other maintainers would say, but this is more of a debug feature in my opinion and shouldn't be user-facing through the config because it has the potential to write a lot of images with no automated cleanup mechanism. 

Perhaps it can be something like our object track debugging code, which can just be set to `True` in code.

https://github.com/blakeblackshear/frigate/blob/87e7b62c851b2cfbe79e310fb5e4276214f063ee/frigate/video.py#L758

**Comment by leccelecce** [comment]
Thank you for the review. I see what you mean. Code changes are a bit of a barrier for most though.

Is there any other middle ground perhaps for enabling debugging, like env vars or a command line flag?

**Comment by leccelecce** [comment]
If a key concern is leaving leftovers files, happy to look at implementing a clean-up when events are expired so they don't build up.

**Comment by NickM-27** [comment]
In my opinion this is a bit different than Frigate's internal debug because the user doesn't have much control over Frigate's internal object tracking behaviors while a user has direct control over their preferred genai provider and its prompt.

This is something that most users won't be using, especially after things are working in a satisfactory manner. This is a debug capability to an additional UI / object information feature. Personally, I think it makes most sense as:
- the config option renamed to explicitly designate it as a debug option
- instead of some event or time based retention, change the config option to be an integer for the number of "thumbnail stacks" to keep. So that way as a user I can specify I want to keep the last 2 sets of thumbnails that were sent so that I can investigate.

**Comment by NickM-27** [comment]
I'd also be fine if it wasn't cleaned up by default, but with the option designated as a debug feature it will be more clear that this is a user function and not a default frigate function

**Comment by hawkeye217** [comment]
> I'd also be fine if it wasn't cleaned up by default, but with the option designated as a debug feature it will be more clear that this is a user function and not a default frigate function

I'm fine with that too.

I'd also prefer to leave it out of the main genai docs and only keep it in the reference config, like other options we provide.

**Comment by leccelecce** [comment]
Thank you for all the feedback, I understand all of these points. One question before I update the PR:

Nick, to your point on only keeping a handful of thumbnail stacks. Currently the thumbnails are held only in memory This means that if you want to change any config and restart you can't regenerate (unless I'm missing something and config can be reloaded on the fly?). I would like to in future send a PR for that, so that if thumbnails have been saved (and the event not expired) they can be re-sent to regenerate rather than using a single thumbnail or snapshot. This would still be possible if limiting to a number of thumbnail stacks but less predictable.

**Comment by NickM-27** [comment]
I'd suggest changing the folder structure to be `clips/genai-requests/{event_id}/{1.jpg}`

**Comment by leccelecce** [comment]
Updated as requested and locally re-tested.

**Review by NickM-27 — APPROVED** [review]

**Review by hawkeye217 — APPROVED** [review]

**Pull request merged**
