### PR TITLE
Auto approve dependabot PRs

### PR DESCRIPTION
**Pull request by felipecrs**
This repository requires at least one approval before merging, enabling auto-merge isn't enough. I hope this works. :)

### CODE REVIEW

**Comment by blakeblackshear** [comment]
I am going to wait on this until after we release 0.12.0. I want to minimize volatility even for dev dependencies for now.

**Comment by felipecrs** [comment]
Sure, ok.

**Comment by NateMeyer** [comment]
I'm a little concerned what dependabot will do with the TensorRT and Cuda libraries.  These may need to be reworked a little bit at some point.  So far GPU compatibility with the 0.12 betas seems to be pretty good, except for a few questions around some of the UnRaid drivers.  We'll want to be careful not to drop compatibility with any of the Cuda upgrades?

**Comment by felipecrs** [comment]
But they are not dev dependencies, are they? This workflow only auto approves minor upgrades of dev deps.

**Comment by NateMeyer** [comment]
> But they are not dev dependencies, are they? This workflow only auto approves minor upgrades of dev deps.

Ah, didn't realize this was just for dev. Where is that determined which packages are development?

**Comment by felipecrs** [comment]
I think dependabot takes into account the name of the requirements file, like [requirements-dev.txt](https://github.com/blakeblackshear/frigate/blob/dev/requirements-dev.txt).

**Comment by felipecrs** [comment]
Well apparently dependabot only supports requirements.txt and no other file. I suppose it will treat it as a production dependency.

The way would be to convert to something like Poetry, with pyproject.toml that have different sections for production and development dependencies like npm does.

**Review by blakeblackshear — APPROVED** [review]

**Comment by CoMPaTech** [comment]
@felipecrs I just switched some of our projects to renovate to accomplish some of this (while also supporting pre-commit and poetry the like). It's not native, though it is available to public projects. (Not affiliated, just mentioning)

**Comment by felipecrs** [comment]
@CoMPaTech yeah, Renovate is million times better and allows us to upgraded way more dependencies than just Python or Node.js ones (like go2rtc, nginx in Dockerfile for example).

I would advise everyone to use Renovate, but on the other hand the entry barrier is higher than dependabot, since dependabot is from GitHub.

**Pull request merged**
