### PR TITLE
Add any option to birdseye

### PR DESCRIPTION
**Pull request by NPutting**
Adding an `any` option to Birdseye that is a combination of both motion and object.

I prefer to use motion for my Birdseye streams, however, it doesn't show me my dogs when they're sleeping. This should allow for the best of both. 

I'm welcome to any feedback on the naming as well as `any` was the best I could think of.

### CODE REVIEW

**Comment by NickM-27** [comment]
I don't think there is a need for this. The current birdseye `object` mode will show the camera if it has seen an active object in the last 30 seconds (which requires motion). So the `motion` mode would already cover this case. I don't see any case where there has not been motion but an object is active.

**Comment by NickM-27** [comment]
(sorry, didn't mean to close)

**Comment by NickM-27** [comment]
It seems like what you're actually after is a mode which shows a birdseye stream when `stationary` objects are still being detected

**Comment by NPutting** [comment]
To clarify the use case, there are some things that trigger `motion` for me like a gate being left open and swinging or a roomba moving around that wouldn't be triggered by `object`. However I also want to see stationary objects as well as they can be of interest even when not triggering motion.

**Comment by NickM-27** [comment]
> To clarify the use case, there are some things that trigger `motion` for me like a gate being left open and swinging or a roomba moving around that wouldn't be triggered by `object`. However I also want to see stationary objects as well as they can be of interest even when not triggering motion. 

I think you're misunderstanding my point which is that the current implementation of the birdseye `objects` type will only show the camera if it sees an ACTIVE object in the last 30 seconds. 

This PR would not change the birdseye behavior and would not show your sleeping dogs.

**Comment by NPutting** [comment]
Got it, I do believe that was a misunderstanding on my part that stationary objects still counted as active objects as used in Birdseye. I'll close out this PR and I'll see about implementing an option that includes stationary objects before adding an any option. 

Thanks for the extremely quick feedback!

**Pull request closed without merging**
