### PR TITLE
Use reolink preset for http go2rtc input args

### PR DESCRIPTION
**Pull request by NickM-27**
In frigate 0.11 it was found that the nobuffer arg caused issues with reolink and other http streams. Go2rtc sets this and I believe that may be part of the stability issues when using with ffmpeg.

### CODE REVIEW

**Comment by blakeblackshear** [comment]
So this sets the ffmpeg args for go2rtc? What if you have a mix of Reolink and non-Reolink cameras?

**Comment by NickM-27** [comment]
> So this sets the ffmpeg args for go2rtc? What if you have a mix of Reolink and non-Reolink cameras?

it sets the ffmpeg args for go2rtc for http streams only. go2rtc config (by default) has different input args for http / rtsp https://github.com/AlexxIT/go2rtc/wiki/Configuration#defaults

I tried these args with an mjpeg http stream as well so I don't think they should cause issues in either case

**Comment by NickM-27** [comment]
I can see why this may not be the best idea as it may not work as well with other types of http streams. Perhaps should hold off for now?

**Comment by AlexxIT** [comment]
You can add your own input formats (rtsp/http/file...) starting from v1.2.0 (param `#input=...`)
https://github.com/AlexxIT/go2rtc#source-ffmpeg

**Pull request closed without merging**
