### PR TITLE
add: Export button to events UI

### PR DESCRIPTION
**Pull request by PovilasID**
I added a export button to events UI. It adds a clip to exports list directly. 
image
It is next to the downloads button.
For now it rounds the clip time to nearest second but if/then #7314 is merged I will update it to just pass the accurate start/end times.

### CODE REVIEW

**Comment by NickM-27** [comment]
Is there a reason why you'd want to do that vs just downloading?

**Comment by PovilasID** [comment]
> Is there a reason why you'd want to do that vs just downloading?

Personally I will mount the exports folder to remote NAS :D so it will work as remote backup.
More broadly you may want to save the footage by adding them to export list.

**Comment by NickM-27** [comment]
Gotcha, I think this would be better as an option inside the download button menu and not as a separate button. It is not clear what the difference is between these two without a label

**Comment by PovilasID** [comment]
> Gotcha, I think this would be better as an option inside the download button menu and not as a separate button. It is not clear what the difference is between these two without a label

I personally think that then you press a download button it does not start the download and instead opens a menu is flawed design in, so I would prefer not add something else to that menu.
I do agree that it being icon only is ambiguous of what that button does, so will try some other visuals.

**Comment by NickM-27** [comment]
That's the current design of frigate though and it fits in with that function well, to me this is going to be taking too much space with extra label next to the download button especially on mobile

**Comment by spacebares** [comment]
maybe put as an option in the download button's dropdown ?

**Comment by towerhand** [comment]
Is there any chance for this PR to get done?

**Comment by PovilasID** [comment]
@towerhand No not for this PR. Maintainers decided not to use it. However, it does not mean they will not implement same feature in some other way.

**Pull request closed without merging**
