### PR TITLE
Search functionality and UI tweaks

### PR DESCRIPTION
**Pull request by hawkeye217**
- Add ability to use time range for Chroma based searches
- Add event_id back to Chroma metadata for filtering
- Portal tooltips on search pages
- Remove object lifecycle from search details for non-object events
- Small tweaks for spacing consistency on mobile
- Bump `chromadb` to 0.5.7

Users on the dev builds running semantic search will need to reindex their embeddings (`reindex: True`) in order to use filters for thumbnail/description searches. A text query search with no filters will work without issue. Additionally, users may want to vaccum their Chroma database as a one-time optimization due to the upgrade from 0.5.0 to 0.5.7 by logging into the container and running `/usr/local/chroma utils vacuum --path /config/chroma`

### CODE REVIEW

**Review by NickM-27 — APPROVED** [review]

**Comment by DrSpaldo** [comment]
@hawkeye217 the time picker within iOS is not working when you export. Ie. You press the time, change it, press it, but it never updates on the export box in the custom area. Would this relate?

**Comment by hawkeye217** [comment]
No, this PR has nothing to do with exporting.

**Comment by DrSpaldo** [comment]
> No, this PR has nothing to do with exporting.

I see, do you think I should create a new issue/bug then?

**Comment by hawkeye217** [comment]
No, I'll fix it in a different PR. 

https://github.com/blakeblackshear/frigate/pull/14010

**Comment by DrSpaldo** [comment]
> No, I'll fix it in a different PR.
> 
> #14010

Great

**Pull request merged**
