### PR TITLE
Run python unit tests in a github actions

### PR DESCRIPTION
**Pull request by yury-sannikov**
hi @blakeblackshear 

This is an alternative way of running Python unit tests with Pytest, keeping the old way of doing unit testing. It helps to run tests outside of the dev container.

This PR does:
- add the `tox` support
- add `pytest` runner and mock `tflite` and file system access
- add github action to run python unit tests along with the UI tests on pull request
- fix unit tests failures

The last point deserves your detailed review. The issue is how the `create_ffmpeg_cmds()` being called. I moved it under `runtime_config` property code, though I'm not sure what was your original intent.

### CODE REVIEW

**Comment by blakeblackshear** [comment]
My preference would be to build the container in the github workflow and run tests from there. I'm not it's really a valid "test" if the pip dependencies could be entirely different versions. It's probably fine for the existing unit tests around parsing the config, but I wouldn't trust it otherwise. I do want to eventually build and publish the containers from github actions, so it would be a step in that direction.

**Comment by yury-sannikov** [comment]
Agree, building a docker image and running tests there would represent it better. What do you think would be the path forward for this PR?

**Comment by yury-sannikov** [comment]
What do you think about this?
image
https://github.com/yury-sannikov/frigate/pull/3/files#diff-a0fe23534b616d51ce686d2a1bcd1a78bc75074aef1a2f6ee96c9469991e1a4cR67

**Comment by yury-sannikov** [comment]
@blakeblackshear as a bare minimum I would like to get your review on unit test fixes if possible. I'm blocked in my other PR by that since I'm touching the same code base and want to make sure I'm not breaking anything.

**Comment by blakeblackshear** [comment]
I would build the container and then execute the tests inside it rather than adding the tests to the dockerbuild. I haven't had a chance to look at this in detail yet.

**Comment by yury-sannikov** [comment]
Hi @blakeblackshear, I made a Makefile command to run the docker build, which executes the unit test at the end. If tests fail, the build will also fail. I managed to reuse the same Dockerfile for each platform by sed-ing them in place.

this PR still contains the tox part to run tests on the local machine for folks like me. Do you think it makes sense to keep it or remove it?

**Comment by blakeblackshear** [comment]
I don't plan to maintain it, so I worry it will get out of date. Are you not using vscode with remote containers for development?

**Comment by yury-sannikov** [comment]
I'm not using remote containers. I'm developing my Jetson Nano using VS Code Remote SSH. It seems it's not possible to use dev containers and remote SSH at the same time.
I think you're right, my use case is not pretty common. I removed tox & pytest setup from this PR.

**Comment by yury-sannikov** [comment]
hi @blakeblackshear, do you have any plans of using `pytest` together with the unittest library? Parametrized tests with the unittest make test code pretty ugly.

**Comment by blakeblackshear** [comment]
I'm open to anything. Feel free to make a suggestion. I haven't invested heavily in writing tests as you can tell.

**Pull request merged**
