### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by madsciencetist**
Continuation of #7296

### CODE REVIEW

**Comment by madsciencetist** [comment]
Sample run: https://github.com/madsciencetist/frigate/actions/runs/5682623740

The amd64 and standard-arm64 builds cache well and are instant. The tensorrt and rpi builds do not seem to be caching, but take less than 10 minutes.

The jetpack4 build caches all but the last step, taking 5 minutes total.

The jetpack5 build is not caching well, taking 2.5 hours. I don't know why there is any difference between the jetpack4 and jetpack5 builds.

**Comment by NickM-27** [comment]
That is odd, I think this looks good generally though

**Review by NickM-27 — APPROVED** [review]

**Comment by madsciencetist** [comment]
Ugh, the jetpack images don't even work. I get `failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header` trying to pull them. All the other images pull fine.

**Comment by NickM-27** [comment]
Did the j4 image work with the original PR merging?

**Comment by madsciencetist** [comment]
No, I'm unable to pull the image from my CI run either. It might be the zstd compression

**Comment by NickM-27** [comment]
Sorry that was not clear, I mean was the image pullable with the original jetson PR?

**Comment by madsciencetist** [comment]
Yes, I can pull `ghcr.io/blakeblackshear/frigate:dev-761daf4-tensorrt-jp4` (but `jp5` timed out before ever building) but not `ghcr.io/blakeblackshear/frigate:dev--tensorrt-jp4` (supposed to be a96602f) or `ghcr.io/blakeblackshear/frigate:dev-f0dda49-tensorrt-jp4`, so it's definitely something from #7296

**Comment by madsciencetist** [comment]
Upgrading docker fixes it - the Jetson host OS is an Ubuntu whose apt docker version is 20.10, before zstd support was added. Still verifying the fix though.

**Comment by madsciencetist** [comment]
Confirmed & verified, fixed in #7308

**Pull request merged**
