### PR TITLE
[Rework RelativeModal] calculate available window height

### LINKED ISSUE #5997: [Support]:  Web Event Camera Selection
### Describe the problem you are having

Ever since 12 beta-8 or 9, the new fancy camera drop down selection under events does not work if frigate has more than 16 cameras for the instance.  16 and below and it works. I tried various combinations and redid my config serveral times so I do not believe it is my config as everything else still works correctly. The only thing I could think to grab was inspect/debug menu from chrome.  There are 3 messages presented:

[172.16.1.45-1681218152992.log](https://github.com/blakeblackshear/frigate/files/11200664/172.16.1.45-1681218152992.log)
[172.16.1.45-1681218193431.log](https://github.com/blakeblackshear/frigate/files/11200665/172.16.1.45-1681218193431.log)
[172.16.1.45-1681218116824.log](https://github.com/blakeblackshear/frigate/files/11200666/172.16.1.45-1681218116824.log)

it may be easier to just quickly add 17 cameras and try it out.  and just a picture so its clear what I am talking about:

frig

Let me know if there is anything else I need to procure.  

### Version

0.12.0-da3e197

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

Other

### Network connection

Wired

### Camera make and model

spiffy one

### Any other information that may be helpful

_No response_

### PR DESCRIPTION
**Pull request by sinamics**
I was able to re-produce the issue reported in #5997
The main issue is calculation of available window space for the dropdown menu that is calculated in the RelativeModal.jsx.

Changes: 
- Added a condition check to determine if there's enough space to position the menu above the clicked icon, and if not, position it below the icon.
- Modified the calculation of maxHeight by using the top value in the condition check for available window height, ensuring the dropdown menu fits within the remaining space.

Tested with 200 camera items on various diffrent window zoom size. 

**Important:** I dont have any events currently so im not able to test if the download menu on the last event appears correctly above the icon as this was an issue earlier. I will be able to check this tomorrow if nobody else has validated it by then.

@kdill00 are you able to test this pr and report back the results?

image
image
image

### CODE REVIEW

**Review by kdill00 — COMMENTED** [review]
Seems to work well now.  I dont know much about how commits are handled but this works.

**Review by kdill00 — DISMISSED** [review]
I tested with my 30 camera site on several devices and this works and looks good.

**Comment by NickM-27** [comment]
Yes that was the goal, so makes sense. Glad you tested all those scenarios.

**Comment by sinamics** [comment]
While testing the modals, I also updated the overflow-scroll to overflow-auto for the system page modals, which effectively hides the scrollbar when it's not necessary, providing a cleaner appearance.

**Comment by blakeblackshear** [comment]
I think we should consider rebasing these changes on master instead of dev so they can be included in 0.12.1.

**Comment by blakeblackshear** [comment]
Yes, but you will need to make sure you only carry over your commits when rebasing.

**Comment by sinamics** [comment]
ok, so i think i got it right..  
created a temp_branch based on master and cherry picked my commits and force-pushed to this branch.  😅

**Review by NickM-27 — APPROVED** [review]

**Comment by ccutrer** [comment]
Is there any documentation on Frigate's branching strategy? From what I can gather, `master` is the "stable" branch, and `dev` was merged into `master` when 0.12.0 was released, with new major features merged into the `dev` branch first. And this PR was merged into `master` so that it will be a part of 0.12.1. But I just started using an image from the `dev` branch to try out the new improved debug metadata and Frigate+ integrations, and noticed this commit is _not_ in that branch. So is it expected that bug fixes go to `master`, and new features go to `dev`, and there may not be a cohesive integrated branch until the next major release? Or can we get bug fixes that went directly to `master` cherry-picked on to the `dev` branch?

**Comment by NickM-27** [comment]
@ccutrer master is for docs updates and any changes for a fast follow like 0.12.1

dev is for new features coming in the next major release. 

Dev will be synced with master at some point, definitely no later than whenever 0.12.1 would go out. There's no specific defined strategy for that.

**Pull request merged**
