### PR TITLE
UI Feature: stop event button on Events page

### PR DESCRIPTION
**Pull request by skrashevich**
Depends on #6997.
Do not merge before it!

### CODE REVIEW

**Comment by NickM-27** [comment]
I think we are only going to want this for custom events, stopping a standard object event would cause issues with the internal object logic

**Comment by skrashevich** [comment]
> stopping a standard object event would cause issues with the internal object logic

Can you describe what kind of problems?

**Comment by NickM-27** [comment]
Frigate is still tracking the object, so snapshots are still potentially being updated and internally the event is still treated as in progress. There are many opportunities for assumptions that wouldn't be true and could cause exceptions. 

Also, the standard object events are not designed to be interacted with by the user directly and it will lead to a confusing experience because ending the event actually does nothing because it will still attempt to be updated by frigate which at best would just end it like it would have ended anyway without the stop button and at worst will cause an exception.

**Comment by NickM-27** [comment]
also to be clear, even if there was no risk of exception and the events ended correctly, I still don't think ending standard object events via user interaction is a good approach.

**Comment by skrashevich** [comment]
> I think we are only going to want this for custom events

any ideas how to differ custom event from internal?

**Comment by NickM-27** [comment]
I think the easiest way would be to set a field like `type: custom` in the `data` field of the event model when saving the manual events.  

Then in the UI just check that field

**Comment by skrashevich** [comment]
> I think the easiest way would be to set a field like `type: custom` in the `data` field of the event model when saving the manual events.

Manual events subsystem developed by you. Can you make the PR for add "type" field in the event model? After it, i will change this PR

**Pull request closed without merging**
