### PR TITLE
Logs in UI

### PR DESCRIPTION
**Pull request by NickM-27**
Here is a demo of the new logs page

https://user-images.githubusercontent.com/14866235/205716477-f905e4e5-de7e-4406-9008-cf0fab6c8be4.mov

### CODE REVIEW

**Comment by NickM-27** [comment]
@felipecrs I saw you commenting on https://github.com/just-containers/s6-overlay/issues/252 and it seems you'll likely have a better understanding of this than I do. We need to log python, go2rtc, and nginx (and future services) to a file in memory (want to avoid writing logs to disk). It seems s6 is the best way to do this.

This log file in memory can then be read to show the logs in the UI, if you have any ideas I'd be happy to hear them

**Comment by felipecrs** [comment]
I have to tinker with it a bit. I'll be back in a few hours with some snippets for you. :)

**Comment by NickM-27** [comment]
> I have to tinker with it a bit. I'll be back in a few hours with some snippets for you. :)

I appreciate it

**Comment by felipecrs** [comment]
I think it's finally time to upgrade to s6 v3... Logging is simpler with it. I'll push a PR.

**Comment by NickM-27** [comment]
Will be rebased on dev once #4587 is merged

**Comment by felipecrs** [comment]
I wonder if we should omit nginx and go2rtc logs from the container stdout now that we have this feature. I believe it may turn the add-on logs page very confusing with everything combined.

I also thought about prefixing the logs on stdout with the service name, but I'm not sure how exactly we can do that (https://github.com/just-containers/s6-overlay/issues/447#issuecomment-1341067116).

**Comment by NickM-27** [comment]
> I wonder if we should omit nginx and go2rtc logs from the container stdout now that we have this feature. I believe it may turn the add-on logs page very confusing with everything combined.
> 
> I also thought about prefixing the logs on stdout with the service name, but I'm not sure how exactly we can do that ([just-containers/s6-overlay#447 (comment)](https://github.com/just-containers/s6-overlay/issues/447#issuecomment-1341067116)).

That's a question for @blakeblackshear I don't really have an opinion one way or the other.

**Comment by felipecrs** [comment]
Well, actually it doesn't matter much. With the new UI users won't have to look at the container logs. Only if they want.

**Comment by NickM-27** [comment]
> Well, actually it doesn't matter much. With the new UI users won't have to look at the container logs. Only if they want.

right, I think that's the goal. Just need to make sure there are no downsides to the UI logs

**Comment by felipecrs** [comment]
One future improvement I can think about is colorizing. :)

**Comment by NickM-27** [comment]
I'm seeing the color characters for go2rtc just haven't had time to look into how html can be set to change them to colors. If you know the answer I'm all ears

**Comment by felipecrs** [comment]
On a quick search I found this: https://www.npmjs.com/package/ansi-to-html

**Comment by NickM-27** [comment]
That's not quite true, the shm size can be increased for HA addons it just has to be set as one value for all addons. 

And yes, we have the camera frames for detect stored in /dev/shm so that may be a concern for addon users.

**Comment by blakeblackshear** [comment]
I don't think we need to keep log archives beyond 10MB. Containers aren't really supposed to retain state like that, and we probably don't ever want to mess with trying to read those archives for the UI either. These files are essentially an in memory buffer for the UI to read logs. If users want a longer history of logs, they should do that by capturing the container logs and storing them on the host. Frigate also has fairly quiet logs normally. Even with 10MB, I suspect we will get support issues with "Bus error" crashes.

**Review by blakeblackshear — APPROVED** [review]

**Pull request merged**
