### PR TITLE
Docker revamp Nvidia decode support

### PR DESCRIPTION
**Pull request by blakeblackshear**

### CODE REVIEW

**Comment by NickM-27** [comment]
@blakeblackshear  When trying to build now I get:

```
 => ERROR [stage-2 11/13] COPY web/dist web/                                               0.0s
------
 > [stage-2 11/13] COPY web/dist web/:
------
failed to compute cache key: "/web/dist" not found: not found
make: *** [local] Error 1
```

and when running `make build_web` I get:

```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 501:20 "/.npm"

npm ERR! A complete log of this run can be found in:
make: *** [build_web] Error 243
```

**Comment by blakeblackshear** [comment]
You should just have to run `make build_web` first, but you may need to clean up existing build artifacts. Still trying to get the build process ironed out that works locally and in actions.

**Comment by NickM-27** [comment]
> You should just have to run `make build_web` first, but you may need to clean up existing build artifacts. Still trying to get the build process ironed out that works locally and in actions.

Okay I see. To confirm, `npm run build` inside web/ works and allows building frigate. 

Running `make build_web` on a fresh clone + no cached assets shows:

```
Status: Downloaded newer image for node:16
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 501:20 "/.npm"

npm ERR! A complete log of this run can be found in:
make: *** [build_web] Error 243
```

**Comment by blakeblackshear** [comment]
That works too. I don't have node or npm installed on my host.

**Comment by NickM-27** [comment]
> That works too. I don't have node or npm installed on my host.

Okay cool. One other thing I noticed after getting things running, I am seeing some issues that seem to be related to the new ffmpeg build

```
frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
[2022-04-25 18:36:21] frigate.record                 ERROR   : [Errno 2] No such file or directory: 'ffprobe'
```

also the detect stream works and I get events with the snapshots (naturally no recordings due to above), but when viewing I don't see bounding boxes, zones, masks, etc. in the live view. 

I hope this is helpful, my apologies if you are already aware and working on it, but figured I'd let you know and also I am happy to look it if you aren't experiencing these things on your side.

**Comment by blakeblackshear** [comment]
I haven't run into those things yet, but I haven't done much testing at all after those changes.

**Pull request merged**
