### PR TITLE
Update go2rtc to 1.5.0

### LINKED ISSUE #6546: Add FLAC(PCMA/PCMU/PCM) support for MSE live view
**Describe what you are trying to accomplish and why in non technical terms**
Currently frigate's MSE live view only support AAC audio, but many cameras give PCMA and lack AAC support. According to [go2rtc's docs](https://github.com/AlexxIT/go2rtc#built-in-transcoding),

Go2rtc support automatic repack PCMA/PCMU/PCM codecs to FLAC for MSE/MP4/HLS so they will work almost anywhere.
Go2rtc can pack PCMA, PCMU and PCM codecs into an MP4 container so that they work in all browsers and all built-in players on modern devices. Including Apple QuickTime:
```
PCMA/PCMU => PCM => FLAC => MSE/MP4/HLS
```
So it's possible to add FLAC(PCMA/PCMU/PCM) support for MSE live view.

**Describe the solution you'd like**
Currently frigate just send `{type: "mse"}`, [frigate](https://github.com/blakeblackshear/frigate/blob/dev/web/src/components/MsePlayer.jsx#L24)
Use `MediaSource.isTypeSupported` to test codecs support then send `{type: "mse", value: "<supported codecs>"}` like [go2rtc](https://github.com/AlexxIT/go2rtc/blob/master/www/video-rtc.js#L175) do.

### PR DESCRIPTION
**Pull request by NickM-27**
To-Do:

- [x] Update webrtc code to better handle async communication
- [x] rewrite mse player to use standard VideoRTC so it can receive future improvements
- [x] Update docs to point to new go2rtc docs 1.5.0

### CODE REVIEW

**Comment by felipecrs** [comment]
> - Update webrtc code to better handle async communication

Is this mandatory or just nice to have? I'm asking because, otherwise, it may be worth re-considering adding this to 0.12, since 1.3.1 has some fixes around reconnections.

**Comment by NickM-27** [comment]
> > - Update webrtc code to better handle async communication
> 
> 
> 
> Is this mandatory or just nice to have? I'm asking because, otherwise, it may be worth re-considering adding this to 0.12, since 1.3.1 has some fixes around reconnections.

In my testing WebRTC works in the frigate webUI but not well and this change will be necessary. In any case, I don't think the dependency being pinned at 1.2.1 will be reconsidered unless some large issue is discovered in 1.2.1. Any user who wants to be on the bleeding edge of go2rtc in frigate can use a bind mount to override the internal go2rtc and run whichever version they want.

**Comment by NickM-27** [comment]
Going to put this back into draft as I test 1.5.0. It contains a number of fixes and optimizations so I think it would be a better base, but it still needs to be tested

**Review by blakeblackshear — APPROVED** [review]

**Comment by blakeblackshear** [comment]
Rebasing this should fix the build errors.

**Pull request merged**
