### PR TITLE
Upgrade go2rtc from v1.0.1 to v1.1.0

### PR DESCRIPTION
**Pull request by felipecrs**
Refs https://github.com/AlexxIT/go2rtc/releases/tag/v1.1.0
Refs https://github.com/AlexxIT/go2rtc#module-rtsp

Closes https://github.com/blakeblackshear/frigate-hass-integration/issues/418

### CODE REVIEW

**Comment by NickM-27** [comment]
We can probably also update the restream docs to remove the `video&audio` query args

**Comment by NickM-27** [comment]
The other side of this is it may cause confusion for users if they don't setup go2rtc correctly and it doesn't have an aac track (referring to frigate recordings)

**Comment by felipecrs** [comment]
> The other side of this is it may cause confusion for users if they don't setup go2rtc correctly and it doesn't have an aac track (referring to frigate recordings)

If it does not have aac track, I think it will not fail. Then audio will not work in HA HLS player.

**Comment by NickM-27** [comment]
> > The other side of this is it may cause confusion for users if they don't setup go2rtc correctly and it doesn't have an aac track (referring to frigate recordings)
> 
> If it does not have aac track, I think it will not fail. Then audio will not work in HA HLS player, just as before. So, I think there is no downside.
> 
> We just need to test it again to ensure it won't fail if aac track isn't there.

I'm not suggesting it will fail, it won't, but it will provide a track with no audio. Basically if we are defaulting to request aac audio, if a user only has pcmu audio and was using `preset-record-generic-audio-aac` it will still be blank unless the user specifically adds `?video&audio` to the url in frigate.

I don't think it will be a big issue (probably reduces the number of issues) we just need to be aware of that

**Comment by NickM-27** [comment]
I think the new guide is pretty clear about needing to enable AAC so it should work as expected for most users, if it becomes a problem can add more docs around it

**Comment by felipecrs** [comment]
Hm... but I was expecting that go2rtc would supply the pcmu audio if there isn't aac audio, instead of providing no audio (this is what happened when I tested the PR at the integration).

**Comment by NickM-27** [comment]
> Hm... but I was expecting that go2rtc would supply the pcmu audio if there isn't aac audio, instead of providing no audio (this is what happened when I tested the PR at the integration).

no, I do not believe that to be the case. If I request aac audio when it has none it returns an empty AAC audio track with 0 data

**Comment by felipecrs** [comment]
Ok, I'll have to test it again.

**Comment by NickM-27** [comment]
For example I just pulled in this change and this is what I get

```
{
      "type": "RTSP client",
      "url": "rtsp://127.0.0.1:8554/front_doorbell_cam",
      "remote_addr": "127.0.0.1:50526",
      "user_agent": "FFmpeg Frigate/0.12.0-5834233",
      "medias": [
        "video, recvonly, 96 H264/90000",
        "audio, recvonly, 97 MPEG4-GENERIC/16000/1"
      ],
      "tracks": [
        "96 H264/90000, sinks=2",
        "97 MPEG4-GENERIC/16000/1, sinks=1"
      ],
      "send": 52406728
    }
```

however when I do the same for the camera when it doesn't have AAC audio I get:

```
    {
      "type": "RTSP client",
      "url": "rtsp://192.168.50.106:8554/front_doorbell_cam",
      "remote_addr": "192.168.50.16:62040",
      "user_agent": "Lavf59.27.100",
      "medias": [
        "video, recvonly, 96 H264/90000",
        "audio, recvonly, 0 MPEG4-GENERIC/0"
      ],
      "tracks": [
        "96 H264/90000, sinks=3"
      ],
      "send": 3144994
    }
```

**Comment by felipecrs** [comment]
Hm... so, this is not great. I think go2rtc should not send any track in this case. For example, I have some cameras that does not have microphone. I'll also do some more tests on my side.

**Comment by NickM-27** [comment]
@felipecrs we may want to reduce this PR to just updating go2rtc to 1.1.0 and handle these additional optimizations in another PR. https://github.com/AlexxIT/go2rtc/issues/227 is something else to consider as well

**Comment by felipecrs** [comment]
@NickM-27 good idea. Done.

**Review by NickM-27 — APPROVED** [review]

**Pull request merged**
