### PR TITLE
FEAT: Ability to retain specific clips / events indefinitely

### PR DESCRIPTION
**Pull request by NickM-27**
This is a WIP PR and I am an Android / Mobile dev by profession so if my code can be improved please feel free to make commits / suggest changes! Fix for #1787 

- [x] Update events object
- [x] Update deletion logic
- [x] Update sqlite version / migration
- [x] Add UI button to edit retain status (not sure best way to do this, potentially a button next to the "delete" button?
- [x] Add POST to HTTP API to allow setting retain
- [x] Set UI button state based on each event
- [x] Edit Events objects when UI button is used
- [x] UI button update state after successful call
- [x] Update HTTP API docs
- [x] Fix un-retain disappearing bug

### CODE REVIEW

**Comment by NickM-27** [comment]
Okay, I reset the `web/` and left everything else and it started working as expected, so it must be some error with the web changes I made

**Comment by NickM-27** [comment]
It seems none of my changes are taking place. I made sure to hard refresh the browser and shut down the container and re `make` but it doesn't seem to change anything. Also trying to access the http API with `http://127.0.0.1:5002/api/stats` and it is giving me an error.

**Comment by mr6880** [comment]
Very interesting pull request NickM. What are your thoughts about the ability to retain custom length clips from recordings, so create an event between two times and retain that footage?

**Comment by NickM-27** [comment]
> Very interesting pull request NickM. What are your thoughts about the ability to retain custom length clips from recordings, so create an event between two times and retain that footage?

Thanks! I think that would be a cool feature, but it is outside the scope of this PR / issue I referenced initially. If there isn't already an issue created for that concept then definitely go and create it 👍

**Comment by NickM-27** [comment]
@blakeblackshear @yury-sannikov This is about ready for review. Hopefully I am not bothering y'all, but if y'all have a minute I could use some help. 

Everything seems to be working except when the button is pressed the buttons state doesn't udpated. And if the button is in the `press to un-retain` state the row will disappear (but reappear on refresh). I have spent a handful of hours on it and I think I may just need another set of eyes. The other thing is I haven't tested to make sure the clip is actually retained since the lowest retention time is 1 day. But based on the logic I believe that part should work just fine. Thank you! 👍

**Comment by NickM-27** [comment]
Okay I fixed the bug where the states weren't updating. Somehow, it still has the issue where pressing the button when it is in the un-retain state causes the event to disappear.

**Comment by NickM-27** [comment]
@blakeblackshear Okay awesome, sounds like a plan. I should have the lint errors taken care of 👍 . Just curious, with no new features coming is 0.10.0 going to become stable soon? I'm looking forward to getting this feature out and also in general would be interested in knowing what the timeline looks like? In any case, thanks for looking over my PR! Glad I was able to contribute something to this awesome project.

**Comment by yury-sannikov** [comment]
I think this is a great feature as-is. I could also see some potential evolvement of it. For instance, a camera zone configuration may have a list of classes to automatically enable `retain_indefinitely` on an event if an object of a specified class has been detected.

**Comment by NickM-27** [comment]
> I think this is a great feature as-is. I could also see some potential evolvement of it. For instance, a camera zone configuration may have a list of classes to automatically enable `retain_indefinitely` on an event if an object of a specified class has been detected.

Thank you! And yeah, that would be a cool evolvement to have it done automatically for config specified types, I don't think that would be too complicated to add in the future.

**Comment by mr6880** [comment]
This is definitely a much appreciated addition! It was also shocking to see the speed that this PR came together.

What are your thoughts about the storage space used by indefinite retention? I've been dwelling on it and feel it could lean on or clash with a future/suggested "Retention by available disk space" option for the regular events/recordings.

**Comment by NickM-27** [comment]
@mr6880 Thank you! 

I have thought about it too and I think it is a non issue. The retention (even the expansion yury suggested) isn't something that is forced or automatic. The same with the "retention by available disk space" idea. So the user, when configuring / using these features, would make a conscious choice if they are more worried about disk space and be specific with which clips to retain or if they have a large drive and want to focus on retaining more clips. 

Also it's only retaining clips, not retaining full hour recording segments so any user ought to be aware their storage is getting more full in the time it would take to retain enough clips to get almost full.

**Comment by NickM-27** [comment]
@mr6880 Also just wanted to clarify as perhaps it wasn't fully specific in the title, this PR adds the ability to retain on a clip by clip basis in the UI, not a generic retain all clips forever

**Comment by mr6880** [comment]
@NickM-27 Thank you for the clarification!

**Comment by blakeblackshear** [comment]
> Just curious, with no new features coming is 0.10.0 going to become stable soon?

I need to make some improvements to the way stationary objects are determined. I am hoping to get an RC as soon as I address those issues and move on to 0.11.0.

**Comment by NickM-27** [comment]
Fixes #615

**Comment by NickM-27** [comment]
@blakeblackshear I have been doing some more testing on this and it seems like it actually is still having the events deleted, so is there any way to potentially create a lower retention than 1 day for testing purposes, or manually trigger a scheduled cleanup to see if things work correctly?

**Comment by NickM-27** [comment]
I only did `retain_indefinitely is False` in the Events.py part, I notice there are other update calls in that file, should I add that parameter to those calls as well? 

Also, is keeping the event from being deleted all it takes to ensure everything stays?

**Comment by NickM-27** [comment]
Ahhh nevermind, looks like the recordings were being deleted still and that was causing the event to be deleted. Need to add a check to the recordings logic as well.

**Comment by blakeblackshear** [comment]
You can adjust the counters in the thread loops for testing: https://github.com/blakeblackshear/frigate/blob/release-0.10.0/frigate/record.py#L551

There should be something similar in events.py

**Comment by NickM-27** [comment]
Okay I figured it out, I didn't have the `retain_indefinitely` check on the `update_config` logic so it was still setting `has_snapshot` and `has_clip` to False despite it not being deleted.

**Pull request closed without merging**
