### PR TITLE
Update TRT

### PR DESCRIPTION
**Pull request by NickM-27**
## Proposed change

Updates the included nvidia libraries to the latest 8.X version

## Type of change

- [x] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code
- [ ] Documentation Update

### CODE REVIEW

**Review by hawkeye217 — APPROVED** [review]

**Comment by kirsch33** [comment]
Just following up to #16332 discussion. I think this PR is where my problem is but it's on my end. Container image 23-02 requires driver version 530 or newer which is what Debian Bookworm is tied to. 

Image 23-12 requires driver version 545 or later. To get this version you have to install the driver from the nvidia repo direct instead of thru apt. 

I'll try this today and follow up.

**Comment by NickM-27** [comment]
Ah good to know

**Comment by kirsch33** [comment]
Had to uninstall all nvidia drivers on the host and reinstall with official nvidia repo, so now running driver version 570.86.15 and can confirm this is all fixed. If this should be in the docs somewhere I can take a stab at adding it.

**Comment by NickM-27** [comment]
There are already docs in the object detection section that define the minimum driver so that would be the best place to update.

**Pull request merged**
