### PR TITLE
Add basic PTZ support

### PR DESCRIPTION
**Pull request by SheaSmith**
This is a reasonably simple PR that adds PTZ support to the API.

There are now five new APIs, `/api/{camera}/ptz/move` which accepts a `direction` parameter (this can be on of `up`, `down`, `left` or `right`), `/api/{camera}/ptz/zoom` which has a `zoomIn` parameter, which can be either 0 or 1, `/api/{camera}/ptz/stop`, which stops all movement, `/api/{camera}/ptz/sethome` which sets the 'home' location to the current location and `/api/{camera}/ptz/gotohome`, which moves the camera to the home location that has been set.

Additionally, two new configuration sections have been added. One section is for the basic ONVIF information (`host`, `port`, `username` and `password`) and the other is for a few specific PTZ settings (`turn_speed`, which specifies how fast the camera should turn and `invert_y_axis` which switches the direction of the y-axis, which is helpful for cameras that are mounted upside-down). I've documented these in the `index.md` file, however it might be helpful to have a dedicated section in the docs perhaps.

I've tested it across two PTZ cameras (and one non-PTZ camera to make sure it doesn't break anything) and it seems to work reasonably well. Basically just relies on the continuous move ONVIF function to operate, and it is intended to work with a frontend implementation where you hold down the appropriate button to move the camera (vs something like Shinobi which you just press to move a set amount each time). It also includes a rundementary home function, where a default home location can be set and activated using the presets ONVIF API.

There's also scope for a frontend in Frigate itself, which I'd be happy to have a look at, although I thought it would be best to have a discussion first about how such a UI would look. I also plan to work on adding support to the HA integrations, but that's a PR for another day.

Also happy to hear any improvements that need to be made to the code, as Python is certainly not my forte, so I expect there's a bit of scope for improvement there.

### CODE REVIEW

**Comment by blakeblackshear** [comment]
Is there a way to query the current position of the camera via onvif?

**Comment by SheaSmith** [comment]
There is, using the [GetStatus](https://www.onvif.org/specs/srv/ptz/ONVIF-PTZ-Service-Spec-v1612.pdf) command, which returns the absolute position of the camera, but both of my cameras don't seem to support it (or absolute movement in general for that matter).

**Comment by maxi1134** [comment]
To add to this: 

Some cameras can be controlled using POST rest command, if there was a way to send those post commands using buttons in the interface, that would be great!

I currently use something like this with the HASS frigate-card in the lower-right corner.: 
image


Those are pre-determined points for the camera using this kind of Hass rest command

```
ptz_reolink:
    url: http://192.168.0.**/cgi-bin/api.cgi?cmd=PtzCtrl&token={{token}}
    method: POST       
    payload: '[{"cmd":"PtzCtrl","action":0,"param":{"channel":0,"op":"ToPos","speed":32,"id":{{ptz_id}}}}]'
    ```

**Comment by Sider92** [comment]
@blakeblackshear is this something you may be implementing in to frigate?

**Comment by blakeblackshear** [comment]
In a later release, yes.

**Comment by nelsongraca** [comment]
Can we have this on 0.11.0?

**Comment by NickM-27** [comment]
@nelsongraca This PR is quite outdated and has lots of conflicts, it won't be making it to 0.11

**Comment by SheaSmith** [comment]
Yes, I don't intend to update this PR. I've moved to using the Home Assistant WebRTC plugin controls for PTZ. It'd still be nice to have motion tracking with PTZ, but I don't have the time (or really the know-how) to implement such a feature.

**Comment by nelsongraca** [comment]
@SheaSmith can you elaborate? I don't see any reference to PTZ on the WebRTC plugin

**Comment by SheaSmith** [comment]
I use the AlexxIT WebRTC addon, which has a guide for adding the WebRTC controls to your configuration at https://github.com/AlexxIT/WebRTC/wiki/PTZ-Config-Examples. Happy to paste my full YAML config for integrating this into the Frigate card if that's helpful.

**Comment by dermotduffy** [comment]
Related: The Frigate Lovelace card (v4+) has PTZ controls built in, as long as the actual camera is moveable via HA service calls (which many are).

Screenshot: https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0#ptz-control

**Pull request closed without merging**
