### PR TITLE
Fix/Feature: Nginx respect logger configuration (sometimes)

### LINKED ISSUE #6828: Make nginx respect logger: default settings
**Describe what you are trying to accomplish and why in non technical terms**
Running 0.12.1-367d724, and I have configured logging as:
```
logger:
  default: warning
  logs:
    frigate.mqtt: warning
```
But the nginx is still continuously logging with:
```
2023-06-17 09:20:04.173117802  1.2.3.4 - - [17/Jun/2023:09:20:04 +0200] "GET /api/stats HTTP/1.1" 200 3594 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
```
**Describe the solution you'd like**
To be able to set NGINX logs to warning, to reduce log output. 

**Describe alternatives you've considered**
Tried adding `frigate.nginx: warning`, but it seems to be ignored.

**Additional context**

### PR DESCRIPTION
**Pull request by skrashevich**
resolve #6828

### CODE REVIEW

**Review by NickM-27 — CHANGES_REQUESTED** [review]
This is not going to work, it will fragment the error log and access log meaning a user can only have one or the other but not both enabled at the same time.

Also, the S6 logger is still enabled which would likely cause conflicts

**Comment by skrashevich** [comment]
> This is not going to work, it will fragment the error log and access log meaning a user can only have one or the other but not both enabled at the same time.

I quickly understood it and rolled out the fix)

> Also, the S6 logger is still enabled which would likely cause conflicts

S6 logger watch  to stdout/stderr. When there's nothing in them, it doesn't write anything

**Comment by skrashevich** [comment]
NB: Nginx, when it receives an HUP signal, not only reload its configs, but also re-opens file descriptors, including logs

**Comment by NickM-27** [comment]
> > I think it would be preferable to have this logic before NGINX starts in the S6 script.
> 
> Because of this: https://github.com/blakeblackshear/frigate/blob/dev/docker/rootfs/etc/s6-overlay/s6-rc.d/nginx/dependencies.d/frigate
> 
> nginx only starts after frigate is up I think.

that's fine, I still think it should be done in the nginx s6 script and not in the frigate code. Same as how go2rtc reads from the frigate config and defines its own config to use

**Comment by trunet** [comment]
Can a new config be added like `nginx_access_log: false` (default being true) under logger? if yes, a simple grep and sed on the supervisor run script would do the trick.

**Comment by NickM-27** [comment]
I don't think python should be used for that, there is already a good example in frigate itself

https://github.com/blakeblackshear/frigate/blob/9e531b0b5bf34634dc6c44e7eca7e5eaf5a52a25/docker/rootfs/etc/s6-overlay/s6-rc.d/frigate/run#L12-L43

**Comment by trunet** [comment]
> I don't think python should be used for that, there is already a good example in frigate itself

Nice to have `yq` available.

**Comment by skrashevich** [comment]
> that's fine, I still think it should be done in the nginx s6 script and not in the frigate code. Same as how go2rtc reads from the frigate config and defines its own config to use

There is a nuance here: the wrong configuration when starting nginx will not allow it to start, but if it is changed after launch, it simply will not be applied, but the services will continue to work

And I want to note that changing the configuration without restarting was one of the main features of nginx from the beginning of the nginx project

**Comment by NickM-27** [comment]
I still think this is a very simple change to the file which can be done before starting nginx as frigate process itself does not need to worry about managing the other processes (which is the job of S6).

In any case, the current implementation here still lacks the ability for the user to view a unified log of both access and error logs at the same time if it was enabled that way. 

I think a much simpler solution would be to leave both access_log and error_log printing to stdout and simply comment out the access log file in the case that access logs are disabled by the user

**Comment by skrashevich** [comment]
> I still think this is a very simple change to the file which can be done before starting nginx as frigate process itself does not need to worry about managing the other processes (which is the job of S6).

In this case, we need to decide who should be the general manager of all logs in the project. It's necessary to put the logs of all processes in one place, and take them from this place with corresponding filters/settings

**Comment by NickM-27** [comment]
> > I still think this is a very simple change to the file which can be done before starting nginx as frigate process itself does not need to worry about managing the other processes (which is the job of S6).
> 
> In this case, we need to decide who should be the general manager of all logs in the project. It's necessary to put the logs of all processes in one place, and take them from this place with corresponding filters/settings

If I understand you correctly then I disagree with that. Each service (nginx, go2rtc, frigate) has its own configurations for logs and controls the filtering / behavior of what logs are output on its own. Once these logs are output to stdout S6 manages the logs and keeps them in SHM. 

This doesn't need to be so complicated, S6 script that starts nginx can read the frigate config and adjust its own behavior accordingly just like scripts that start frigate and go2rtc do already. That way it fits in with the current architecture.

**Comment by vertex-github** [comment]
Did this get implemented?  Id also like to disable the access logs from my docker container if possible.

**Comment by NickM-27** [comment]
/stats and /version were removed from the access logs. There is no official way to disable all access logs

**Comment by AnderssonPeter** [comment]
> /stats and /version were removed from the access logs. There is no official way to disable all access logs

Is this still the case in 2025?
While it is nice that /version and /stats are gone, it would be nice to get rid of the http request unless they are a failure..

**Comment by NickM-27** [comment]
you can do that, just bind mount an adjusted nginx config with access logs disabled

**Comment by Pasukaru** [comment]
For those looking for how to do the proposed nginx changes, this is what I did:

* Copy existing nginx conf from inside frigate container to your docker host:
```docker cp frigate:/usr/local/nginx/conf/nginx.conf config/frigate/nginx.conf```
`frigate` is the container name. `config/frigate/nginx.conf` is the relative path where you want the file on the docker host

* Edit `config/frigate/nginx.conf` and comment out the access log (for me this was in line 22 with the current 0.15.1 image)
```access_log /dev/stdout main;``` => ```# access_log /dev/stdout main;```

* Mount the updated file in the docker container. In my case with docker compose this is how:
```
services:
  frigate:
    ...
    volumes:
      - ./config/frigate/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
```

* Restart it
```docker compose up -d frigate```

* Pray that the original nginx conf doesn't change in the future and if it does that you don't forget about it. You'll have to copy the original and adjust it again.

**Comment by definitio** [comment]
Just build a custom image:
```
FROM ghcr.io/blakeblackshear/frigate:stable
RUN sed -i "s/\ \ \ \ access_log\ \/dev\/stdout.*/\ \ \ \ access_log\ off;/g" /usr/local/nginx/conf/nginx.conf
```

**Comment by sndrsmnk** [comment]
[This comment](https://github.com/blakeblackshear/frigate/discussions/6871#discussioncomment-6626208) is a clean and working solution to disable access logs.

**Comment by rccoleman** [comment]
> For those looking for how to do the proposed nginx changes, this is what I did:
> ... 
> But all the other spam is gone.

This is super-easy and works great.  Thanks!

**Pull request closed without merging**
