### PR TITLE
Clarify mqtt env-var version requirements

### PR DESCRIPTION
**Pull request by kquinsland**
This addresses #5640

### CODE REVIEW

**Comment by NickM-27** [comment]
There's no need to have this. These docs are already specific to 0.12 beta. The stable docs do not show this is possible.

**Comment by kquinsland** [comment]
> 

Can you link me to the "stable" docs?

I just assumed that this page: https://docs.frigate.video/configuration/index/

was the stable docs as there is no branch/tag in the URL and that's the link you get when you google "frigate docs" or click the "docs" link from frigate.video page. 

I don't see a "select your version" function on that page which sorta reinforced the "the docs you see here are accurate to the stable release" notion.

**Comment by NickM-27** [comment]
> > There's no need to have this. These docs are already specific to 0.12 beta. The stable docs do not show this is possible, 
> 
> 
> 
> Can you link me to the "stable" docs?
> 
> 
> 
> I just assumed that this page: https://docs.frigate.video/configuration/index/
> 
> 
> 
> was the stable docs as there is no branch/tag in the URL and that's the link you get when you google "frigate docs" or click the "docs" link from frigate.video page. 

Those are the stable docs, and in them it only says MQTT password substitution is supported, not MQTT user. 

https://deploy-preview-4055--frigate-docs.netlify.app is the link to beta docs. 


> > there's no need for the docs to say which things are supported in which versions.
> 
> 
> 
> That's an unfortunate policy to have.

Why? If we have a long list of each feature and when it started being supported and different iterations of confirmations the docs would be a confusing mess and much longer. 

The stable docs are for the stable version and what should be referenced. 

Also, to be clear, that's my own opinion and I don't speak for the project in saying that (it's not a policy)

**Comment by kquinsland** [comment]
> Those are the stable docs, and in them it only says MQTT password substitution is supported, not MQTT user.

That env-vars only work for _some_ fields and not others wasn't super clear. I could have sworn that I saw **general** "env vars starting with `FRIGATE_` map back to some corresponding config value...." in a few places throughout docs/example configs.

Apparently i'm not the only one that assumed the somewhat common pattern applied to all configuration directives: https://github.com/blakeblackshear/frigate/issues/1976

> Why? If we have a long list of each feature and when it started being supported and different iterations of configurations the docs would be a confusing mess and much longer.

No need to over think this: a general `New since $versionHere` on each directive in the "full config" would get the point across.  A simpler approach is to just generate and serve them w/ a tag in the url.  E.G: `docs.frigate.video/latest` which is just an alias to `docs.frigate.video/0.11`. 

Something like this; 

docs-version-ex


You loose automated "new since" annotations, but it's still easy enough to visually compare a documentation page for two different versions.

/shrug.  Lesson learned - despite looking like a common "all config can be an env-var" pattern ... it is _not_ an "**all config** can be an env-var" pattern.

**Comment by NickM-27** [comment]
> > Those are the stable docs, and in them it only says MQTT password substitution is supported, not MQTT user.
> 
> 
> 
> That env-vars only work for _some_ fields and not others wasn't super clear. I could have sworn that I saw **general** "env vars starting with `FRIGATE_` map back to some corresponding config value...." in a few places throughout docs/example configs.
> 
> 
> 
> Apparently i'm not the only one that assumed the somewhat common pattern applied to all configuration directives: https://github.com/blakeblackshear/frigate/issues/1976
> 
> 
> 
> > Why? If we have a long list of each feature and when it started being supported and different iterations of configurations the docs would be a confusing mess and much longer.
> 
> 
> 
> No need to over think this: a general `New since $versionHere` on each directive in the "full config" would get the point across.  A simpler approach is to just generate and serve them w/ a tag in the url.  E.G: `docs.frigate.video/latest` which is just an alias to `docs.frigate.video/0.11`. 
> 
> 
> 
> Something like this; 
> 
> 
> 
> docs-version-ex
> 
> 
> 
> 
> 
> You loose automated "new since" annotations, but it's still easy enough to visually compare a documentation page for two different versions.

Would be easier to serve the beta docs that way, not sure the docs deploy supports anything like that.


> /shrug.  Lesson learned - despite looking like a common "all config can be an env-var" pattern ... it is _not_ an "**all config** can be an env-var" pattern.

I agree it is confusing in the stable docs but that's why the new docs were rewritten to reflect this and https://github.com/blakeblackshear/frigate/pull/4882/files will help further.

**Pull request closed without merging**
