### PR TITLE
Performance: multiprocessing improvement: step 2

### PR DESCRIPTION
**Pull request by skrashevich**
in continue to #6936
Feedback on performance improvements on different setups are welcome

### CODE REVIEW

**Comment by skrashevich** [comment]
On my system I see a performance increase of about 75% (relative to #6936, but together with #6917)

**Comment by NickM-27** [comment]
I'll try to pull it down in a bit and give it a go. If there is concern of race condition then it might make sense to use the mp.Queue for those limited queue cases until ff supports `maxsize`

**Comment by NickM-27** [comment]
Running now, seems good on startup but will see how things are after letting it run for a bit

**Comment by kdill00** [comment]
loaded it before one of my locations closed and seemed to run okay with 50 people or so in front of the 30 or so cameras at the high point in comparison to blakes previous motion commit which has been running great.  I will run it tomorrow when we open and theirs a couple hundred people around and let you know how it does.  I will try it on all different recording settings as I tend to see ranging effects with different retention settings due to the number of people in front of the cameras.  I do notice the recording managers are now using a lot more CPU.  But overall everything seems lower at the moment.

**Comment by kdill00** [comment]
I ran it all today and it looks like it’s running great. I’m having some issues with objects loosing tracking fast but I think it’s partially due to me needing to fine tune motion sensitivity as well I just saw that the interval command to scan stationary objects was changed from a default of 0 in previous versions so I probably need to play with that. It was a somewhat slow day but with 110 people being tracked on the cameras I was seeing about 15 percent cpu compared to a usual 30 percent on this server.  While my inference time is higher, it seems to be more effective in putting the frames in front of the gpu.  The really big win I see here and I don’t know if it’s the multiprocessing improvements, motion detection changes, or what but starting back in 10.0 when frigate moved to track forever concept, i seemed to run into a hard limit of around 10 to 14 objects tracked by a camera. I had one camera tracking 40 people today with better accuracy than I would have expected. Tomorrow should be a huge day as it’s the holiday. I am excited to see it pushed to the limit on this system and see what it does then.  It feels like now the limit is finally my resources instead of whatever mystery was limiting previous versions from exceeding these limits.  Tomorrow I expect a lot more foot traffic and will be watching closely to see how much better it does when the server is completely maxed out.  13.0 is shaping up to be the best release yet.

**Comment by NickM-27** [comment]
The new tracker has a different behavior than the previous one. The previous tracker would try to track an object for `max_disappeared` as soon as it was a true positive. The norfair tracker has a concept of "object inertia" so each hit on an object is a +1 and each miss (object isn't detected) is a -1 and it counts up to max_disappeared. This helps with false positives since a false positive will be lost sooner after it's found. 

This does also mean that an object that isn't detected for a few frames soon after being initially detected will be considered gone.

**Comment by kdill00** [comment]
That makes perfect sense.  Thanks for the explanation.  The tracking definitely handles setting with flashing bright lights and tons of movement from things it’s not suppose to track.  A massive improvement so far and my average ram usage has gone from 14gb + to a steady 11 to 12 with thirty 720p cameras.  I did see swap being used even though there was 250gb of ram available but changing the vm.swappiness setting in Debian got rid of that. It was not causing me issues and I know sometimes it can be beneficial to use swap even in cases where there is lots of free ram but going to try forcing it away first so we will see if that hurts me at all tomorrow.

**Review by blakeblackshear — APPROVED** [review]

**Pull request merged**
