### PR TITLE
Upgrade go2rtc from v0.1-rc.8 to v0.1-rc.9

### PR DESCRIPTION
**Pull request by felipecrs**
~Also refactors the configuration logic loading so that both the internal config and the user defined config are taken into account.~

~- Refs https://github.com/blakeblackshear/frigate/pull/5088#issuecomment-1382876276~

### CODE REVIEW

**Comment by felipecrs** [comment]
Actually I have to test this loading stuff.

**Comment by NickM-27** [comment]
@felipecrs we are reworking the config loading for go2rtc separately so this won't be needed here. Will put up PR in a bit.

**Comment by felipecrs** [comment]
Ok, cleaning it up then.

**Comment by felipecrs** [comment]
Done.

**Review by NickM-27 — APPROVED** [review]

**Pull request merged**
