### PR TITLE
Favorite events delete button warning

### PR DESCRIPTION
**Pull request by NickM-27**
As mentioned in https://github.com/blakeblackshear/frigate/discussions/3221#discussioncomment-2776261

Would be good to provide a deletion dialog for favorite / saved events in case of a misclick. This changes nothing for events that are not favorited.

Screenshot for reference when clicking delete on a favorited event:

Screen Shot 2022-05-18 at 9 05 43 AM

### CODE REVIEW

**Comment by ozett** [comment]
that feature should be linked to calculation/estimation of storage space left ...
(estimate how long recordingtime will remain, when blocking and delete-protect a clip of specific length)
see: FR https://github.com/blakeblackshear/frigate/issues/994#issuecomment-1132320239

**Comment by NickM-27** [comment]
> that feature should be linked to calculation/estimation of storage space (=recording-time) left ...
> 
> (estimate how long recordingtime will remain, when blocking and delete-protect a clip of specific length)
> 
> see: FR https://github.com/blakeblackshear/frigate/issues/994#issuecomment-1132320239

I'm not sure what you mean? This goes along with the favorites feature which in the beta already allows saving a clip from being deleted. 

I'm not sure how this is related to that FR. It is similar in that it deals with saving events but the implementation is entirely different. I may be missing some context

**Comment by ozett** [comment]
ok,
permanent storage of some clips, change remaining disk-space.
deleting of clips also.

would be nice to see somehwere how much recording-time is left after storage or deleting.
i know, thats highly dynamic, but there could AI along with some estimation on historical data...

but maybe that unrelated here and must be out somewhere else.... 
i dreamed of a pop-up on permanent storage or on deleting clips, thats says: 
" you have estimated 3 hrs recording time left" or " you gained 3 days recording time"

**Comment by NickM-27** [comment]
@ozett I see what you mean. Yeah that wouldn't be related to this but could be something for the future. Maybe add your comments to the issue you linked.

**Pull request merged**
