### PR TITLE
Reuse open connection, fix #920

### LINKED ISSUE #920: [BUG] Connection already opened
**Describe the bug**
A clear and concise description of what your issue is.
After a while / restart or Home-Assistant I get a connection error. Does this mean it did not close the connection when restarting HASS?
**Version of frigate**
1.13
**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
not related```

**Frigate container logs**
```
https://pastebin.ddns.me/hoviyalasa.rb```

**Frigate stats**
```json
Internal Server Error```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Computer Hardware**
 - OS:  Ubuntu, 
 - Install method: Addon

 - Coral Version: PCIe
 - Network Setup: WiFi]

### PR DESCRIPTION
**Pull request by fl42**
Hello,

This PR it's an attempt to fix #920 
What is your opinion on the fix?

As the problem appears randomly, I don't know if this fix totally solves it.

EDIT: it runs for few days without any issue of my side

### CODE REVIEW

**Comment by blakeblackshear** [comment]
I _think_ the proper fix is described [here](http://docs.peewee-orm.com/projects/flask-peewee/en/latest/gevent.html). This issue started after adding gevent to handle websockets.

**Comment by fl42** [comment]
I'm not a big fan of monkeypatching the thread module but...I agree that sharing connections between threads is not the best option too

I'm considering rewriting the WS part (or event the full API) using [FastAPI](https://fastapi.tiangolo.com/advanced/websockets/)
Would you accept such a big refactoring @blakeblackshear?

**Comment by blakeblackshear** [comment]
I don't know much about fastapi, but yes. I am not sure how it will impact the other parts of frigate given you must start it with uvicorn.

**Comment by fl42** [comment]
Ok I'll try on side

**Comment by b3nj1** [comment]
FWIW, I this PR also fixed the issue on my side. Further, it seems to have reduced the load on the server by something like 50-60%!! 
Is there a reason that it's not safe to re-use the connection as in this PR?

- Benjamin

**Comment by blakeblackshear** [comment]
I'm not sure why it would change the server load. I plan to address this in a different way for the next release.

**Comment by fl42** [comment]
@blakeblackshear Would you consider merging this fix with a patch release bump? (before 0.9.0 I mean)
The bug is quite annoying when the API is heavy loaded (e.g., when Home Assistant copy snapshot on event)

**Comment by blakeblackshear** [comment]
No. I don't plan to solve it this way.

**Pull request closed without merging**
