### PR TITLE
Improve audio conversion tip

### PR DESCRIPTION
**Pull request by felipecrs**
I spent quite a good time to figure out that `-c copy` overlaps with `-c:a aac`.

### CODE REVIEW

**Comment by felipecrs** [comment]
Hey maintainers, I think this one is quite simple and would be a good addition to the docs. No?

**Comment by felipecrs** [comment]
@blakeblackshear you may want to take a look at this one.

**Comment by blakeblackshear** [comment]
I haven't merged this because I would rather show a full example of the output args with audio added. This still seems just as confusing.

**Comment by felipecrs** [comment]
Sure, let me see if I can enhance this.

**Comment by felipecrs** [comment]
@blakeblackshear done. Please let me know if it looks better.

**Pull request merged**
