### PR TITLE
Limit exposed go2rtc api to bare minimum

### PR DESCRIPTION
**Pull request by blakeblackshear**

### CODE REVIEW

**Review by NickM-27 — APPROVED** [review]

**Comment by skrashevich** [comment]
This is a terrible patch. I demonstrated vulnerability not at all for this :(

**Comment by AlexxIT** [comment]
It seems at the moment go2rtc doesn't provide a better way to protect against this sort of thing

**Comment by rodrigoratan** [comment]
Can someone please give me a explanation why it is needed? Will I be able to access the go2rtc config and stream pages outside frigate?

**Comment by NickM-27** [comment]
> Can someone please give me a explanation why it is needed?

There are issues with the api being open including the ability to execute code using the `exec` type in go2rtc as well as camera passwords being exposed in the stream info. 

This change still allows stream info to be retrieved from within frigate for troubleshooting reasons but with the passwords cleaned out

> Will I be able to access the go2rtc config and stream pages outside frigate?

go2rtc config is always edited and viewed within the frigate config so that has not changed. This also does not affect the rtsp restream and as a user if you want to view go2rtc then you simply need to map port 1984

**Comment by T3chArmy** [comment]
@blakeblackshear @NickM-27 Not sure if it's something with my configuration or what, but attempting to access frigate:5000/api/go2rtc/streams seems to throw an internal server error.

**Comment by NickM-27** [comment]
@T3chArmy need to see frigate logs then

**Comment by T3chArmy** [comment]
@NickM-27
`2023-12-02 02:45:02.941327916  [2023-12-02 02:45:02] frigate.http                   ERROR   : Exception on /go2rtc/streams [GET]
2023-12-02 02:45:02.941336793  Traceback (most recent call last):
2023-12-02 02:45:02.941342996    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
2023-12-02 02:45:02.941347996      response = self.full_dispatch_request()
2023-12-02 02:45:02.941353341    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
2023-12-02 02:45:02.941358103      rv = self.handle_user_exception(e)
2023-12-02 02:45:02.941363442    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
2023-12-02 02:45:02.941367765      rv = self.dispatch_request()
2023-12-02 02:45:02.941372918    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
2023-12-02 02:45:02.941378041      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-12-02 02:45:02.941382850    File "/opt/frigate/frigate/http.py", line 1361, in go2rtc_streams
2023-12-02 02:45:02.941387478      producer["url"] = clean_camera_user_pass(producer["url"])
2023-12-02 02:45:02.941391527  KeyError: 'url'`

**Comment by T3chArmy** [comment]
@NickM-27 Additional info. I believe this is related to me using a nest camera in Go2RTC. The JSON does not contain a url.

Manually accessed the Go2RTC streams output. Here's the section for the nest cam

```
"rear_garage":{"producers":[{"type":"Nest active producer","remote_addr":"udp4 host 142.250.111.127:19305","medias":["video, recvonly, H264","video, sendonly, H264","audio, recvonly, OPUS/48000/2","audio, sendonly, OPUS/48000/2"],"receivers":["97 H264, bytes=555331748, senders=1","101 OPUS/48000/2, bytes=19975306, senders=0"],"recv":591560315},{"url":"ffmpeg:rear_garage#audio=opus"}],"consumers":[{"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/rear_garage","remote_addr":"127.0.0.1:41196","user_agent":"FFmpeg Frigate/0.13.0-595fa3d","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=control:trackID=0\r\n","medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"senders":["96 H264, bytes=555331748, receivers=1"],"send":563467686}]}
```

**Comment by troykelly** [comment]
> > Will I be able to access the go2rtc config and stream pages outside frigate?
> 
> go2rtc config is always edited and viewed within the frigate config so that has not changed. This also does not affect the rtsp restream and as a user if you want to view go2rtc dashboard then you simply need to map port 1984 and view it there

If you want to continue accessing streams (ie the stream URL's from Frigate) - this change completely removes that functionality. With this change in-place go2rtc is a tool for internal Frigate use only. (Perhaps this was what was originally intended - but, I find go2rtc + frigate very valuable together)

*If somebody finds this because they used the go2rtc functionality:*

If you are using Traefik in front of Frigate, go2rtc's functionality can be restored at the documented URL with the use of `PathPrefix`.

For example:

```yaml
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      # #----------------------------------------------- middleware for: frigate -----------------------------------------------
      - "traefik.http.middlewares.go2rtc-strip-webrtc-prefix.stripprefix.prefixes=/live/webrtc"
      - "traefik.http.middlewares.go2rtc-strip-webrtc-prefix.stripprefix.forceSlash=false"
      # #----------------------------------------------- routers for: frigate --------------------------------------------------
      # http internal
      - traefik.http.routers.frigate-http-internal.rule=(Host(`${DOMAIN}`) && (PathPrefix(`/`) && !PathPrefix(`/live/webrtc`)) && ClientIP(`192.0.2.0/24`, `2001:db8:1000:1000::/64`, `198.51.100.0/24`, `2001:db8:2000:2000::/64`, `203.0.113.0/24`, `2001:db8:a000:b000::/64`))
      - traefik.http.routers.frigate-http-internal.entrypoints=http
      - traefik.http.routers.frigate-http-internal.middlewares=servicests,block-apple,https-redirect,reporturi
      - traefik.http.routers.frigate-http-internal.service=frigate
      # https internal
      - traefik.http.routers.frigate-https-internal.rule=(Host(`${DOMAIN}`) && (PathPrefix(`/`) && !PathPrefix(`/live/webrtc`)) && ClientIP(`192.0.2.0/24`, `2001:db8:1000:1000::/64`, `198.51.100.0/24`, `2001:db8:2000:2000::/64`, `203.0.113.0/24`, `2001:db8:a000:b000::/64`))
      - traefik.http.routers.frigate-https-internal.entrypoints=http3
      - traefik.http.routers.frigate-https-internal.service=frigate
      - traefik.http.routers.frigate-https-internal.tls.certresolver=${DNS_PROVIDER}
      - traefik.http.routers.frigate-https-internal.middlewares=gzip,limit,reporturi,block-apple
      # #----------------------------------------------- routers for: go2rtc --------------------------------------------------
      # http internal
      - traefik.http.routers.go2rtc-http-internal.rule=(Host(`${DOMAIN}`) && PathPrefix(`/live/webrtc`) && ClientIP(`192.0.2.0/24`, `2001:db8:1000:1000::/64`, `198.51.100.0/24`, `2001:db8:2000:2000::/64`, `203.0.113.0/24`, `2001:db8:a000:b000::/64`))
      - traefik.http.routers.go2rtc-http-internal.entrypoints=http
      - traefik.http.routers.go2rtc-http-internal.middlewares=servicests,block-apple,https-redirect,reporturi
      - traefik.http.routers.go2rtc-http-internal.service=go2rtc
      # https internal
      - traefik.http.routers.go2rtc-https-internal.rule=(Host(`${DOMAIN}`) && PathPrefix(`/live/webrtc`) && ClientIP(`192.0.2.0/24`, `2001:db8:1000:1000::/64`, `198.51.100.0/24`, `2001:db8:2000:2000::/64`, `203.0.113.0/24`, `2001:db8:a000:b000::/64`))
      - traefik.http.routers.go2rtc-https-internal.entrypoints=http3
      - traefik.http.routers.go2rtc-https-internal.service=go2rtc
      - traefik.http.routers.go2rtc-https-internal.tls.certresolver=${DNS_PROVIDER}
      - traefik.http.routers.go2rtc-https-internal.middlewares=gzip,limit,reporturi,block-apple,go2rtc-strip-webrtc-prefix
      #====================================================== services ===========================================================
      - traefik.http.services.frigate.loadbalancer.server.port=5000
      - traefik.http.services.go2rtc.loadbalancer.server.port=1984
```

**Comment by rossmarkflo** [comment]
This is kind of stupid - I used the HTTP(s) URL to stream to a Google Nest when motion was detected. The Update to 13 removed this functionality.

Now I have to load yet another software to accomplish this?

Can't we just make this disabled by default and let the end-user choose if we want this functionality?

**Comment by NickM-27** [comment]
Did you not read any of the above comments? You don't have the run any more software, just map port 1984 and use go2rtc like normal.

**Comment by rossmarkflo** [comment]
Well - map it where? I tried a few things, but it's still not clear to me..

I used an URL like this:
http://frigate:5000/live/webrtc/api/stream.mp4?src=CAM

1984 was the main dashboard, where you could choose all these URLs, if I am not mistaken.. 

Sorry if I didn't specify this earlier.. I feel just stuck right now, and didn't find anything but the above via **Traefik** ... what just adds unnecessary complexity IMO... I understand there is a security risk, though, but my Frigate isn't exposed externally, so I just use it within my LAN what limits the attack surface tremendously - unless I missed something.

**Comment by NickM-27** [comment]
Mapping port 1984 means mapping from the container to host. Just adding a single line to the docker compose or editing the HA addon config. 

Then it would be accessed at frigate_ip:1984

**Comment by rossmarkflo** [comment]
You are a life-saver... but I want to summarize this for others:

In the DOCKER docker-cokmpose.yml file you want to add a line with 1984, like below:

`
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984" #Go2RTC API
`

The new line:
      **- "1984:1984" #Go2RTC API**

And the URL for your cameras will change, instead of port 5000 you will use port **1984** now, once you recreated the docker container with the new composer file.

http://frigate_ip:1984/live/webrtc/api/stream.mp4?src=CAM

Thanks Nick for the Help, didn't realize it was that easy, the documentation definitive should be updated for this, unless it is already and I really missed it.

Hope this helps others!

**Pull request merged**
