### PR TITLE
Update iframe interval recommendation

### PR DESCRIPTION
**Pull request by hawkeye217**
## Proposed change

Ensure the recommendation for i-frame interval is consistent throughout the docs (1x framerate).

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code
- [x] Documentation Update

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Ruff (`ruff format frigate`)

### CODE REVIEW

**Comment by NickM-27** [comment]
I don't think this is right, this is what I use for my recordings too, is there a reason to change this for the recording config?

**Comment by hawkeye217** [comment]
> I don't think this is right, this is what I use for my recordings too, is there a reason to change this for the recording stream?

For users who use the recording stream with go2rtc/live view, we recommend 1x already in the live view docs. A user was confused about this example here because it was different.

**Comment by NickM-27** [comment]
For the recording config this will considerably increase storage usage or reduce quality given a constant bitrate. IMO these docs should stay the same and the live docs can make it more clear that it is for the stream used for detection.

**Comment by NickM-27** [comment]
Either that or the recommendation needs to explain the difference between prioritizing streaming performance or recording storage efficiency

**Comment by hawkeye217** [comment]
That's fair. I'll update the live view docs too then.

**Review by NickM-27 — APPROVED** [review]

**Pull request merged**
