### PR TITLE
0.2.0 Release

### LINKED ISSUE #21: Run FFmpeg in a separate process to leverage hardware acceleration
I was looking into support for hardware accelerated decoding and realized that OpenCV doesn’t use the hardware acceleration built into FFmpeg. I did some basic tests, and it makes a substantial difference. On the laptop where I am running frigate, decoding a 25FPS 1080p stream uses about 25% of a single CPU. Switching FFmpeg to use hardware acceleration drops that to <2%. I can read raw frames form a separate FFmpeg process like [this](https://github.com/kkroening/ffmpeg-python/blob/master/examples/tensorflow_stream.py). Once I add support for this, even low powered machines should be able to perform object detection on many cameras.

### LINKED ISSUE #39: control label formatting for detected objects
Noticed this today on a successful object scan, a person is picked up a decent distance from the camera (so they are pretty small) but the label drawn obscures the person.

small_person

Is it possible/feasible to control the label (eg remove the red background), in an effort to not obscure the detected object?

### LINKED ISSUE #40: Allow reducing the ingress framerate from RTSP stream
Per request on the [Home Assistant community](https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras/103107/259):

Is there anyway to limit the frame rate that python is analyzing? My WYZE cameras do not have a way to change the frame rate in the RTSP stream. This means frigate processes every single frame (multiplied by my 6 regions across 2 cameras) and destroys my CPU/maxes out the Coral buffer queue.

I noticed in the README you mention a tip about limiting the frame rate to lower the CPU usage, but I am unable to do that in my setup without pre-processing the video first.

### LINKED ISSUE #46: Region and Mask information
Maybe a bit of a newb question regarding opencv and tensorflow but what is the purpose of the back-mask.bmp and is there a tool people are using to plan/make the region sizes and coordinates up?

### PR DESCRIPTION
**Pull request by blakeblackshear**
This release includes the following:

- Video decoding is now done in an FFMPEG sub process which enables hardware accelerated decoding of video streams. For me, this reduced CPU usage for decoding by 60-70%. (Fixes #21)
- New `take_frame` option to reduce framerates with frigate when the camera doesnt support it (Fixes #40)
- Tweaked the position of the labels to avoid overlapping with detected objects (Fixes #39)
- Added the area of the object to the label to help determine min_person_area values (thanks @aav7fl)
- Greatly reduced Docker image size, from ~2GB to 450MB
- Added support for custom Odroid-XU4 build (unfortunately, I wasn't able to get the Coral performance to be good enough for me with this board)
- Latest Coral drivers from Google
- Added a benchmarking script to test inference times
- Added some comments to better document config options (Fixes #46)

### CODE REVIEW

**Comment by tubalainen** [comment]
LOVE this release! Works wonders for my setup! <3

**Comment by scstraus** [comment]
Yeah huge improvement!

**Comment by billimek** [comment]
Do we think this is good-to-merge?

**Comment by cwhits** [comment]
>hardware accelerated decoding of video streams

does this work on coreos or did you give up on that front?

**Comment by blakeblackshear** [comment]
I may circle back to it later. It will require a custom coreos build that I would have to maintain. I will probably end up running this on a separate server that does not run coreos.

**Pull request merged**
