### PR TITLE
Refactor process management

### PR DESCRIPTION
**Pull request by gtsiam**
## Proposed change

There are lots and lots of changes (as tends to happen with refactors), but the headline changes are:

- The Camera class, which tries to manage some of the camera-specific related code. It's still not great, but it's getting there.
- Switch from the "fork" start method to "forkserver". (Apparently they made [the switch](https://github.com/python/cpython/commit/b65f2cdfa77d8d12c213aec663ddaaa30d75a4b2) a couple of days ago for 3.14). This will essentially eliminate many of the deadlocks caused by mixing threading and multiprocessing without us having to maintain careful start order.

Take a look at the commit messages for the rest.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)[^1]
- [ ] New feature
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code

[^1]: In the sense that this should stop the obscure deadlocks in internal python datastructures inherent to fork.

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Ruff (`ruff format frigate`)

### CODE REVIEW

**Comment by NickM-27** [comment]
Just a heads up, we are moving towards a release for 0.15 so these refactors will be targeted at 0.16 now 👍

**Comment by gtsiam** [comment]
Well, fk. I was under the impression you were planning to keep the 0.16 branch back. I was about to hit ready for review, but off to merge conflict hell with me. Not sure why not just track dev if you were planning to pull 0.16 up with it.

Anyway, while I do that, if you wanna look at the code in the meantime, I'm not making any more changes. Shutdown now takes ~13 seconds from 100+ seconds it used to take for me with 8 cameras. Process shutdown is ~1 second, the rest is code I haven't dealt with yet. But the diff is large enough already, so I'm calling it here (-200 lines of code total tho).

---

2 questions:
- `process_clip.py`: Does anybody use that and should I update it to follow the refactoring? Does anybody use it? #7020 seems to imply its abandoned.
- `benchmark.py`: Same question. Is this used by anyone, or was it a one-off script, way back when?
- `benchmark_motion.py`: Ditto.

**Comment by gtsiam** [comment]
Actually, before I touch any merge conflicts, should I merge to dev or to 0.16? Merging to 0.16 seems completely pointless since its just one commit behind.

**Comment by NickM-27** [comment]
`dev` represents the 0.15 release. We may have some smaller changes / fixes but soon 0.15 beta 1 will be released. 0.16 branch is meant to hold the larger changes that we do not want to include in the 0.15 release

**Comment by NickM-27** [comment]
> process_clip.py: Does anybody use that and should I update it to follow the refactoring? Does anybody use it? https://github.com/blakeblackshear/frigate/issues/7020 seems to imply its abandoned.

I have used it on occasion for testing, it works fine for me

the other two are similar, used from time to time for specific things when needed

**Comment by NickM-27** [comment]
We can see what other maintainers think but in my opinion I would want this PR broken into multiple parts. This is a lot to review and test each specific part to ensure there are no hidden bugs or other issues introduced. With it targeting 0.16 there will be a good amount of time to find them but I believe we would still like to be able to thoroughly test some of these changes specifically.

**Comment by hawkeye217** [comment]
> We can see what other maintainers think but in my opinion I would want this PR broken into multiple parts. This is a lot to review and test each specific part to ensure there are no hidden bugs or other issues introduced. With it targeting 0.16 there will be a good amount of time to find them but I believe we would still like to be able to thoroughly test some of these changes specifically.

Agreed. In my experience, large "refactor" PRs in any project always tend to introduce some kind of regression or bug. Having related changes that can be tested and merged separately makes it easier to track them down.

**Comment by gtsiam** [comment]
> I would want this PR broken into multiple parts. This is a lot to review and test each specific part to ensure there are no hidden bugs or other issues introduced.

That's understandable but, let me do a bit of friendly ranting:
- I don't have the luxury to self-review and merge PRs immediately like you do.
- Same, but mentioned twice for emphasis.
- ~~Mine~~ Everyone else's PRs tend to just sit there until someone gets around to reviewing them. Typically that takes days. That's understandable, but you should also understand that my out-of-tree changes will start ballooning if that's the case. The process that works for you, who can just review and merge PRs immediately, will not work for those who can't.
- Why in the world are you squashing every. single. commit. Commits are NOT PRs. PRs are a unit to review. Commits are a unit of code change. Some code changes go hand-in-hand, as in this case.
- Frigate's architecture. Currently it's written like a collection of bash scripts, not as a long-running server process.
- The monolithic docker container. That is not a container, it's an entire damn VM at this point.
- The structure of the config. Until I read the code, I had no idea half the keys were just overlays for each CameraConfig.
- Please make dependabot stfu.

Okay, frustrations vented.

I really don't want to break this PR up, since it would involve essentially rewriting much of it. This is not my day-job. That said, I understand where you're coming from and I'd be willing to make a new PR with clean commits if you agree to freeze the 0.16 branch for a couple of days. I really don't fancy more merge conflicts.

**Comment by gtsiam** [comment]
You know what? I don't care. I'll slowly pull the important changes from this PR after 0.15 is released.

I refuse to send anything to the 0.16 branch, due to the ungodly amount of merge conflicts involved with doing parallel development while refactoring. Everything will come to dev over time, if I can be bothered.

**Pull request closed without merging**
